export type BlockType =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'ul'; items: string[] }
  | { type: 'ol'; items: string[] }
  | { type: 'callout'; emoji: string; text: string }
  | { type: 'table'; headers: string[]; rows: string[][] }
  | { type: 'divider' };

export type BlogCategory = 'Planning' | 'Budget' | 'India' | 'Asia' | 'Europe' | 'Tips';

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  readTime: number;
  category: BlogCategory;
  tags: string[];
  coverPhoto: string;
  citySlug?: string;
  content: BlockType[];
}

export const allPosts: BlogPost[] = [
  {
    slug: 'best-time-to-visit-bali',
    title: 'Best Time to Visit Bali (2025): Month-by-Month Guide',
    excerpt: 'Planning a trip to Bali? Here is exactly when to go — dry season deals, surf windows, festival dates, and the months locals wish you\'d avoid.',
    date: '2025-05-20',
    readTime: 8,
    category: 'Planning',
    tags: ['Bali', 'Indonesia', 'Beach', 'Planning'],
    coverPhoto: 'photo-1537996194471-e657df975ab4',
    citySlug: 'bali',
    content: [
      { type: 'p', text: 'Bali is one of those destinations that looks good in every travel photo — but timing your trip correctly can be the difference between a dream holiday and a soggy, overpriced disappointment. The island has two distinct seasons, a handful of shoulder-month sweet spots, and festival dates that can either enrich your trip or make finding a room nearly impossible.' },
      { type: 'p', text: 'Here is everything you need to know to pick the right month.' },
      { type: 'h2', text: 'Bali\'s Two Seasons at a Glance' },
      { type: 'table', headers: ['Season', 'Months', 'What to Expect', 'Prices'], rows: [
        ['Dry Season', 'April – October', 'Sunny days, low humidity, great for beaches', 'Peak / High'],
        ['Wet Season', 'November – March', 'Afternoon downpours, lush rice terraces', 'Low / Budget'],
        ['Sweet Spot', 'April–May, September', 'Dry weather, fewer crowds, decent prices', 'Mid'],
      ]},
      { type: 'h2', text: 'Dry Season: April to October' },
      { type: 'p', text: 'This is when Bali is at its best for most travellers. Skies are blue, the humidity is manageable, and the ocean is calm enough for snorkelling and diving around Nusa Penida and Amed. July and August are peak season — schools are out across Europe and Australia, prices are at their highest, and popular temples like Tanah Lot can feel uncomfortably crowded.' },
      { type: 'h3', text: 'July & August — Busy but Beautiful' },
      { type: 'p', text: 'Expect beach clubs to be packed, villa prices to be 30–50% higher than low season, and Kuta to feel like a sunburnt theme park. If you\'re going in peak season, book accommodation at least three months ahead and consider staying in Ubud or Canggu instead of Seminyak or Kuta — the vibe is better and prices are more forgiving.' },
      { type: 'h3', text: 'April, May & September — The Sweet Spots' },
      { type: 'p', text: 'These are the best months to visit Bali if you want dry weather without the peak-season crush. April and May sit right before the European summer rush, while September comes just after it ends. You get almost identical weather to July-August with 20–30% lower accommodation prices and noticeably thinner crowds at major attractions.' },
      { type: 'callout', emoji: '💡', text: 'April and September are hands-down the best months to visit Bali. Dry weather, lower prices, and you can actually walk through Ubud\'s rice terraces without shoulder-to-shoulder tourists.' },
      { type: 'h2', text: 'Wet Season: November to March' },
      { type: 'p', text: 'The wet season does not mean it rains all day every day. You will typically get three to five hours of bright sunshine in the morning, followed by a heavy downpour for an hour or two in the afternoon, then usually clearing again by evening. If you structure your itinerary around this pattern (temples and outdoor activities in the morning, spa treatments or café-hopping in the afternoon), the wet season is very manageable.' },
      { type: 'h3', text: 'December — Expensive Despite the Rain' },
      { type: 'p', text: 'Christmas and New Year are curiously expensive in Bali despite being deep in wet season. Australians on summer holiday and global NYE tourists push prices up significantly. If you\'re travelling in December, book early or shift your travel to the first two weeks of the month before the holiday surge.' },
      { type: 'h3', text: 'January & February — Best Budget Months' },
      { type: 'p', text: 'These are the cheapest months to visit Bali. You can find villas with private pools in Ubud for half the August price. The rice terraces are an impossibly vivid green, waterfalls are at their most impressive, and many of Bali\'s best restaurants have short or no queues. Pack a light rain jacket and embrace it.' },
      { type: 'h2', text: 'Bali\'s Key Festivals & Events' },
      { type: 'ul', items: [
        'Nyepi (Balinese New Year) — Usually March/April. Bali goes completely silent for 24 hours. No traffic, no lights, no going outside. The airport closes. Extraordinary to experience but book well in advance.',
        'Galungan & Kuningan — Every 210 days on the Balinese calendar. Temples are decorated with tall bamboo poles (penjor). A beautiful time to visit.',
        'Bali Arts Festival — June to July. Month-long celebration of traditional dance, music and crafts in Denpasar.',
        'Kuta Carnival — October. Beach events, surfing competitions, and live music.',
      ]},
      { type: 'h2', text: 'Month-by-Month Quick Reference' },
      { type: 'table', headers: ['Month', 'Weather', 'Crowds', 'Price', 'Verdict'], rows: [
        ['January', '🌧️ Wet', 'Low', '💚 Cheap', 'Great for budget travel'],
        ['February', '🌧️ Wet', 'Low', '💚 Cheap', 'Best time to save money'],
        ['March', '🌦️ Mixed', 'Low-Mid', '💛 Mid', 'Nyepi — plan around it'],
        ['April', '☀️ Dry', 'Low-Mid', '💛 Mid', 'Sweet spot — highly recommended'],
        ['May', '☀️ Dry', 'Mid', '💛 Mid', 'Great all-round choice'],
        ['June', '☀️ Dry', 'Mid-High', '🔴 High', 'Arts Festival — good for culture'],
        ['July', '☀️ Dry', 'Very High', '🔴 Peak', 'Busy and expensive'],
        ['August', '☀️ Dry', 'Very High', '🔴 Peak', 'Book months ahead'],
        ['September', '☀️ Dry', 'Mid', '💛 Mid', 'Sweet spot — highly recommended'],
        ['October', '🌦️ Mixed', 'Mid', '💛 Mid', 'Good value, slight rain risk'],
        ['November', '🌧️ Wet', 'Low', '💚 Cheap', 'Off-peak bargains'],
        ['December', '🌧️ Wet', 'High', '🔴 High', 'Xmas/NYE surcharges'],
      ]},
      { type: 'h2', text: 'Our Final Recommendation' },
      { type: 'p', text: 'For first-time visitors who want reliable sunshine and manageable crowds: visit in April or September. For budget travellers who can tolerate afternoon rain: January or February offer the best value. Avoid July and August unless you\'re booking six months in advance and don\'t mind paying a premium.' },
      { type: 'p', text: 'Whatever month you choose, Bali will deliver: extraordinary temples, world-class food, and a warmth — both climatic and human — that keeps travellers coming back year after year.' },
    ],
  },

  {
    slug: 'goa-vs-kerala',
    title: 'Goa vs Kerala 2025: Which Indian State Should You Visit?',
    excerpt: 'Two very different versions of paradise. Goa is parties and Portuguese churches; Kerala is backwaters and Ayurveda. Here\'s how to choose.',
    date: '2025-05-15',
    readTime: 9,
    category: 'India',
    tags: ['Goa', 'Kerala', 'India', 'Beaches', 'Comparison'],
    coverPhoto: 'photo-1512343879784-a960bf40e7f2',
    citySlug: 'goa',
    content: [
      { type: 'p', text: 'India\'s two most famous coastal states sit a few hours apart on the western Malabar Coast, yet they feel like completely different countries. Goa is all about Portuguese-tinged architecture, legendary beach parties, and a laid-back hippie-meets-luxury vibe. Kerala is peaceful backwaters, ancient Ayurveda retreats, and some of the most refined cuisine in India.' },
      { type: 'p', text: 'Both are wonderful. But they are emphatically not interchangeable. Here is the honest breakdown.' },
      { type: 'h2', text: 'The Beaches' },
      { type: 'h3', text: 'Goa' },
      { type: 'p', text: 'Goa has 100 kilometres of coastline divided roughly into North and South Goa — and the difference between the two is enormous. North Goa (Baga, Calangute, Anjuna) is where the parties, beach clubs, and tourist infrastructure concentrate. South Goa (Palolem, Agonda, Colva) is quieter, cleaner, and genuinely beautiful. If you are coming for beaches alone, South Goa\'s Palolem — a horseshoe bay with gentle waves and towering palms — is one of the best beaches in Asia.' },
      { type: 'h3', text: 'Kerala' },
      { type: 'p', text: 'Kerala\'s beaches are less famous than Goa\'s but genuinely special. Varkala is a dramatic red-cliffside beach town with budget guesthouses and great yoga. Mararikulam is a quiet fishing village with pristine sands. Kovalam, near Thiruvananthapuram, is the most developed Kerala beach and has a pleasant bay with calm waters. Kerala beaches are better for peaceful swimming, while Goa is better for people-watching and nightlife.' },
      { type: 'callout', emoji: '🏖️', text: 'Verdict on beaches: Goa wins for energy and variety. Kerala wins for peace and natural beauty. If you want to unplug — go Kerala. If you want beach clubs — go Goa.' },
      { type: 'h2', text: 'Food' },
      { type: 'h3', text: 'Goa' },
      { type: 'p', text: 'Goan food is unlike anything else in India. The Portuguese influence left behind a cuisine built on vinegar, pork, and coconut. Must-eats include fish curry rice (the unofficial state dish), prawn balchão (a fiery pickle-style preparation), sorpotel (spiced pork offal — not for the faint-hearted), and bebinca (a rich layered coconut dessert). Seafood in Goa is excellent and cheap if you know where to go — skip the tourist-facing shacks on the main beaches and walk five minutes to find a local joint.' },
      { type: 'h3', text: 'Kerala' },
      { type: 'p', text: 'Kerala cuisine is one of India\'s great underrated food traditions. Expect an enormous amount of coconut — in curries, chutneys, and cooking oil. The Kerala sadya (a vegetarian feast served on a banana leaf with 20+ dishes) is a must-experience at least once. Seafood is exceptional: karimeen (pearl spot fish) cooked in banana leaf is the signature dish. For breakfast, try appam with stew — a lacy rice-flour crepe with a thin vegetable or chicken coconut curry. Kerala also has the best filter coffee in India, full stop.' },
      { type: 'callout', emoji: '🍛', text: 'Verdict on food: Both states have outstanding food cultures. Kerala\'s cuisine is more refined and complex. Goa\'s is more bold and accessible for first-timers. Visit both and eat everything.' },
      { type: 'h2', text: 'Budget' },
      { type: 'table', headers: ['Category', 'Goa (₹/day)', 'Kerala (₹/day)'], rows: [
        ['Budget accommodation', '₹800–1,500', '₹700–1,200'],
        ['Mid-range hotel', '₹2,500–5,000', '₹2,000–4,000'],
        ['Meal (local restaurant)', '₹150–300', '₹100–200'],
        ['Beach shack meal', '₹300–600', 'N/A'],
        ['Backwater houseboat (per night)', 'N/A', '₹4,000–12,000'],
        ['Beer / cocktail', '₹150–250', '₹120–200 (in bars)'],
        ['Scooter rental', '₹300–400/day', '₹250–350/day'],
      ]},
      { type: 'p', text: 'Goa is slightly more expensive, especially during peak season (December–February) when beach shack prices and accommodation rates can triple. Kerala is generally better value, particularly in the cultural heartland of Fort Kochi and the hill stations of Munnar.' },
      { type: 'h2', text: 'Experiences Unique to Each' },
      { type: 'h3', text: 'Only in Goa' },
      { type: 'ul', items: [
        'Old Goa\'s UNESCO-listed Portuguese churches (Basilica of Bom Jesus)',
        'Sunset at Chapora Fort — the fort from the Dil Chahta Hai film',
        'Flea markets at Anjuna and Arpora (Saturday Night Market)',
        'Dudhsagar Falls — a 600m waterfall accessible by jeep safari',
        'Genuine trance parties at Hilltop and Curlies (if that\'s your scene)',
      ]},
      { type: 'h3', text: 'Only in Kerala' },
      { type: 'ul', items: [
        'Overnight houseboat cruise through the Alleppey backwaters',
        'Kathakali classical dance performance in Kochi',
        'Authentic Ayurveda treatments (massage, Panchakarma, shirodhara)',
        'Tea plantation walk in Munnar\'s misty highlands',
        'Periyar Wildlife Sanctuary tiger/elephant spotting',
        'A Kerala sadya feast on a banana leaf',
      ]},
      { type: 'h2', text: 'Who Should Go Where' },
      { type: 'table', headers: ['Traveller Type', 'Go to Goa', 'Go to Kerala'], rows: [
        ['Solo backpacker', '✅ Easy to meet people', '✅ Safe, easy to navigate'],
        ['Couple / honeymoon', '✅ Romantic (South Goa)', '✅ Houseboats & spa retreats'],
        ['Family with kids', '⚠️ North Goa can be rowdy', '✅ Calm, family-friendly'],
        ['Party-seeker', '✅ Best in India', '❌ Not really the vibe'],
        ['Culture / history', '✅ Portuguese heritage', '✅ Deeper cultural traditions'],
        ['Nature / wildlife', '⚠️ Limited', '✅ Forests, backwaters, hills'],
        ['Budget traveller', '✅ Cheap if you go local', '✅ Generally good value'],
        ['Foodie', '✅ Unique Goan cuisine', '✅ Outstanding Kerala food'],
      ]},
      { type: 'h2', text: 'The Verdict' },
      { type: 'p', text: 'If you have only one week in India and have never visited either state — go to Goa. It is easier to navigate, the tourist infrastructure is more developed, and the beach-culture-food combination is hard to beat for a first visit.' },
      { type: 'p', text: 'If you have already been to Goa or want something deeper and more authentically Indian — go to Kerala. The backwaters, the food, the hill stations, and the Kathakali performances will stay with you long after the trip ends.' },
      { type: 'p', text: 'Best of all: both states are reachable from each other (Goa to Kochi is a 9-hour overnight train or a 1-hour flight). Many travellers do a 2-week India trip combining both, and it is an excellent itinerary.' },
    ],
  },

  {
    slug: 'bangkok-budget-travel-guide',
    title: 'Bangkok Budget Travel Guide 2025: See the City for Under ₹4,000/Day',
    excerpt: 'Bangkok is one of the world\'s most exciting cities — and one of the most affordable. Here\'s exactly how to do it without breaking the bank.',
    date: '2025-05-10',
    readTime: 10,
    category: 'Budget',
    tags: ['Bangkok', 'Thailand', 'Budget Travel', 'Asia'],
    coverPhoto: 'photo-1508009603885-50cf7c579365',
    citySlug: 'bangkok',
    content: [
      { type: 'p', text: 'Bangkok has a reputation for blowing budgets — luxury hotels, rooftop bars, sky-high restaurants. But scratch beneath the tourist surface and you find a city where you can eat magnificently for ₹150, sleep comfortably for ₹700, and travel across town for ₹40. Bangkok rewards the traveller who is willing to do it like a local.' },
      { type: 'callout', emoji: '💰', text: 'Realistic daily budget: Backpacker ₹1,800–2,500 | Mid-range ₹3,500–5,000 | Comfortable ₹6,000–10,000' },
      { type: 'h2', text: 'Getting to Bangkok Cheaply from India' },
      { type: 'p', text: 'The best airfare from India to Bangkok (Suvarnabhumi or Don Mueang) runs through Air Asia, IndiGo\'s codeshare, or Thai AirAsia. Book 6–8 weeks ahead and you can find direct flights from Delhi, Mumbai, or Chennai for ₹8,000–15,000 return. Don Mueang airport serves low-cost carriers; Suvarnabhumi serves full-service airlines. Both have good public transport connections to the city.' },
      { type: 'h3', text: 'Airport to City' },
      { type: 'ul', items: [
        'Suvarnabhumi: Airport Rail Link (City Line) to Phaya Thai station — 30 mins, ₹160 (45 THB)',
        'Don Mueang: A1/A2 public bus to Mo Chit BTS station — 45 mins, ₹50 (15 THB)',
        'Taxi from either airport: ₹400–700 (toll + meter), perfectly safe, use the official metered queue',
        'Avoid airport taxis that approach you before the official queue — always use the meter',
      ]},
      { type: 'h2', text: 'Where to Stay on a Budget' },
      { type: 'p', text: 'Bangkok has three backpacker zones worth knowing. Khao San Road is the classic — loud, touristy, great for meeting fellow travellers, dormitories from ₹500/night. Silom/Bangrak is better for mid-range travellers: quieter, more central, and a 10-minute walk to the river. Ari neighbourhood is where Bangkok\'s young locals live — the cafés are outstanding, accommodation is good value, and you feel like you\'re living in the real city rather than a tourist bubble.' },
      { type: 'table', headers: ['Type', 'Area', 'Price (₹/night)', 'Best for'], rows: [
        ['Hostel dorm', 'Khao San Road', '₹450–700', 'Solo budget travellers'],
        ['Private hostel room', 'Silom', '₹900–1,500', 'Couples on a budget'],
        ['Budget guesthouse', 'Ari', '₹1,200–2,000', 'Mid-range, local feel'],
        ['Boutique hotel', 'Sukhumvit', '₹2,500–4,000', 'Comfortable mid-range'],
      ]},
      { type: 'h2', text: 'Food: Where to Eat Without Spending Much' },
      { type: 'p', text: 'Bangkok\'s food scene is one of the world\'s great pleasures, and the best food is usually the cheapest. Here is where to eat:' },
      { type: 'h3', text: 'Street Food Stalls (₹80–200 per dish)' },
      { type: 'p', text: 'Bangkok\'s street food won a Michelin star — not a restaurant, the entire street food culture. Pad Thai from a wok on wheels, boat noodles in a tiny shophouse, mango sticky rice from a pushcart, grilled pork skewers at midnight. The best areas: Or Tor Kor market (near Chatuchak), Yaowarat Road (Chinatown, best after 6pm), and the street stalls around Victory Monument.' },
      { type: 'h3', text: 'Must-Eat Bangkok Dishes' },
      { type: 'ul', items: [
        'Pad Kra Pao (basil stir-fry with egg on rice) — ₹100–150, available everywhere',
        'Tom Yum Goong (hot & sour prawn soup) — ₹200–350 at a sit-down restaurant',
        'Khao Man Gai (poached chicken rice) — ₹80–120, the best cheap lunch in Bangkok',
        'Som Tum (green papaya salad) — ₹80–150, order at the papaya salad specialist carts',
        'Mango Sticky Rice from Mamuang Khao Niao vendors — ₹100–150',
        'Boat noodles near Khlong Saen Saep canal — ₹40–60 per bowl',
      ]},
      { type: 'h2', text: 'Getting Around Bangkok Cheaply' },
      { type: 'p', text: 'Bangkok has genuinely good public transport if you know how to use it:' },
      { type: 'ul', items: [
        'BTS Skytrain: Covers Sukhumvit, Silom, Siam. ₹50–180 per trip. Buy a Rabbit Card for the best rates.',
        'MRT Metro: Covers Chatuchak, Chinatown, Lumphini. Similar prices to BTS.',
        'Chao Phraya River Boat: ₹40–60, a scenic and practical way to reach the Grand Palace, Wat Arun, and Chinatown.',
        'Khlong Saen Saep Canal Boat: The fastest way across Bangkok — ₹30–50, used by locals, gets crowded at rush hour.',
        'Grab (like Uber): Excellent in Bangkok, 30–50% cheaper than hailing a taxi. Essential for late nights.',
        'Metered taxi: Good value but traffic can be brutal. Always insist on the meter.',
      ]},
      { type: 'callout', emoji: '🚇', text: 'Pro tip: Buy a BTS Rabbit Card (refundable ₹175 deposit) and load it with credit. It gives you slightly discounted fares and saves you queuing for tickets every time.' },
      { type: 'h2', text: 'Best Free Things to Do in Bangkok' },
      { type: 'ul', items: [
        'Wat Pho (₹650 entry — worth every rupee for the giant reclining Buddha)',
        'Walk across the river to Wat Arun at sunrise — the pagoda catches early light beautifully',
        'Explore Chinatown (Yaowarat Road) on foot — free, and the most sensory-rich street in Thailand',
        'Chatuchak Weekend Market — free to enter, over 8,000 stalls, arrive early',
        'Lumpini Park evening walk — free, beautiful, with monitor lizards wandering the paths',
        'Flower market at Pak Khlong Talat, best at 3–5am (not for everyone, but extraordinary)',
        'Browse the riverside around Asiatique or Iconsiam without spending anything',
      ]},
      { type: 'h2', text: '3-Day Budget Itinerary' },
      { type: 'ol', items: [
        'Day 1: Grand Palace + Wat Pho in the morning (₹1,000 entry combined), lunch at a nearby local restaurant (₹150), Chao Phraya river boat to Chinatown, street food dinner on Yaowarat Road (₹400 total)',
        'Day 2: Chatuchak Weekend Market in the morning (free, budget ₹500 for shopping), afternoon at Or Tor Kor food market for lunch (₹200), evening rooftop at a free-to-enter Skybar with one drink minimum (₹500)',
        'Day 3: Damnoen Saduak Floating Market by shared minivan (₹450 total), afternoon in Ari neighbourhood for café-hopping (₹300), farewell dinner at a riverside restaurant (₹600)',
      ]},
      { type: 'p', text: 'Bangkok rewards the curious traveller. The more you wander off the tourist map — into the sois (side streets), onto the canal boats, into the neighbourhood markets — the better and cheaper it gets. Come with an open stomach and a flexible schedule.' },
    ],
  },

  {
    slug: 'first-time-japan-travel-tips',
    title: '12 Things Nobody Tells You About Visiting Japan (2025)',
    excerpt: 'Japan is extraordinary but genuinely different. Here are 12 things first-time visitors wish they\'d known — from cash culture to quiet trains to the best free experiences.',
    date: '2025-05-05',
    readTime: 7,
    category: 'Tips',
    tags: ['Japan', 'Tokyo', 'Travel Tips', 'First Time'],
    coverPhoto: 'photo-1528360983277-13d401cdc186',
    citySlug: 'tokyo',
    content: [
      { type: 'p', text: 'Japan is one of the most rewarding destinations on earth — and one of the most disorienting for first-time visitors. The country operates on a fundamentally different set of social rules, logistical norms, and cultural assumptions to anywhere else you may have been. None of it is difficult once you know it, but arriving unprepared can make your first few days unnecessarily stressful.' },
      { type: 'p', text: 'Here are the twelve things experienced Japan travellers wish someone had told them before their first trip.' },
      { type: 'h2', text: '1. Japan is Mostly a Cash Society' },
      { type: 'p', text: 'This is the biggest practical shock for most visitors. Many restaurants, temples, local shops, and even some hotels do not accept credit cards. This is changing rapidly — particularly in Tokyo — but outside major cities or in traditional establishments, cash is essential. Withdraw yen at 7-Eleven, Japan Post, or convenience store ATMs (they accept foreign cards reliably). Withdraw in large amounts to avoid repeated fees.' },
      { type: 'callout', emoji: '💴', text: 'Withdraw ¥30,000–50,000 (₹15,000–25,000) at once when you land. You will use it. Convenience store ATMs (7-Eleven, Lawson, FamilyMart) are the most reliable for foreign cards.' },
      { type: 'h2', text: '2. Convenience Stores Are Genuinely Excellent' },
      { type: 'p', text: '7-Eleven, Lawson, and FamilyMart in Japan are nothing like their counterparts elsewhere. They sell freshly made onigiri (rice balls) for ¥120, hot ramen, surprisingly good sandwiches, ATMs, phone chargers, event tickets, and will print documents for you. Many budget travellers eat primarily from convenience stores and eat extremely well. The egg salad sandwich and nikuman (steamed pork bun) are staples.' },
      { type: 'h2', text: '3. The JR Pass May Not Save You Money' },
      { type: 'p', text: 'The Japan Rail Pass is a flat-fee unlimited shinkansen pass sold to foreign tourists. It sounds like a great deal, but it only makes financial sense if you are travelling extensively between cities. If you are spending most of your time in Tokyo or Osaka/Kyoto, calculate your actual journeys first — a single Tokyo-Kyoto-Tokyo shinkansen return costs roughly ¥28,000 (₹14,000), and a 7-day JR Pass costs ¥50,000 (₹25,000). Do the maths before buying.' },
      { type: 'h2', text: '4. You Cannot Put Trash in Your Pocket and Walk Away' },
      { type: 'p', text: 'Japan has almost no public rubbish bins. Yet the streets are immaculate. The reason: Japanese people carry their rubbish home or to a convenience store bin. Arrive expecting this, bring a small bag for your rubbish, and you will be fine. Trying to find a bin to throw away your convenience store packaging for 45 minutes while walking through Shibuya is a rite of passage — now you can skip it.' },
      { type: 'h2', text: '5. Trains Are Quiet — And That\'s the Rules' },
      { type: 'p', text: 'On trains and subways, phone calls are strongly discouraged. Eating is generally frowned upon (allowed on long-distance shinkansen, not on metro lines). People do not talk loudly. Silence is comfortable and expected. Lower your voice, put your phone on silent, and you will immediately seem more like a considerate traveller and less like an oblivious tourist.' },
      { type: 'h2', text: '6. Bowing Has Simple Rules' },
      { type: 'p', text: 'You do not need to master the complex social hierarchy of Japanese bowing. For tourists, a simple 15-degree head nod when greeting someone, thanking someone, or saying goodbye is universally appropriate and always appreciated. Do not bow and shake hands simultaneously — choose one. Japanese people dealing with tourists are used to handshakes and will not be offended.' },
      { type: 'h2', text: '7. Tipping is Not Done — and Can Be Insulting' },
      { type: 'p', text: 'Do not tip in Japan. Not in restaurants, not for taxi drivers, not for hotel staff. Tipping implies the person is not paid fairly for their work, which can cause offense. The service in Japan is already the best in the world — it does not need a tip to motivate it.' },
      { type: 'h2', text: '8. Japan is Not as Expensive as You Think' },
      { type: 'p', text: 'Japan has a reputation for being extremely expensive, but for budget-conscious travellers it is often cheaper than major European cities. A bowl of ramen from a restaurant costs ¥700–1,000 (₹350–500). A set lunch at a restaurant is ¥900–1,300 (₹450–650). A capsule hotel costs ¥2,500–4,000/night (₹1,250–2,000). The expensive things in Japan are department store food halls, tourist-facing sushi counters, and high-end ryokan stays. Budget travellers can live very well.' },
      { type: 'h2', text: '9. Get an IC Card on Day One' },
      { type: 'p', text: 'IC cards (Suica, Pasmo, ICOCA) are reloadable transit cards that work on almost every train, subway, and bus in Japan. More usefully, they also work at convenience stores, vending machines, and many restaurants. You can now add a Suica card directly to your iPhone or Android. Do this at the airport before you do anything else — it will make every day simpler.' },
      { type: 'h2', text: '10. Vending Machines Are Everywhere and Wonderful' },
      { type: 'p', text: 'Japan has approximately one vending machine for every 23 people. They sell hot and cold canned coffee, tea, sports drinks, and sometimes umbrellas, neckties, and sake. Hot canned coffee (缶コーヒー, kan kōhī) from a vending machine on a cold day is one of the simple joys of Japanese travel. Budget ¥120–150 per drink.' },
      { type: 'h2', text: '11. The Best Experiences Are Often Free' },
      { type: 'ul', items: [
        'Senso-ji Temple in Asakusa — free to enter (¥200 for the main hall, skip it and just explore the grounds)',
        'Meiji Jingu shrine and forest in Harajuku — free',
        'Shibuya Crossing at rush hour — stand on the second floor of Starbucks for the best view',
        'TeamLab Planets/Borderless require tickets (¥3,200+) but the free digital art installations around Odaiba are extraordinary',
        'Yanaka neighbourhood — the best-preserved old Tokyo street, free to wander',
        'Mt. Fuji from afar: free from the observation deck at Chureito Pagoda (small entry fee) or from a clear-day train window',
      ]},
      { type: 'h2', text: '12. Download These Apps Before You Land' },
      { type: 'ul', items: [
        'Google Maps — works well in Japan; download offline maps for Tokyo, Osaka, Kyoto',
        'Google Translate with Japanese camera mode — essential for reading menus and signs',
        'Japan Official Travel App — connects you to WiFi hotspots at no cost',
        'Hyperdia or Navitime — for train route planning including shinkansen',
        'Suica (if you have an iPhone 8 or later, Apple Watch, or modern Android)',
      ]},
      { type: 'p', text: 'Japan rewards preparation and punishes assumption. Read a little before you go, download your apps, get your IC card at the airport — and then surrender to one of the most extraordinary travel experiences on earth.' },
    ],
  },

  {
    slug: 'best-beaches-india-2025',
    title: 'Best Beaches in India 2025: The Definitive Guide',
    excerpt: 'From the party beaches of North Goa to the secret sands of Andaman and the cliffside drama of Kerala\'s Varkala — India\'s best beaches ranked and reviewed.',
    date: '2025-04-28',
    readTime: 11,
    category: 'India',
    tags: ['India', 'Beaches', 'Goa', 'Kerala', 'Andaman'],
    coverPhoto: 'photo-1583244685026-d8519b977e5b',
    content: [
      { type: 'p', text: 'India has over 7,500 kilometres of coastline stretching from the mangrove creeks of Gujarat down to the tropical tip at Kanyakumari, and back up the eastern seaboard through Tamil Nadu, Andhra Pradesh, and Odisha. Within that coastline are some of the finest beaches in the world — many of them virtually unknown outside India.' },
      { type: 'p', text: 'Here is the definitive ranking of India\'s best beaches, divided by region, with honest assessments of crowd levels, cleanliness, and what each one is best for.' },
      { type: 'h2', text: 'Goa: India\'s Most Famous Coastline' },
      { type: 'p', text: 'Goa\'s beaches are so well-known they barely need introduction — but the differences between them are enormous and first-timers often end up at the wrong one.' },
      { type: 'h3', text: 'Palolem (South Goa) — Best Overall' },
      { type: 'p', text: 'The most beautiful beach in Goa by most measures. A horseshoe bay with calm, swimmable water bookended by rocky headlands and swaying coconut palms. Palolem has good budget accommodation (beach huts from ₹800/night), excellent seafood restaurants on the sand, and a relaxed nightlife scene (including silent disco nights). Gets busy in peak season (December-January) but rarely feels overwhelming.' },
      { type: 'h3', text: 'Agonda (South Goa) — Best for Peace and Quiet' },
      { type: 'p', text: 'A 30-minute drive from Palolem, Agonda is one of the last quiet beaches in Goa. Long, wide, and uncrowded, with almost no beach shacks. Agonda has a nesting Olive Ridley turtle population (protected, so certain sections close at night November-March). Accommodation options are limited; book ahead. The lack of shacks means you will need to walk a little to eat — worth it for the silence.' },
      { type: 'h3', text: 'Arambol (North Goa) — Best for Hippie Vibe' },
      { type: 'p', text: 'The last major beach before the Goa-Maharashtra border, Arambol has been a counter-culture hangout since the 1970s and still attracts long-stay travellers, yoga practitioners, and people who have decided to stay "just one more week" for the past three years. A sweet freshwater lagoon sits behind the main beach. Strong surf, interesting people, and the most affordable accommodation in Goa.' },
      { type: 'h3', text: 'Baga/Calangute (North Goa) — Skip It' },
      { type: 'p', text: 'Honestly: unless you specifically want the chaotic, commercial, package-holiday beach experience, avoid Baga and Calangute. They are heavily developed, loud, and the beach itself is overcrowded and not particularly clean. Nearby Candolim is marginally better but still firmly in tourist-zone territory.' },
      { type: 'h2', text: 'Kerala: Dramatic Beauty and Backwater Serenity' },
      { type: 'h3', text: 'Varkala — Best Cliff Beach in India' },
      { type: 'p', text: 'Varkala is dramatically different from Goa. Red laterite cliffs plunge down to the Arabian Sea, and a clifftop path is lined with budget guesthouses, yoga studios, and restaurants with sea views. The beach at the base of the cliff has strong surf and is not ideal for swimming, but the clifftop atmosphere at sunset is one of the finest travel experiences in south India. Best visited October-March.' },
      { type: 'h3', text: 'Marari — Best Low-Key Beach' },
      { type: 'p', text: 'Between Alleppey and Kochi, Marari is a quiet fishing village with a long, largely deserted beach. There is almost no tourist infrastructure — a handful of homestays and one luxury resort. The Marari Beach Resort is famous for its ayurvedic treatments and is a frequent entrant on "best beach hotels in India" lists. For budget travellers, the village homestays offer an authentic Kerala experience for ₹800-1,200/night.' },
      { type: 'h3', text: 'Kovalam — Best Developed Kerala Beach' },
      { type: 'p', text: 'Three adjoining crescent bays near Thiruvananthapuram. Lighthouse Beach is the most developed with a good row of restaurants and guesthouses. The lighthouse itself offers a panoramic view over the coast. Swimming is good in Lighthouse Beach; the water is calmer and more protected than Varkala. Not as beautiful as Varkala but more convenient for Ayurvedic resort visits and accessible facilities.' },
      { type: 'h2', text: 'Andaman Islands: India\'s Best Secret' },
      { type: 'p', text: 'The Andaman and Nicobar Islands are 1,300 kilometres off the eastern coast of mainland India but worth every rupee of the flight. The water clarity, the coral, and the white sand quality are on par with the Maldives at a fraction of the price.' },
      { type: 'h3', text: 'Radhanagar Beach, Havelock Island — Best Beach in India' },
      { type: 'p', text: 'Consistently voted the best beach in Asia by multiple publications, and for good reason. Three kilometres of powder-white sand fringed by forest, with turquoise water that is warm, calm, and crystal-clear. No beach shacks, no jet skis, no parasailing operators — just pure, protected shoreline. Reached by ferry from Port Blair. Snorkelling at nearby Elephant Beach is excellent.' },
      { type: 'h3', text: 'Neil Island — Best for Coral' },
      { type: 'p', text: 'Smaller and quieter than Havelock, Neil Island has three beaches each with a different character. Bharatpur Beach has excellent snorkelling right off the shore. Laxmanpur Beach has a dramatic natural rock arch visible at low tide. The island takes about four hours to explore by bicycle (₹100/day rental). Fewer tourists than Havelock, simpler accommodation, and genuinely pristine reefs.' },
      { type: 'h2', text: 'Karnataka: Gokarna and Beyond' },
      { type: 'h3', text: 'Om Beach, Gokarna — Best Budget Alternative to Goa' },
      { type: 'p', text: 'Gokarna is a temple town on the Karnataka coast that also happens to have some beautiful beaches accessible by trail or boat. Om Beach gets its name from its Om-symbol shape when viewed from above. Half Moon Beach and Paradise Beach require a longer walk or boat ride but reward you with near-total solitude. Accommodation is basic and cheap (₹400-800/night for huts). A serious alternative to Goa for travellers who want beaches without the party scene.' },
      { type: 'h2', text: 'Quick Rankings for Different Types of Travellers' },
      { type: 'table', headers: ['Best For', 'Top Pick', 'Runner Up'], rows: [
        ['Overall beauty', 'Radhanagar Beach, Andaman', 'Palolem, Goa'],
        ['Budget traveller', 'Arambol, Goa', 'Om Beach, Gokarna'],
        ['Families', 'Marari, Kerala', 'Kovalam, Kerala'],
        ['Snorkelling / diving', 'Neil Island, Andaman', 'Pondicherry (Auroville Beach)'],
        ['Nightlife', 'Baga / Anjuna, Goa', 'Palolem (silent disco)'],
        ['Couples / romance', 'Varkala, Kerala', 'Agonda, Goa'],
        ['Solitude', 'Paradise Beach, Gokarna', 'Agonda, Goa'],
      ]},
      { type: 'h2', text: 'When to Go: Beach Season in India' },
      { type: 'ul', items: [
        'Goa: October to March is peak season; April-September is monsoon (seas are rough, many shacks close)',
        'Kerala: October to February; March onwards gets humid; June-September is monsoon',
        'Andaman: October to May; avoid June-September (rough seas, ferry services reduced)',
        'Karnataka / Gokarna: October to March is best; Gokarna has a local following in May before monsoon',
      ]},
      { type: 'p', text: 'India\'s beaches are as varied as the country itself. The Andaman Islands offer world-class snorkelling. Goa offers sun-soaked hedonism. Kerala offers peace and Ayurvedic retreats. Gokarna offers temple-beach serenity. Whatever kind of beach holiday you are after, India has a version of it — and the best ones are often the least obvious.' },
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return allPosts.find(p => p.slug === slug);
}

export function getRelatedPosts(post: BlogPost, count = 3): BlogPost[] {
  return allPosts
    .filter(p => p.slug !== post.slug && (p.category === post.category || p.tags.some(t => post.tags.includes(t))))
    .slice(0, count);
}
