import { City } from "./types";

export const cities: City[] = [
  {
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    flag: "🇮🇩",
    tagline: "Island of the Gods",
    description: "Bali is where ancient temples meet emerald rice terraces, sacred ceremonies fill the air with incense, and world-class surf breaks draw adventurers from every corner of the globe.",
    heroDescription: "A timeless island where spirituality, nature, and culture converge in perfect harmony. Every sunrise paints the volcanoes gold, every sunset drowns the horizon in amber.",
    stats: {
      bestTime: "Apr – Oct",
      budget: "$40–$200/day",
      language: "Balinese, Indonesian",
      currency: "IDR (Rupiah)",
    },
    vibes: ["Spiritual", "Romantic", "Adventure"],
    gradient: "from-orange-600 via-amber-500 to-yellow-400",
    accentColor: "#FF6B35",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=85",
    thingsToDo: [
      {
        name: "Tanah Lot Temple",
        description: "Watch the sun melt into the Indian Ocean behind this iconic sea temple perched on a dramatic rock formation. Arrive 90 minutes before sunset for the golden hour magic.",
        icon: "🛕",
        duration: "2–3 hours",
        category: "Cultural",
      },
      {
        name: "Tegallalang Rice Terraces",
        description: "Walk through centuries-old subak irrigation systems carved into the hillsides above Ubud. The terraced emerald fields are a UNESCO World Heritage landscape.",
        icon: "🌾",
        duration: "2–4 hours",
        category: "Nature",
      },
      {
        name: "Ubud Monkey Forest",
        description: "A sacred nature reserve home to over 700 long-tailed macaques. Three ancient Hindu temples are nestled among giant banyan trees in this mystical sanctuary.",
        icon: "🐒",
        duration: "1–2 hours",
        category: "Nature",
      },
      {
        name: "Mount Batur Sunrise Trek",
        description: "Begin your ascent at 2am to reach the volcano's summit by dawn. The reward: watching sunrise paint the caldera in hues of rose and amber with Lombok visible on clear days.",
        icon: "🌋",
        duration: "Full day",
        category: "Adventure",
      },
      {
        name: "Seminyak Beach",
        description: "Bali's most stylish stretch of sand with world-class beach clubs, acclaimed restaurants, and consistent surf breaks. The sunset here is a daily communal ritual.",
        icon: "🌊",
        duration: "Half day",
        category: "Relaxation",
      },
      {
        name: "Tirta Empul Temple",
        description: "Participate in a purification ritual at this 1,000-year-old spring temple. Bathe in the sacred waters emerging from 30 fountains as Balinese worshippers do daily.",
        icon: "💧",
        duration: "1–2 hours",
        category: "Cultural",
      },
      {
        name: "Kuta Surf Lessons",
        description: "Bali's most famous surf beach has perfect beginner waves and hundreds of surf schools. Most visitors are standing up on their boards within their first hour.",
        icon: "🏄",
        duration: "2–3 hours",
        category: "Adventure",
      },
      {
        name: "Sacred Monkey Forest Sanctuary",
        description: "Explore ancient temples and walk through a lush forest reserve teeming with Balinese long-tailed monkeys in the heart of Ubud.",
        icon: "🌿",
        duration: "1–2 hours",
        category: "Nature",
      },
      {
        name: "Cooking Class in Ubud",
        description: "Visit a local market at dawn, then learn to prepare Balinese classics: nasi goreng, satay, tempeh, and fresh coconut desserts with master home cooks.",
        icon: "🍜",
        duration: "4–5 hours",
        category: "Culinary",
      },
      {
        name: "Traditional Kecak Fire Dance",
        description: "Watch the hypnotic Kecak ceremony at Uluwatu cliff-top temple as the sun dips below the horizon. A hundred bare-chested men chanting 'kecak' create an unforgettable trance.",
        icon: "🔥",
        duration: "1.5 hours",
        category: "Cultural",
      },
    ],
    hotels: [
      {
        name: "Alila Ubud",
        description: "Perched on the edge of a river gorge valley, this award-winning jungle retreat offers infinity pools floating above the treetops, private villas, and impeccable Balinese hospitality.",
        priceRange: "$350–$650/night",
        type: "Luxury Jungle Resort",
        highlight: "Infinity pool overlooking the valley",
      },
      {
        name: "Potato Head Suites",
        description: "The hippest stay in Seminyak. A collection of designer suites and studios adjacent to Potato Head Beach Club, blending Indonesian craft with contemporary cool.",
        priceRange: "$180–$320/night",
        type: "Boutique Beach Hotel",
        highlight: "Direct access to iconic beach club",
      },
      {
        name: "Bisma Eight",
        description: "A boutique haven in the heart of Ubud's creative district, offering stunning jungle-view infinity pools, organic farm-to-table dining, and thoughtfully designed suites.",
        priceRange: "$120–$250/night",
        type: "Boutique Eco-Hotel",
        highlight: "Three-tiered infinity pool with jungle views",
      },
    ],
    restaurants: [
      {
        name: "Locavore",
        description: "Bali's most celebrated fine dining restaurant using only locally-sourced ingredients from Balinese farms. The tasting menu is a journey through the island's flavors.",
        cuisine: "Modern Indonesian Fine Dining",
        priceRange: "$80–$120/person",
        mustTry: "Signature tasting menu with wine pairing",
      },
      {
        name: "Naughty Nuri's",
        description: "A Ubud institution famous for its fall-off-the-bone pork ribs, potent cocktails, and the kind of laid-back atmosphere that makes hours disappear happily.",
        cuisine: "BBQ & Indonesian",
        priceRange: "$15–$30/person",
        mustTry: "Baby back ribs and dirty martini",
      },
      {
        name: "Sarong",
        description: "A candlelit open-air pavilion in Seminyak serving contemporary Asian cuisine with an enormous cocktail list. The atmosphere is pure Bali magic at golden hour.",
        cuisine: "Pan-Asian Contemporary",
        priceRange: "$40–$70/person",
        mustTry: "Duck confit with Balinese spices",
      },
    ],
    gettingAround: [
      "Rent a scooter for maximum freedom — most roads are navigable with basic riding skills ($5–8/day)",
      "Gojek and Grab apps offer cheap, reliable rides and food delivery across the island",
      "Hire a private driver for day trips — around $40–60 for a full day, often including a custom itinerary",
      "Blue Bird taxis are metered and trustworthy for airport transfers",
      "Many areas in Seminyak and Canggu are walkable; Ubud's center is best explored on foot",
    ],
    proTips: [
      "Buy sarongs at local markets for $2-3 — they're required at temple entrances and make great souvenirs",
      "Always carry small bills (Rp 10,000–50,000) for warungs, offerings, and parking attendants",
      "The traffic between Kuta and Ubud (40km) can take 3+ hours during peak hours — plan accordingly",
      "Respect temple ceremonies: dress modestly, don't point feet at shrines, don't enter if menstruating",
      "Book popular restaurants like Locavore 4–6 weeks in advance — they sell out fast",
      "Visit rice terraces early morning (7–9am) before the tour groups arrive for serene, crowd-free shots",
      "The shoulder season (Apr–May, Sep–Oct) offers perfect weather with fewer crowds and lower prices",
    ],
    offbeatPlaces: [
      {
        name: "Tukad Cepung Waterfall",
        description: "A cathedral-like waterfall hidden inside a narrow canyon where sunlight pierces through a crack in the rock above and illuminates the mist in golden beams. One of Bali's most magical sights that most visitors completely miss.",
        why: "Only a 45-minute drive from Ubud but sees a fraction of the crowds. The approach involves wading through a shallow river — which keeps the casual tourists away.",
        icon: "🌊",
        type: "Hidden Nature",
        tip: "Arrive before 9am for the sunbeam effect. Wear shorts you don't mind getting wet for the river crossing.",
      },
      {
        name: "Sidemen Valley",
        description: "A breathtaking valley of emerald rice terraces, rushing rivers, and traditional Balinese villages that hasn't been touched by the Seminyak party scene. Mount Agung looms dramatically on clear mornings.",
        why: "While Tegallalang gets 3,000 tourists a day, Sidemen sees 30. The landscapes are arguably more beautiful and the villages are genuinely traditional.",
        icon: "🏔️",
        type: "Off the Beaten Path",
        tip: "Stay at least one night in a local homestay to see dawn over the valley. Jeramban village is the best base.",
      },
      {
        name: "Amed Fishing Villages",
        description: "A string of quiet fishing villages on Bali's northeast coast with volcanic black-sand beaches, world-class snorkelling over the USS Liberty wreck, and some of the freshest seafood on the island.",
        why: "The drive from Ubud takes 2.5 hours, which deters day-trippers. You get an entirely different Bali — local, unhurried, genuinely beautiful.",
        icon: "🐠",
        type: "Hidden Coastal Gem",
        tip: "Book a room right on the beach — many warung guesthouses have loungers over the water for under $30/night.",
      },
      {
        name: "Pura Lempuyang 'Gates of Heaven'",
        description: "The famous split gate (Candi Bentar) framing Mount Agung at sunrise is actually one of seven temples on a sacred mountain ridge. Most visitors only see the gate — the full pilgrimage trail through jungle to the summit is extraordinary.",
        why: "The famous photo spot is packed. But walk the full trail through all seven temples and you'll have the ancient jungle path almost entirely to yourself.",
        icon: "⛩️",
        type: "Spiritual Secret",
        tip: "Start the full trail by 5:30am. Bring offerings, wear a sarong, and hire a local guide at the base for $10.",
      },
      {
        name: "Penglipuran Traditional Village",
        description: "One of Bali's best-preserved traditional villages where every home is identical, bamboo forests line the main street, and life follows ancient Balinese custom. Spotlessly maintained and genuinely inhabited — not a museum.",
        why: "Only 45 minutes from Ubud, entry is just $2, and it's usually quiet in the morning. The bamboo forest behind the village is free and surreal.",
        icon: "🎋",
        type: "Cultural Hidden Gem",
        tip: "Visit on a Balinese ceremony day (check local calendar) to see the village decorated with elaborate offerings.",
      },
    ],
  },
  {
    slug: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    flag: "🇹🇭",
    tagline: "City of Angels",
    description: "Bangkok is a city of dazzling contradictions — gilded temples rising above neon-lit street markets, serene monks navigating chaotic traffic, and world-class cuisine available for $1 on any corner.",
    heroDescription: "Asia's most electrifying metropolis pulses with ancient grandeur and hypermodern ambition. Every sense is assaulted in the best possible way.",
    stats: {
      bestTime: "Nov – Mar",
      budget: "$30–$120/day",
      language: "Thai",
      currency: "THB (Baht)",
    },
    vibes: ["Cultural", "Foodie", "Adventure"],
    gradient: "from-rose-600 via-pink-500 to-orange-400",
    accentColor: "#FF4785",
    image: "https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=1600&q=85",
    thingsToDo: [
      {
        name: "Grand Palace & Wat Phra Kaew",
        description: "The spiritual heart of Thailand. The Emerald Buddha temple within these golden walls is the most sacred site in the country — every Thai king visits to change its golden robes seasonally.",
        icon: "👑",
        duration: "3–4 hours",
        category: "Cultural",
      },
      {
        name: "Chatuchak Weekend Market",
        description: "The world's largest weekend market with 15,000 stalls spread across 35 acres. Antiques, street food, handmade clothing, vintage goods, and pets — all under corrugated tin roofs.",
        icon: "🛍️",
        duration: "Half day",
        category: "Shopping",
      },
      {
        name: "Chao Phraya River at Dusk",
        description: "Take a longtail boat through canal networks or a sunset dinner cruise along the river that Bangkok was built around. The skyline reflected in the water is extraordinary.",
        icon: "🚤",
        duration: "2–3 hours",
        category: "Scenic",
      },
      {
        name: "Street Food Tour – Yaowarat",
        description: "Bangkok's Chinatown transforms at night into a heaving street food paradise. Roast duck, crab fried rice, and Thai-Chinese desserts you won't find anywhere else on earth.",
        icon: "🦀",
        duration: "3–4 hours",
        category: "Culinary",
      },
      {
        name: "Muay Thai at Rajadamnern Stadium",
        description: "The world's most famous Muay Thai arena hosts electrifying bouts several nights a week. The atmosphere with wildly betting Thai crowds is unlike any sporting event anywhere.",
        icon: "🥊",
        duration: "3 hours",
        category: "Entertainment",
      },
    ],
    hotels: [
      {
        name: "Capella Bangkok",
        description: "Set on the Chao Phraya riverfront, this ultra-luxury retreat features two-story villas with private pools and butler service. Arguably the finest hotel in Southeast Asia.",
        priceRange: "$600–$2,000/night",
        type: "Ultra-Luxury River Resort",
        highlight: "Private riverside pool villas",
      },
      {
        name: "The Standard Bangkok",
        description: "The hip hotel brand's Bangkok outpost in Mahanakhon Tower. Rooftop bar, dramatic city views, and a design-forward aesthetic that attracts Bangkok's creative crowd.",
        priceRange: "$200–$400/night",
        type: "Design Hotel",
        highlight: "Rooftop sky deck with 360° views",
      },
      {
        name: "Ibis Styles Bangkok Sukhumvit 50",
        description: "A well-located, cheerful hotel in the heart of the Sukhumvit nightlife corridor. Excellent value, consistent quality, and easy BTS access.",
        priceRange: "$50–$90/night",
        type: "Mid-Range City Hotel",
        highlight: "Walking distance to BTS Skytrain",
      },
    ],
    restaurants: [
      {
        name: "Le Du",
        description: "The restaurant that put Bangkok on the global fine dining map. Chef Thitid Tassanakajohn's seasonal Thai tasting menus use only local Thai ingredients interpreted with French technique.",
        cuisine: "Progressive Thai Fine Dining",
        priceRange: "$80–$130/person",
        mustTry: "Seasonal tasting menu",
      },
      {
        name: "Jay Fai",
        description: "A Michelin-starred street food stall run by an 80-year-old woman in skiing goggles and a woolly hat. The crab omelette alone is worth flying to Bangkok for.",
        cuisine: "Thai Street Food",
        priceRange: "$20–$50/person",
        mustTry: "Drunken noodles and crab omelette",
      },
      {
        name: "Supanniga Eating Room",
        description: "Chef Supaksorn 'Woody' Jongsiri's celebration of Trat Province cuisine — a regional Thai cooking tradition largely unknown outside Thailand.",
        cuisine: "Regional Thai",
        priceRange: "$15–$30/person",
        mustTry: "Crab fat curry with coconut milk",
      },
    ],
    gettingAround: [
      "BTS Skytrain is the fastest way across the city — buy a Rabbit Card for seamless travel",
      "MRT subway connects additional areas including Chinatown (Yaowarat station)",
      "Grab app is essential — metered taxis often refuse to use meters with tourists",
      "Tuk-tuks are fun for short distances but agree on price before boarding",
      "Boat taxis along Chao Phraya and Khlong Saen Saep canals beat surface traffic",
    ],
    proTips: [
      "Temple dress code is strict — cover shoulders and knees or buy a sarong at the entrance",
      "Always carry cash — many markets, street stalls, and temples are cash-only",
      "Avoid tuk-tuk drivers who offer 'free' city tours — they'll take you to commission-paying gem shops",
      "The best street food is often at markets that close by 10pm — eat early",
      "Heat and humidity are intense — plan outdoor activities before 11am or after 4pm",
    ],
    offbeatPlaces: [
      {
        name: "Bang Krachao — Bangkok's Green Lung",
        description: "A car-free island jungle in the middle of the Chao Phraya river, accessible only by ferry. Cycle through mangroves, visit a floating market, and eat at riverside shacks with zero tourists in sight.",
        why: "Five minutes by ferry from central Bangkok but feels like a different planet. Almost no foreign tourists have discovered it yet.",
        icon: "🌿",
        type: "Urban Escape",
        tip: "Rent a bicycle at the ferry pier (฿50/hour), arrive on weekends when the market is open, and bring mosquito repellent.",
      },
      {
        name: "Talat Noi Neighbourhood",
        description: "Bangkok's oldest Chinese neighbourhood, a labyrinth of shrines, family businesses, and street art tucked between Chinatown and the river. Iron workshops sit next to century-old temples and hip coffee shops.",
        why: "Just one street from the tourist hordes of Yaowarat but feels like a secret world. The street art installations are genuinely world-class.",
        icon: "🎨",
        type: "Local Neighbourhood",
        tip: "Start at Tha Rua Hang Yao pier and walk inward. The Lhong 1919 heritage wharf complex nearby is also worth the detour.",
      },
      {
        name: "Khlong Bang Luang Floating Art House",
        description: "A 200-year-old wooden mansion on a canal in Thonburi that a local artist converted into a floating gallery. Classical Thai puppet shows perform on weekends inside this hidden canal neighbourhood.",
        why: "Zero mainstream tourist presence. The canal boat ride to get there is itself a glimpse into old Bangkok life that barely exists anymore.",
        icon: "🎭",
        type: "Hidden Cultural Gem",
        tip: "Take the express boat to Tha Chang pier, then a long-tail boat through the klongs. Visit Saturday or Sunday for puppet performances.",
      },
      {
        name: "Phra Nakhon District at Dawn",
        description: "Bangkok's old royal district comes alive at 5am when monks collect alms, vendors set up orchid stalls, and the temples glow in morning gold before the tourist buses arrive.",
        why: "The Grand Palace area is unrecognisable without crowds. Walking these streets at dawn feels like time travel.",
        icon: "🌅",
        type: "Early Morning Secret",
        tip: "Stay in a Rattanakosin area guesthouse so you can wake up at 5am and walk — no transport needed.",
      },
    ],
  },
  {
    slug: "paris",
    name: "Paris",
    country: "France",
    flag: "🇫🇷",
    tagline: "City of Light",
    description: "Paris is where Haussmann boulevards frame the Eiffel Tower at dusk, where every corner café serves a perfect crème brûlée, and where centuries of art and fashion have created the world's most romantic city.",
    heroDescription: "The city that invented the art of living well. Every arrondissement holds a lifetime of discovery — from the Louvre's labyrinth to hidden passages and rooftop gardens.",
    stats: {
      bestTime: "Apr – Jun, Sep – Oct",
      budget: "$100–$400/day",
      language: "French",
      currency: "EUR (Euro)",
    },
    vibes: ["Romantic", "Cultural", "Luxury"],
    gradient: "from-purple-600 via-blue-500 to-indigo-400",
    accentColor: "#8B5CF6",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=85",
    thingsToDo: [
      {
        name: "Eiffel Tower at Sunset",
        description: "Book tickets online (essential) for the second or third floor platform for the best city views. Return after dark to watch the tower's hourly light show sparkle across the Seine.",
        icon: "🗼",
        duration: "2–3 hours",
        category: "Iconic",
      },
      {
        name: "The Louvre",
        description: "The world's largest art museum contains 380,000 works. Focus on the Richelieu Wing (French paintings) and Denon Wing (Italian sculpture). The Mona Lisa room is always crowded.",
        icon: "🎨",
        duration: "Half day",
        category: "Cultural",
      },
      {
        name: "Le Marais Walking Tour",
        description: "Paris's most fashionable district blends medieval streets, Jewish delis, gay bars, art galleries, and the grand Place des Vosges. Explore on foot — every alley reveals something extraordinary.",
        icon: "🚶",
        duration: "3–4 hours",
        category: "Walking",
      },
      {
        name: "Versailles Day Trip",
        description: "The Sun King's incomprehensible palace complex is just 45 minutes from Paris. The Hall of Mirrors, royal apartments, and 800-hectare gardens demand a full day of exploration.",
        icon: "🏰",
        duration: "Full day",
        category: "Day Trip",
      },
      {
        name: "Montmartre & Sacré-Cœur",
        description: "Climb through bohemian streets to the hilltop basilica that overlooks all of Paris. Artists, street musicians, and the best city panorama in the French capital await.",
        icon: "⛪",
        duration: "Half day",
        category: "Cultural",
      },
    ],
    hotels: [
      {
        name: "Hôtel Plaza Athénée",
        description: "The most iconic address on Avenue Montaigne, facing the Eiffel Tower from the other side of the Seine. Home to Alain Ducasse's legendary restaurant and incomparable old-world elegance.",
        priceRange: "$800–$2,500/night",
        type: "Palace Hotel",
        highlight: "Eiffel Tower-facing suites on the avenue",
      },
      {
        name: "Le Pigalle",
        description: "A chic boutique hotel in the revived 9th arrondissement. Local art, a wine bar, eclectic design, and a neighborhood that feels like discovering Paris's best-kept secret.",
        priceRange: "$180–$350/night",
        type: "Boutique Design Hotel",
        highlight: "Wine bar with curated natural wines",
      },
      {
        name: "Generator Paris",
        description: "A design-forward hostel in the 10th arrondissement with private rooms, a rooftop terrace bar, and an artsy crowd. The best value stay in Paris that still feels special.",
        priceRange: "$50–$120/night",
        type: "Boutique Hostel",
        highlight: "Rooftop terrace with Canal Saint-Martin views",
      },
    ],
    restaurants: [
      {
        name: "Septime",
        description: "The hardest reservation in Paris, consistently ranked among Europe's best restaurants. Bertrand Grébaut's market-driven tasting menus define modern French bistronomie.",
        cuisine: "Modern French Bistronomie",
        priceRange: "$120–$180/person",
        mustTry: "Seasonal vegetable tasting menu",
      },
      {
        name: "L'As du Fallafel",
        description: "The legendary falafel stand in the Marais that draws queues stretching around the block at lunch. A Paris institution for 30+ years with zero compromise on quality.",
        cuisine: "Israeli / Middle Eastern",
        priceRange: "$8–$15/person",
        mustTry: "Special falafel sandwich with all toppings",
      },
      {
        name: "Frenchie Wine Bar",
        description: "The casual sibling of the acclaimed Frenchie restaurant. Order sharing plates from a seasonal menu alongside natural wines from small French producers — no reservation needed.",
        cuisine: "Contemporary French Wine Bar",
        priceRange: "$40–$70/person",
        mustTry: "Charcuterie board and natural wine flight",
      },
    ],
    gettingAround: [
      "Metro is cheap, fast, and comprehensive — buy a Navigo Semaine (weekly pass) for unlimited travel",
      "Walk wherever possible — Paris's best discoveries happen between destinations",
      "Vélib' bike-share is perfect for flat areas like along the Seine and through the Marais",
      "RER trains connect the airport, Versailles, and Disneyland to central Paris",
      "Taxis and Uber are expensive but reliable late at night when Metro stops running at 1:15am",
    ],
    proTips: [
      "Book museum tickets online — skip the queues, which can be 2+ hours for the Louvre",
      "Pharmacies (marked with a green cross) are excellent for cheap skincare and medicine",
      "Most shops and restaurants are closed on Sundays — plan accordingly",
      "Learning a few words of French goes a very long way in terms of service and warmth",
      "The best baguette is from Paul Pâtisserie, Maison Landemaine, or your nearest neighborhood boulangerie",
    ],
    offbeatPlaces: [
      {
        name: "Promenade Plantée",
        description: "The world's first elevated park, built on a disused 19th-century railway viaduct before New York's High Line existed. A 4.5km linear garden floating above Paris's 12th arrondissement, lined with rose gardens and art studios below.",
        why: "Virtually unknown to tourists despite being one of the most beautiful walks in Paris. The arches below (the Viaduc des Arts) house artisan workshops open to visitors.",
        icon: "🌹",
        type: "Hidden Green Space",
        tip: "Enter at Avenue Daumesnil near Bastille. Walk the full length east to Bois de Vincennes for a rare green half-day in the city.",
      },
      {
        name: "Château de Vincennes",
        description: "A perfectly preserved medieval fortress with a 52-metre keep just 15 minutes from central Paris on the Metro. Kings of France lived here before Versailles was built — and almost nobody visits it.",
        why: "Versailles gets 15 million visitors a year. Vincennes gets 150,000. It's larger, older, and in many ways more impressive. Entry costs €11.",
        icon: "🏰",
        type: "Overlooked Monument",
        tip: "Combine with a walk through the Bois de Vincennes — Paris's largest park at 995 hectares, with lakes and a proper forest.",
      },
      {
        name: "Musée de la Chasse et de la Nature",
        description: "A private museum in a 17th-century mansion in the Marais dedicated to hunting and nature — but reimagined as a surrealist cabinet of curiosities. Taxidermy meets contemporary art in the most unexpected way.",
        why: "One of the quirkiest, most beautifully designed spaces in Paris. Always uncrowded because the name sounds niche. It is not — it's extraordinary.",
        icon: "🦊",
        type: "Quirky Museum",
        tip: "Free on the first Sunday of each month. Budget at least 90 minutes — every room rewards close attention.",
      },
      {
        name: "Buttes-Chaumont Park",
        description: "A dramatic 19th-century park in the 19th arrondissement with a 50-metre cliff island, a suspension bridge, and panoramic views over Paris — where Parisians actually spend their Sundays.",
        why: "Every tourist goes to Luxembourg Gardens. Parisians go to Buttes-Chaumont. It's twice as large, far more dramatic, and has almost no foreign tourists.",
        icon: "🌲",
        type: "Local's Park",
        tip: "Bring a bottle of wine and a baguette. The Rosa Bonheur guinguette bar on the lake is open on weekends in summer.",
      },
    ],
  },
  {
    slug: "tokyo",
    name: "Tokyo",
    country: "Japan",
    flag: "🇯🇵",
    tagline: "Future in Tradition",
    description: "Tokyo is where ancient Shinto shrines stand in the shadow of neon skyscrapers, where a bowl of ramen can be Michelin-starred, and where the world's most efficient city somehow feels perfectly human.",
    heroDescription: "The city that proves the future and the past can share the same street. Fourteen million people, infinite neighborhoods, and a level of craft that elevates everything from convenience store food to garden design.",
    stats: {
      bestTime: "Mar – May, Oct – Nov",
      budget: "$80–$250/day",
      language: "Japanese",
      currency: "JPY (Yen)",
    },
    vibes: ["Cultural", "Foodie", "Adventure"],
    gradient: "from-red-600 via-rose-500 to-pink-400",
    accentColor: "#EF4444",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1600&q=85",
    thingsToDo: [
      {
        name: "Shibuya Crossing",
        description: "The world's busiest pedestrian intersection handles up to 3,000 people per crossing cycle. Watch from the Shibuya Sky observation deck or the Mag's Park cafe for the ultimate overhead view.",
        icon: "🚦",
        duration: "1 hour",
        category: "Iconic",
      },
      {
        name: "Tsukiji Outer Market",
        description: "The fish market may have moved to Toyosu, but the surrounding outer market remains the best place in Japan for fresh sushi, tamagoyaki, and Japanese street food at 7am.",
        icon: "🐟",
        duration: "2–3 hours",
        category: "Culinary",
      },
      {
        name: "Meiji Jingu Shrine",
        description: "A forested Shinto shrine dedicated to Emperor Meiji at the heart of Harajuku. The towering cypress torii gates and gravel paths create a transcendent escape from the city.",
        icon: "⛩️",
        duration: "1–2 hours",
        category: "Cultural",
      },
      {
        name: "TeamLab Borderless",
        description: "A cathedral of light and movement where interactive digital art installations respond to your presence. One of the most mesmerizing art experiences anywhere in the world.",
        icon: "✨",
        duration: "3–4 hours",
        category: "Art & Culture",
      },
      {
        name: "Arashiyama Bamboo Grove",
        description: "Visit at dawn when the light filters impossibly between towering bamboo stalks and the forest sounds like a natural symphony. One of Japan's most otherworldly landscapes.",
        icon: "🎋",
        duration: "Half day",
        category: "Nature",
      },
    ],
    hotels: [
      {
        name: "Aman Tokyo",
        description: "Japan filtered through the Aman ethos. Occupying six floors of the Otemachi Tower above the Imperial Palace East Gardens, this is hospitality refined to its purest form.",
        priceRange: "$1,000–$3,000/night",
        type: "Ultra-Luxury City Hotel",
        highlight: "Sweeping Imperial Palace garden views",
      },
      {
        name: "Trunk Hotel",
        description: "A social-conscious design hotel in Shibuya with locally-sourced materials, a rooftop bar, and the ethos that hospitality should benefit the surrounding community.",
        priceRange: "$200–$400/night",
        type: "Boutique Design Hotel",
        highlight: "Rooftop bar with Shibuya views",
      },
      {
        name: "The Millennials Shibuya",
        description: "Tokyo's most innovative pod hotel — private sleeping pods with smart controls, a co-working lobby, and an excellent location for half the price of a traditional room.",
        priceRange: "$60–$100/night",
        type: "Smart Capsule Hotel",
        highlight: "Fully automated pod experience",
      },
    ],
    restaurants: [
      {
        name: "Sukiyabashi Jiro",
        description: "The subject of Jiro Dreams of Sushi. Obtaining a reservation is nearly impossible for non-Japanese guests, but the satellite location in Roppongi Hills is more accessible.",
        cuisine: "Omakase Sushi",
        priceRange: "$300–$400/person",
        mustTry: "The complete omakase experience",
      },
      {
        name: "Ichiran Ramen",
        description: "A solo dining chain where each customer sits in an individual booth to focus entirely on their bowl of tonkotsu ramen. The ritual of ordering via paper form is deeply satisfying.",
        cuisine: "Tonkotsu Ramen",
        priceRange: "$10–$15/person",
        mustTry: "Tonkotsu ramen with all toppings",
      },
      {
        name: "Sushi Yoshitake",
        description: "One of Tokyo's three-Michelin-starred sushi counters where chef Yoshitake's extraordinary skill meets the finest seasonal fish. Book months ahead for a transcendent meal.",
        cuisine: "Michelin 3-Star Sushi Omakase",
        priceRange: "$200–$300/person",
        mustTry: "Seasonal omakase",
      },
    ],
    gettingAround: [
      "The JR and Tokyo Metro systems cover virtually everywhere — buy a Suica or Pasmo IC card",
      "Tokyo Subway 24/48/72-hour passes offer unlimited rides and are excellent value for tourists",
      "Taxis are very expensive but safe — the door opens automatically when the driver stops",
      "Rent a bicycle in neighborhoods like Yanaka or Shimokitazawa for a perfect local experience",
      "Google Maps works flawlessly in Tokyo and even recommends train platforms and car numbers",
    ],
    proTips: [
      "7-Eleven and FamilyMart convenience stores serve genuinely excellent food — never skip them",
      "Carry cash at all times — many restaurants and shrines don't accept cards",
      "Download the Google Translate camera feature to read Japanese menus instantly",
      "Cherry blossom (late March–early April) is spectacular but accommodation prices triple",
      "Shoes that slip on and off are essential — many traditional restaurants require removing shoes",
    ],
    offbeatPlaces: [
      {
        name: "Yanaka — Old Tokyo Frozen in Time",
        description: "A neighbourhood that survived WWII bombing and the bubble economy's redevelopment. Wooden temples, family craft shops, cats sunbathing in cemetery alleys, and a shotengai (shopping street) unchanged since the 1950s.",
        why: "Every guidebook mentions Shibuya and Asakusa. Almost none mention Yanaka — where Tokyo's soul actually lives, unchanged and unhurried.",
        icon: "🏮",
        type: "Historic Neighbourhood",
        tip: "Get off at Nippori station, walk to Yanaka Cemetery (hauntingly beautiful, not morbid), then explore the Yanaka Ginza shotengai for street food.",
      },
      {
        name: "Nezu Shrine",
        description: "A 1,900-year-old Shinto shrine in the Bunkyo district with hundreds of small torii gates lining a hillside garden — the same visual as Fushimi Inari in Kyoto, but in central Tokyo with a fraction of visitors.",
        why: "Fushimi Inari gets 2.5 million visitors a year. Nezu gets 200,000. The atmosphere is more intimate, the garden is more beautiful, and it's free.",
        icon: "⛩️",
        type: "Hidden Shrine",
        tip: "Visit during azalea season (April–May) when the garden blooms in pink and purple around the torii tunnels.",
      },
      {
        name: "Shimokitazawa",
        description: "Tokyo's bohemian village — a maze of narrow lanes packed with vintage clothing shops, indie music venues, craft beer bars, and tiny theatres. The antithesis of everything glossy about modern Tokyo.",
        why: "The creative class of Tokyo calls this home. No chains, no tourists, just record shops, second-hand bookstores, and the city's best live music scene.",
        icon: "🎸",
        type: "Bohemian Quarter",
        tip: "Come on a Sunday afternoon when the markets are out. Stay for evening live music at Garage, Shelter, or 251.",
      },
      {
        name: "Kagurazaka",
        description: "A Franco-Japanese neighbourhood on a hill in central Tokyo with French bakeries beside traditional ryotei restaurants, hidden geisha alleys (yokocho), and a French school that gives it a uniquely European atmosphere.",
        why: "One of Tokyo's great neighbourhood secrets. The hidden alley behind the main street (Kagurazaka Dori) is genuinely magical at night.",
        icon: "🥐",
        type: "Hidden Neighbourhood",
        tip: "Find the narrow lantern-lit alley off Kagurazaka Dori — it's unmarked and leads to some of Tokyo's best hidden restaurants.",
      },
    ],
  },
  {
    slug: "dubai",
    name: "Dubai",
    country: "UAE",
    flag: "🇦🇪",
    tagline: "Where the Future Lives",
    description: "Dubai is a city built on audacity — the world's tallest building, the world's largest mall, man-made islands visible from space, and a skyline that didn't exist 40 years ago.",
    heroDescription: "Excess, ambition, and Arabic hospitality combine in the world's most dramatic city. The desert backdrop makes every architectural achievement look even more impossible.",
    stats: {
      bestTime: "Nov – Mar",
      budget: "$100–$500/day",
      language: "Arabic, English",
      currency: "AED (Dirham)",
    },
    vibes: ["Luxury", "Adventure", "Spectacle"],
    gradient: "from-amber-500 via-yellow-400 to-orange-300",
    accentColor: "#F59E0B",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=85",
    thingsToDo: [
      {
        name: "Burj Khalifa At the Top",
        description: "The 124th or 148th floor observation decks offer panoramic views of the city, desert, and Gulf. Book the sunset slot for the transformation from golden hour to a twinkling sea of lights.",
        icon: "🏙️",
        duration: "2–3 hours",
        category: "Iconic",
      },
      {
        name: "Desert Safari",
        description: "Dune bashing, camel rides, sandboarding, and a Bedouin camp dinner under the stars. The dramatic red dunes of the Dubai Desert Conservation Reserve are unforgettable.",
        icon: "🐪",
        duration: "6–8 hours",
        category: "Adventure",
      },
      {
        name: "Dubai Creek & Gold Souk",
        description: "Cross the historic creek on an abra (wooden boat) and explore the gold and spice souks of old Dubai. A world away from the gleaming towers across the water.",
        icon: "⚓",
        duration: "3–4 hours",
        category: "Cultural",
      },
      {
        name: "Palm Jumeirah",
        description: "Take the monorail across the world's largest man-made island. Visit the Atlantis waterpark, walk The Pointe, or stay overnight at the Seven Pines or Atlantis resort.",
        icon: "🌴",
        duration: "Half day",
        category: "Scenic",
      },
      {
        name: "Dubai Frame",
        description: "A 150m picture frame structure straddling old and new Dubai. The glass floor bridge between two towers and the historic vs. modern city view from each side is genuinely clever.",
        icon: "🖼️",
        duration: "1–2 hours",
        category: "Iconic",
      },
    ],
    hotels: [
      {
        name: "Burj Al Arab",
        description: "The world's most recognizable hotel, built on its own island in the shape of a sail. Even if you don't stay here, having afternoon tea in the atrium lobby is a bucket-list experience.",
        priceRange: "$1,500–$10,000/night",
        type: "Ultra-Luxury Icon",
        highlight: "In-room private butler and helipad",
      },
      {
        name: "Address Sky View",
        description: "Two interconnected towers with an infinity sky pool suspended 220 meters above Downtown Dubai. The view over the Burj Khalifa and Dubai Fountain is impossible to forget.",
        priceRange: "$400–$900/night",
        type: "Luxury City Hotel",
        highlight: "Sky-bridge infinity pool at 220m height",
      },
      {
        name: "Rove Downtown",
        description: "A smart, modern hotel within walking distance of the Burj Khalifa and Dubai Mall. Stylish, practical, and excellent value for Dubai's otherwise expensive accommodation market.",
        priceRange: "$80–$160/night",
        type: "Mid-Range Lifestyle Hotel",
        highlight: "5 minutes walk to Dubai Mall",
      },
    ],
    restaurants: [
      {
        name: "Nobu Atlantis",
        description: "The iconic Japanese-Peruvian fusion brand at home in the Atlantis hotel. Chef Nobu Matsuhisa's signature dishes with an Arabian Gulf sunset backdrop from the terrace.",
        cuisine: "Japanese-Peruvian Fusion",
        priceRange: "$80–$150/person",
        mustTry: "Black cod miso and yellowtail jalapeño",
      },
      {
        name: "Al Fanar Restaurant",
        description: "A celebration of authentic Emirati cuisine in a heritage setting overlooking the Dubai Creek. Taste food that predates the oil boom era — dates, camel milk desserts, and majboos rice.",
        cuisine: "Traditional Emirati",
        priceRange: "$30–$60/person",
        mustTry: "Majboos and camel milk crème brûlée",
      },
      {
        name: "Ravi Restaurant",
        description: "A 40-year-old Pakistani restaurant in Satwa beloved by every class of Dubai society. The karahi gosht and daal fry have fed taxi drivers and billionaires with equal devotion.",
        cuisine: "Pakistani",
        priceRange: "$5–$15/person",
        mustTry: "Karahi gosht and fresh naan",
      },
    ],
    gettingAround: [
      "Dubai Metro Red and Green lines connect major attractions — buy a Nol Card",
      "Careem (local ride-hailing) and Uber both operate reliably and cheaply",
      "RTA taxis are metered, plentiful, and run 24 hours — very affordable by global standards",
      "The Dubai Tram connects JBR, Media City, and Marina areas seamlessly",
      "Renting a car is popular for visiting Hatta, Al Qudra Lakes, and other outlying areas",
    ],
    proTips: [
      "The Dubai Mall fountain show runs every evening and is completely free to watch from outside",
      "Dubai's alcohol laws are complex — drinking is only permitted at licensed venues (hotels, clubs, restaurants)",
      "Dress conservatively in souks, malls, and public spaces — swimwear belongs at the beach or pool",
      "Ramadan changes operating hours and bans public eating/drinking — check dates before booking",
      "The best views of the Burj Khalifa and fountain are from the free outdoor terrace of Dubai Mall",
    ],
    offbeatPlaces: [
      {
        name: "Alserkal Avenue — Dubai's Art District",
        description: "A converted industrial warehouse complex in Al Quoz that houses over 60 contemporary art galleries, independent cinemas, design studios, and the city's best specialty coffee shops. The creative soul of Dubai.",
        why: "Dubai's gleaming malls and skyscrapers dominate the tourist experience. This warehouse district shows a completely different city — young, creative, and genuinely interesting.",
        icon: "🎨",
        type: "Arts & Culture",
        tip: "Visit on a weekday morning when galleries are open and the coffee crowd is in. First Thursdays feature gallery openings with free drinks.",
      },
      {
        name: "Hatta Mountain Village",
        description: "A 1.5-hour drive into the Hajar mountains brings you to a restored heritage village, turquoise dam, kayaking, and mountain biking trails through dramatic rocky terrain. Entirely unlike the Dubai everyone imagines.",
        why: "Almost every Dubai tourist stays within 10km of the Burj Khalifa. Hatta is a full day of genuine mountain adventure that feels like a different country.",
        icon: "⛰️",
        type: "Mountain Escape",
        tip: "Book an accommodation pod by the dam for a night under desert stars — it's one of the UAE's best experiences and surprisingly affordable.",
      },
      {
        name: "Al Fahidi Historical Neighbourhood",
        description: "Dubai's oldest surviving neighbourhood, a maze of wind-tower architecture and coral-stone houses that predates the oil boom. The Dubai Museum, excellent independent galleries, and the best chai in the city live here.",
        why: "Tourists photograph the Burj Al Arab. Locals say Al Fahidi is the real Dubai — the city as it existed before the world noticed.",
        icon: "🏛️",
        type: "Historical Quarter",
        tip: "Take an abra (wooden boat) across the Creek for AED 1 and explore the gold and spice souks on the other side. Do it at dusk.",
      },
      {
        name: "Al Qudra Desert Lakes",
        description: "A hidden network of artificial lakes in the desert south of Dubai where flamingos, ducks, and migratory birds gather against a backdrop of golden dunes. A bizarre and beautiful secret just 40 minutes from downtown.",
        why: "Known to Dubai residents but essentially undiscovered by tourists. Watching sunset over flamingos in the desert with the city skyline visible on the horizon is surreal.",
        icon: "🦩",
        type: "Desert Secret",
        tip: "Bring your own food and a blanket for a desert picnic at sunset. The 'Lovers Lake' heart-shaped lake is the most photogenic spot.",
      },
    ],
  },
  {
    slug: "goa",
    name: "Goa",
    country: "India",
    flag: "🇮🇳",
    tagline: "Sun, Sea & Soul",
    description: "India's smallest state is its most hedonistic — Portuguese colonial churches, endless palm-fringed beaches, seafood so fresh it came out of the water this morning, and a nightlife culture unlike anywhere else in India.",
    heroDescription: "Where the Arabian Sea meets four centuries of colonial history. Goa moves at its own unhurried pace between feast days, feni-fueled beach parties, and languorous beach village life.",
    stats: {
      bestTime: "Nov – Feb",
      budget: "$25–$100/day",
      language: "Konkani, Portuguese, English",
      currency: "INR (Rupee)",
    },
    vibes: ["Beach", "Romantic", "Bohemian"],
    gradient: "from-teal-500 via-cyan-400 to-blue-400",
    accentColor: "#06B6D4",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1600&q=85",
    thingsToDo: [
      {
        name: "Palolem Beach Kayaking",
        description: "Goa's most photogenic crescent beach with calm waters perfect for kayaking to Honeymoon Island and Butterfly Beach at sunrise before the crowds arrive.",
        icon: "🚣",
        duration: "3–4 hours",
        category: "Adventure",
      },
      {
        name: "Old Goa Churches",
        description: "The UNESCO-listed Basilica of Bom Jesus contains the mortal remains of St. Francis Xavier. The Portuguese Baroque architecture rising from the jungle is unexpectedly magnificent.",
        icon: "⛪",
        duration: "2–3 hours",
        category: "Cultural",
      },
      {
        name: "Anjuna Flea Market",
        description: "The original hippie market that started in the 1960s. A labyrinth of Rajasthani textiles, silver jewelry, leather goods, and everything tie-dyed every Wednesday afternoon.",
        icon: "🧿",
        duration: "Half day",
        category: "Shopping",
      },
      {
        name: "Spice Plantation Tour",
        description: "A guided walk through a lush plantation where vanilla, cardamom, black pepper, and turmeric grow. Traditional Goan lunch served on banana leaves included.",
        icon: "🌿",
        duration: "4–5 hours",
        category: "Culinary",
      },
      {
        name: "Dudhsagar Falls",
        description: "A 600m four-tiered waterfall that translates to 'sea of milk.' Accessible by jeep safari through the Bhagwan Mahavir Wildlife Sanctuary — most spectacular during monsoon.",
        icon: "💦",
        duration: "Full day",
        category: "Nature",
      },
    ],
    hotels: [
      {
        name: "Taj Exotica Resort & Spa",
        description: "A sprawling beachfront resort on Benaulim Beach with 56 acres of manicured grounds, a spectacular pool, and the kind of service only a Taj hotel delivers.",
        priceRange: "$200–$450/night",
        type: "Luxury Beachfront Resort",
        highlight: "Private beach and championship putting green",
      },
      {
        name: "Elsewhere",
        description: "A dreamy collection of heritage cottages and treehouses on the banks of the Mandovi River. The kind of boutique stay where you wake to birdsong and forget your phone.",
        priceRange: "$80–$180/night",
        type: "Heritage Boutique Retreat",
        highlight: "River-facing heritage cottages",
      },
      {
        name: "Zostel Goa (Palolem)",
        description: "The most beautiful hostel in Goa, right on Palolem Beach. Bamboo beach huts and dorms with direct sand access, hammocks, and a vibrant community of world travelers.",
        priceRange: "$15–$45/night",
        type: "Beach Hostel",
        highlight: "Beachfront bamboo huts",
      },
    ],
    restaurants: [
      {
        name: "Mum's Kitchen",
        description: "The definitive repository of traditional Goan home cooking. Grandmothers' recipes collected from across the state — prawn balchão, sorpotel, and xacuti served with love.",
        cuisine: "Traditional Goan Home Cooking",
        priceRange: "$12–$25/person",
        mustTry: "Fish curry rice and prawn balchão",
      },
      {
        name: "Gunpowder",
        description: "A rooftop restaurant in Assagao with a menu spanning the entire Indian subcontinent. The Mangalorean fish curry and Kerala beef fry attract visitors from across North Goa.",
        cuisine: "Regional Indian",
        priceRange: "$10–$20/person",
        mustTry: "Mangalorean fish curry and parotta",
      },
      {
        name: "Vinayak Family Restaurant",
        description: "An unassuming local haunt in Calangute beloved for its authentic Goan thali. No frills, full flavors, and portions that make a meal of it for the whole day.",
        cuisine: "Local Goan Thali",
        priceRange: "$4–$8/person",
        mustTry: "Full Goan thali with rice, curry, and feni",
      },
    ],
    gettingAround: [
      "Renting a scooter or motorcycle is the best way to explore — ask your accommodation to arrange it",
      "Goa Miles app is more reliable than traditional taxis for metered, air-conditioned rides",
      "Local buses are extremely cheap and go nearly everywhere in the state",
      "Auto-rickshaws are abundant in towns but negotiate the price firmly before getting in",
      "Hiring a driver for a full day costs $25–40 and lets you cover North or South Goa comprehensively",
    ],
    proTips: [
      "Feni (cashew or coconut spirit) is Goa's indigenous liquor — try it at a local bar, not a tourist trap",
      "Beach shacks close for monsoon (Jun–Sep) and the best ones book up fast in peak season (Dec–Jan)",
      "The north (Vagator, Anjuna, Calangute) is lively and touristy; the south (Palolem, Agonda) is peaceful and beautiful",
      "Portuguese pork sausages (choriz) from local bakeries are a breakfast institution",
      "Nightlife in North Goa requires advance planning — the best parties are often in private venues",
    ],
    offbeatPlaces: [
      {
        name: "Divar Island",
        description: "A sleepy island in the Mandovi river accessible only by ferry, where Portuguese colonial villas crumble beautifully among paddy fields, churches hold centuries-old festivals, and the loudest sound is birdsong.",
        why: "While tourists crowd Baga and Calangute, this island 20 minutes from Panaji exists in a completely different time. Almost no tourist infrastructure — just local life.",
        icon: "⛪",
        type: "Hidden Island",
        tip: "Rent a bicycle on the island and ride to Nossa Senhora de Piedade Church for views over the river. Go on a weekday — weekends bring a few day-trippers.",
      },
      {
        name: "Fontainhas — Goa's Latin Quarter",
        description: "Panjim's old Portuguese neighbourhood of brightly painted houses on steep narrow streets, tiled staircases, art galleries in converted mansions, and the most beautiful bakeries in India.",
        why: "Goa's most architecturally stunning neighbourhood is 10 minutes from the Mandovi ferry terminal yet sees a fraction of the visitors it deserves.",
        icon: "🎨",
        type: "Heritage Quarter",
        tip: "Visit the Fundação Oriente gallery (free entry) in a restored Portuguese mansion. Grab beef cutlets and bebinca at George Bar & Restaurant nearby.",
      },
      {
        name: "Kakolem 'Tiger Beach'",
        description: "An isolated crescent of white sand accessible only via a steep 20-minute trek through jungle from the road above. Named after a tiger sighted here decades ago. No shacks, no vendors, no crowds — just the sea.",
        why: "One of the most beautiful beaches in all of India, and almost completely unknown because getting there requires effort. That's exactly the point.",
        icon: "🐅",
        type: "Secret Beach",
        tip: "Located near Canacona in South Goa. Park at the top of the hill and follow the narrow jungle path down. Bring water and snacks — there's nothing there.",
      },
      {
        name: "Cabo de Rama Fort",
        description: "A 500-year-old clifftop fort at the southernmost tip of Goa's coast, mostly ruins but with spectacular views over a completely deserted coastline that seems to go on forever.",
        why: "Listed in every guide but visited by almost nobody. The views are among Goa's finest and the fort grounds have a wildness that Chapora (the Instagram fort) has lost.",
        icon: "🏯",
        type: "Ruined Fort",
        tip: "Go at sunset. Bring a picnic. The beach directly below the fort (Cola Beach) is accessible by a steep path and has two beautiful lagoons.",
      },
    ],
  },
];

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((city) => city.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return cities.map((city) => city.slug);
}
