import { City } from './types';

/**
 * Extended Indian cities — added in batches.
 * Batch 1 (10 cities): Jaisalmer, Srinagar, Dharamshala, Hyderabad,
 *   Chennai, Nainital, Lucknow, Khajuraho, Puri, Coorg
 *
 * TO ADD NEXT: Batch 2 — Gulmarg, Kasol, Spiti, Mussoorie, Haridwar,
 *   Jim Corbett, Bikaner, Ranthambore, Madurai, Ooty
 */
export const indianCitiesExtended: City[] = [

  // ── BATCH 1 ──────────────────────────────────────────────────

  {
    slug: 'jaisalmer', name: 'Jaisalmer', state: 'Rajasthan',
    country: 'India', flag: '🇮🇳', tagline: 'The Golden City',
    description: 'A 12th-century fort city rising from the Thar Desert — golden sandstone havelis, camel safaris, and the vast Sam Sand Dunes at sunset.',
    heroDescription: 'The Sonar Quila (Golden Fort) is one of the largest living forts in the world. Half the old city still lives inside its walls, making it unique in all of India.',
    stats: { bestTime: 'Oct – Feb', budget: '$15–$60/day', language: 'Hindi, Rajasthani', currency: 'INR (Rupee)' },
    vibes: ['Adventure', 'Cultural', 'Romantic'],
    gradient: 'from-amber-800 to-orange-900', accentColor: '#D97706',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Jaisalmer Fort', emoji: '🏯', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'Living golden fort', spots: [
          { name: 'Sonar Quila (Golden Fort)', tag: 'UNESCO' },
          { name: 'Patwon Ki Haveli', tag: 'Architecture' },
          { name: 'Jain Temples inside fort', tag: 'Sacred' },
          { name: 'Gadisar Lake', tag: 'Sunset' },
          { name: 'Folklore Museum', tag: 'Culture' },
        ]},
      { name: 'Sam Sand Dunes', emoji: '🐪', accentColor: '#F59E0B',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'Camel safaris & desert camps', spots: [
          { name: 'Sam Dunes camel safari', tag: 'Must-do' },
          { name: 'Overnight desert camps', tag: 'Stay' },
          { name: 'Sunrise over the dunes', tag: 'Photography' },
          { name: 'Kuldhara abandoned village', tag: 'Haunting' },
        ]},
      { name: 'Desert Villages', emoji: '🌵', accentColor: '#EA580C',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'Authentic Thar life', spots: [
          { name: 'Bada Bagh cenotaphs', tag: 'Heritage' },
          { name: 'Desert National Park', tag: 'Wildlife' },
          { name: 'Khuri dunes (quieter)', tag: 'Hidden gem' },
          { name: 'Thar Heritage Museum', tag: 'Culture' },
        ]},
    ],
  },

  {
    slug: 'srinagar', name: 'Srinagar', state: 'Jammu & Kashmir',
    country: 'India', flag: '🇮🇳', tagline: 'Paradise on Earth',
    description: 'Kashmir\'s capital sits on Dal Lake — houseboats, Mughal gardens, and snow-capped peaks make it India\'s most romantic destination.',
    heroDescription: 'Wake up on a wooden houseboat as the morning mist lifts off Dal Lake, with the Pir Panjal mountains reflected in the water. There is nowhere else like Srinagar.',
    stats: { bestTime: 'Apr – Oct', budget: '$20–$80/day', language: 'Kashmiri, Urdu, Hindi', currency: 'INR (Rupee)' },
    vibes: ['Romantic', 'Cultural', 'Nature'],
    gradient: 'from-blue-900 to-cyan-900', accentColor: '#0891B2',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Dal Lake', emoji: '🚣', accentColor: '#0891B2',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
        tagline: 'Houseboats & floating markets', spots: [
          { name: 'Shikara ride at sunrise', tag: 'Must-do' },
          { name: 'Floating Vegetable Market (dawn)', tag: 'Unique' },
          { name: 'Dal Lake houseboats', tag: 'Stay' },
          { name: 'Nehru Park island', tag: 'Scenic' },
        ]},
      { name: 'Mughal Gardens', emoji: '🌸', accentColor: '#7C3AED',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
        tagline: 'Persian paradise gardens', spots: [
          { name: 'Shalimar Bagh (most famous)', tag: 'Mughal' },
          { name: 'Nishat Bagh (terraced)', tag: 'Garden' },
          { name: 'Chashme Shahi (smallest, sweetest water)', tag: 'Sacred' },
          { name: 'Pari Mahal ruins', tag: 'Views' },
        ]},
      { name: 'Old City & Bazaars', emoji: '🛍️', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
        tagline: 'Crafts, carpets & Kashmiri food', spots: [
          { name: 'Jama Masjid', tag: 'Sacred' },
          { name: 'Lal Chowk (city centre)', tag: 'Shopping' },
          { name: 'Kashmiri carpet & shawl shops', tag: 'Crafts' },
          { name: 'Wazwan (royal feast) dinner', tag: 'Culinary' },
        ]},
    ],
  },

  {
    slug: 'dharamshala', name: 'Dharamshala', state: 'Himachal Pradesh',
    country: 'India', flag: '🇮🇳', tagline: 'Little Lhasa in the Himalayas',
    description: 'Home of the Dalai Lama and the Tibetan government-in-exile — McLeod Ganj has Tibetan monasteries, great trekking, and arguably India\'s best café culture.',
    heroDescription: 'The Dhauladhar Range rises dramatically behind McLeod Ganj, where red-robed monks share the lanes with backpackers. The Dalai Lama\'s temple is open to visitors every morning.',
    stats: { bestTime: 'Mar – Jun, Sep – Nov', budget: '$12–$45/day', language: 'Hindi, Tibetan, English', currency: 'INR (Rupee)' },
    vibes: ['Spiritual', 'Adventure', 'Cultural'],
    gradient: 'from-slate-800 to-blue-900', accentColor: '#2563EB',
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'McLeod Ganj', emoji: '🙏', accentColor: '#2563EB',
        image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80',
        tagline: 'Tibetan culture & Dalai Lama', spots: [
          { name: 'Tsuglagkhang (Dalai Lama Temple)', tag: 'Sacred' },
          { name: 'Tibet Museum', tag: 'Moving' },
          { name: 'Bhagsu waterfall short trek', tag: 'Nature' },
          { name: 'Tibetan restaurants & momos', tag: 'Food' },
        ]},
      { name: 'Dharamkot & Triund', emoji: '🏔️', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80',
        tagline: 'Best day trek in Himachal', spots: [
          { name: 'Triund hilltop (9km trek)', tag: 'Best trek' },
          { name: 'Dharamkot village cafes', tag: 'Chill' },
          { name: 'Guna Devi Temple', tag: 'Views' },
          { name: 'Yoga & meditation centres', tag: 'Wellness' },
        ]},
      { name: 'Kangra Valley', emoji: '🌿', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80',
        tagline: 'Tea gardens & ancient temples', spots: [
          { name: 'Kangra Fort (oldest in Himachal)', tag: 'Historical' },
          { name: 'Masrur Rock Temple', tag: 'Hidden gem' },
          { name: 'Kangra Art Museum', tag: 'Culture' },
          { name: 'Palampur tea estates', tag: 'Scenic' },
        ]},
    ],
  },

  {
    slug: 'hyderabad', name: 'Hyderabad', state: 'Telangana',
    country: 'India', flag: '🇮🇳', tagline: 'City of Pearls & Biryani',
    description: 'The city of Nizams — Charminar, Golconda Fort, the world\'s finest biryani, and a booming tech sector that has made it India\'s most cosmopolitan southern city.',
    heroDescription: 'Hyderabad straddles old and new India perfectly — 16th-century mosques beside glass tech campuses, street-side biryani beside Michelin-rated restaurants.',
    stats: { bestTime: 'Oct – Feb', budget: '$20–$80/day', language: 'Telugu, Urdu, Hindi', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Foodie', 'Historical'],
    gradient: 'from-orange-900 to-red-900', accentColor: '#C2410C',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Old City', emoji: '🕌', accentColor: '#C2410C',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Charminar, biryani & bazaars', spots: [
          { name: 'Charminar', tag: 'Iconic' },
          { name: 'Laad Bazaar (bangles)', tag: 'Shopping' },
          { name: 'Mecca Masjid', tag: 'Sacred' },
          { name: 'Hyderabadi Biryani at Paradise', tag: 'Must-eat' },
          { name: 'Chowmahalla Palace', tag: 'Nizam heritage' },
        ]},
      { name: 'Golconda & Hussain Sagar', emoji: '🏯', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Fort & lake city highlights', spots: [
          { name: 'Golconda Fort (Sound & Light show)', tag: 'Must-see' },
          { name: 'Qutb Shahi Tombs', tag: 'UNESCO' },
          { name: 'Hussain Sagar Lake boat ride', tag: 'Scenic' },
          { name: 'Birla Mandir (hilltop temple)', tag: 'Views' },
        ]},
      { name: 'Banjara Hills & HITEC', emoji: '☕', accentColor: '#7C3AED',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Modern Hyderabad', spots: [
          { name: 'Ramoji Film City (world\'s largest)', tag: 'Entertainment' },
          { name: 'Salar Jung Museum', tag: 'Best museum' },
          { name: 'Shilparamam crafts village', tag: 'Culture' },
          { name: 'Irani Chai at Nimrah Cafe', tag: 'Institution' },
        ]},
    ],
  },

  {
    slug: 'chennai', name: 'Chennai', state: 'Tamil Nadu',
    country: 'India', flag: '🇮🇳', tagline: 'Gateway to South India',
    description: 'India\'s fourth-largest city — Marina Beach (world\'s second longest), Dravidian temples, classical music, filter coffee, and the warmest hospitality in the country.',
    heroDescription: 'Chennai is where South Indian civilization is most concentrated — ancient temples, Bharatanatyam dance, and a culinary tradition that makes every other Indian cuisine jealous.',
    stats: { bestTime: 'Nov – Feb', budget: '$20–$70/day', language: 'Tamil, English', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Foodie', 'Historical'],
    gradient: 'from-red-900 to-orange-900', accentColor: '#DC2626',
    image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Marina Beach & Mylapore', emoji: '🌊', accentColor: '#DC2626',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'World\'s second longest beach', spots: [
          { name: 'Marina Beach at dawn', tag: 'Must-see' },
          { name: 'Kapaleeshwarar Temple', tag: 'Sacred' },
          { name: 'Filter coffee at Murugan Idli', tag: 'Breakfast' },
          { name: 'San Thome Cathedral', tag: 'Colonial' },
        ]},
      { name: 'Fort & Georgetown', emoji: '🏛️', accentColor: '#B91C1C',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'Colonial heritage & temples', spots: [
          { name: 'Fort St George & Museum', tag: 'Historical' },
          { name: 'Parthasarathy Temple (8th c)', tag: 'Ancient' },
          { name: 'Armenian Street', tag: 'Heritage' },
          { name: 'Parry\'s Corner market', tag: 'Chaotic' },
        ]},
      { name: 'T. Nagar & Pondy Bazaar', emoji: '🛍️', accentColor: '#F97316',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'Shopping & local life', spots: [
          { name: 'Ranganathan Street (busiest in Asia)', tag: 'Shopping' },
          { name: 'Saravana Bhavan (legendary thali)', tag: 'Must-eat' },
          { name: 'Mahabalipuram day trip (58km)', tag: 'UNESCO' },
          { name: 'Government Museum (free)', tag: 'Culture' },
        ]},
    ],
  },

  {
    slug: 'nainital', name: 'Nainital', state: 'Uttarakhand',
    country: 'India', flag: '🇮🇳', tagline: 'Lake District of India',
    description: 'A crescent-shaped lake encircled by seven hills — the most romantic hill station in Uttarakhand, with Himalayan panoramas, boating, and the Governor\'s colonial estate.',
    heroDescription: 'Naini Lake reflects the surrounding Kumaon Himalayan peaks in perfect clarity. The Mall Road circling the lake is the most pleasant promenade in North India\'s hills.',
    stats: { bestTime: 'Mar – Jun, Sep – Nov', budget: '$15–$50/day', language: 'Hindi, Kumaoni', currency: 'INR (Rupee)' },
    vibes: ['Romantic', 'Nature', 'Wellness'],
    gradient: 'from-blue-900 to-teal-900', accentColor: '#0D9488',
    image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Naini Lake & Mall Road', emoji: '🚣', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Boating & colonial promenade', spots: [
          { name: 'Naini Lake boating', tag: 'Must-do' },
          { name: 'Naini Devi Temple', tag: 'Sacred' },
          { name: 'Mall Road evening walk', tag: 'Classic' },
          { name: 'Boat house club sunset', tag: 'Views' },
        ]},
      { name: 'Snow View & Tiffin Top', emoji: '🏔️', accentColor: '#2563EB',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Himalayan panoramas', spots: [
          { name: 'Snow View Point (cable car)', tag: 'Views' },
          { name: 'Tiffin Top (Dorothy\'s Seat) trek', tag: 'Short trek' },
          { name: 'Land\'s End viewpoint', tag: 'Sunset' },
          { name: 'Ayarpatta Hill', tag: 'Forest walk' },
        ]},
      { name: 'Corbett Surrounds', emoji: '🐘', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Wildlife & nearby villages', spots: [
          { name: 'Bhimtal Lake (nearby)', tag: 'Day trip' },
          { name: 'Sattal (seven lakes)', tag: 'Birdwatching' },
          { name: 'Mukteshwar temple trek', tag: 'Views' },
          { name: 'Ramgarh fruit orchards', tag: 'Unique' },
        ]},
    ],
  },

  {
    slug: 'lucknow', name: 'Lucknow', state: 'Uttar Pradesh',
    country: 'India', flag: '🇮🇳', tagline: 'City of Nawabs',
    description: 'The most graceful city in North India — Nawabi architecture, the finest Awadhi cuisine, Chikankari embroidery, and a refinement of manners (tehzeeb) that defines the city.',
    heroDescription: 'Lucknow perfected the art of living — the Bara Imambara\'s labyrinthine Bhulbhulaiya, biryani slow-cooked in sealed pots, and an elegance that survived every upheaval.',
    stats: { bestTime: 'Oct – Mar', budget: '$15–$50/day', language: 'Hindi, Urdu', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Foodie', 'Historical'],
    gradient: 'from-amber-900 to-orange-900', accentColor: '#B45309',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Old City (Chowk)', emoji: '🕌', accentColor: '#B45309',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Nawabi monuments & street food', spots: [
          { name: 'Bara Imambara & Bhulbhulaiya', tag: 'Must-see' },
          { name: 'Rumi Darwaza (Turkish Gate)', tag: 'Iconic' },
          { name: 'Chota Imambara (Palace of Lights)', tag: 'Beautiful' },
          { name: 'Tunday Kababi (150 yr old)', tag: 'Institution' },
          { name: 'Chowk bazaar', tag: 'Chikankari' },
        ]},
      { name: 'Hazratganj & Residency', emoji: '🏛️', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'British-era boulevard & ruins', spots: [
          { name: 'The Residency (1857 siege ruins)', tag: 'Historical' },
          { name: 'Hazratganj promenade', tag: 'Strolling' },
          { name: 'Nawabi cuisine at Idrees Biryani', tag: 'Food' },
          { name: 'State Museum', tag: 'Culture' },
        ]},
      { name: 'Aminabad & Bazaars', emoji: '🧵', accentColor: '#92400E',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Chikankari & Awadhi sweets', spots: [
          { name: 'Chikankari embroidery workshops', tag: 'Craft' },
          { name: 'Aminabad cloth market', tag: 'Shopping' },
          { name: 'Malai ki Gilori (seasonal sweet)', tag: 'Unique' },
          { name: 'Paranthe wali gali', tag: 'Street food' },
        ]},
    ],
  },

  {
    slug: 'khajuraho', name: 'Khajuraho', state: 'Madhya Pradesh',
    country: 'India', flag: '🇮🇳', tagline: 'Temples of Love & Devotion',
    description: 'A UNESCO World Heritage Site — 85 medieval Hindu and Jain temples famous for their intricate erotic carvings, but also masterpieces of spiritual architecture and cosmic symbolism.',
    heroDescription: 'Built between 950–1050 AD by the Chandela dynasty, Khajuraho\'s temples are covered in 10% erotic sculptures representing divine love. The remaining 90% is pure spiritual devotion.',
    stats: { bestTime: 'Oct – Mar', budget: '$15–$50/day', language: 'Hindi, Bundeli', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Historical', 'Spiritual'],
    gradient: 'from-stone-800 to-amber-900', accentColor: '#92400E',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Western Group', emoji: '🛕', accentColor: '#92400E',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'UNESCO main complex', spots: [
          { name: 'Kandariya Mahadeva Temple', tag: 'Most famous' },
          { name: 'Chitragupta Temple', tag: 'Sun god' },
          { name: 'Devi Jagadambi Temple', tag: 'Carvings' },
          { name: 'Light & Sound Show (evenings)', tag: 'Experience' },
        ]},
      { name: 'Eastern & Southern Groups', emoji: '🏛️', accentColor: '#B45309',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Jain temples & village life', spots: [
          { name: 'Parsvanatha Jain Temple', tag: 'Finest Jain' },
          { name: 'Chaturbhuja Temple', tag: 'Unique' },
          { name: 'Local village walks', tag: 'Authentic' },
          { name: 'Archaeological Museum', tag: 'Context' },
        ]},
      { name: 'Panna & Surrounds', emoji: '🐯', accentColor: '#166534',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Tigers & diamond mines', spots: [
          { name: 'Panna Tiger Reserve (25km)', tag: 'Wildlife' },
          { name: 'Raneh Falls Canyon', tag: 'Nature' },
          { name: 'Ken River safari', tag: 'Adventure' },
          { name: 'Ajaygarh Fort (60km)', tag: 'Day trip' },
        ]},
    ],
  },

  {
    slug: 'puri', name: 'Puri', state: 'Odisha',
    country: 'India', flag: '🇮🇳', tagline: 'Abode of Lord Jagannath',
    description: 'One of the four sacred dhams of Hinduism — the Jagannath Temple, the annual Rath Yatra chariot festival, and a long golden beach where pilgrims and beach-lovers coexist.',
    heroDescription: 'Puri\'s sacred geography is unique — the Jagannath Temple\'s flag is always visible from the sea, and the beach stretches unbroken for miles. The Rath Yatra draws a million devotees.',
    stats: { bestTime: 'Oct – Feb', budget: '$12–$40/day', language: 'Odia, Hindi', currency: 'INR (Rupee)' },
    vibes: ['Spiritual', 'Beach', 'Cultural'],
    gradient: 'from-orange-900 to-amber-900', accentColor: '#EA580C',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Jagannath Temple & Grand Road', emoji: '🛕', accentColor: '#EA580C',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Holiest dham of Odisha', spots: [
          { name: 'Jagannath Temple (non-Hindus from rooftop only)', tag: 'Sacred' },
          { name: 'Grand Road (Rath Yatra route)', tag: 'Pilgrimage' },
          { name: 'Matha (monastery) complexes', tag: 'Culture' },
          { name: 'Mahaprasad (temple food)', tag: 'Unique' },
        ]},
      { name: 'Puri Beach', emoji: '🏖️', accentColor: '#F59E0B',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Long golden coast', spots: [
          { name: 'Puri Beach sunrise', tag: 'Beautiful' },
          { name: 'Swargadwar cremation ghat', tag: 'Sacred' },
          { name: 'Chilika Lake day trip (largest lagoon)', tag: 'Nature' },
          { name: 'Konark Sun Temple (35km)', tag: 'UNESCO' },
        ]},
      { name: 'Pipili & Raghurajpur', emoji: '🎨', accentColor: '#7C3AED',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Odisha\'s craft villages', spots: [
          { name: 'Pipili appliqué craft village', tag: 'Handicrafts' },
          { name: 'Raghurajpur artists\' village', tag: 'Pattachitra' },
          { name: 'Bhubaneswar temple trail (60km)', tag: 'Day trip' },
          { name: 'Odisha State Museum', tag: 'Culture' },
        ]},
    ],
  },

  {
    slug: 'coorg', name: 'Coorg (Kodagu)', state: 'Karnataka',
    country: 'India', flag: '🇮🇳', tagline: 'Scotland of India',
    description: 'A mist-covered district of coffee and cardamom estates, sacred rivers, ancient Kodava warrior culture, and the most pristine forest landscape in South India.',
    heroDescription: 'The Kodava people — India\'s only warrior community allowed to carry firearms — have maintained a unique culture amid estates that produce 30% of India\'s coffee. Coorg is unlike any other India.',
    stats: { bestTime: 'Oct – Apr', budget: '$20–$80/day', language: 'Kodava, Kannada', currency: 'INR (Rupee)' },
    vibes: ['Nature', 'Wellness', 'Adventure'],
    gradient: 'from-green-900 to-emerald-900', accentColor: '#166534',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Madikeri & Coffee Estates', emoji: '☕', accentColor: '#166534',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        tagline: 'Coffee, cardamom & misty hills', spots: [
          { name: 'Coffee estate plantation stay', tag: 'Must-do' },
          { name: 'Madikeri Fort', tag: 'Historic' },
          { name: 'Raja\'s Seat sunset viewpoint', tag: 'Views' },
          { name: 'Omkareshwara Temple', tag: 'Sacred' },
        ]},
      { name: 'Waterfalls & Nature', emoji: '💧', accentColor: '#059669',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        tagline: 'Jungle & cascading falls', spots: [
          { name: 'Abbey Falls', tag: 'Most visited' },
          { name: 'Iruppu Falls trek', tag: 'Remote' },
          { name: 'Nagarhole National Park', tag: 'Tigers' },
          { name: 'Nisargadhama river island', tag: 'Nature' },
        ]},
      { name: 'Talacauvery & Brahmagiri', emoji: '🏔️', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        tagline: 'Sacred source of Cauvery', spots: [
          { name: 'Talacauvery (Cauvery source)', tag: 'Sacred' },
          { name: 'Brahmagiri peak trek', tag: 'Adventure' },
          { name: 'Bylakuppe Tibetan settlement', tag: 'Unique' },
          { name: 'Dubare elephant camp', tag: 'Elephants' },
        ]},
    ],
  },

  // ── BATCH 2 PLACEHOLDER ──────────────────────────────────────
  // Add next 10 cities here in the next session:
  // Gulmarg, Kasol, Spiti, Mussoorie, Haridwar,
  // Jim Corbett, Bikaner, Madurai, Ooty, Mahabalipuram
];
