import { City } from './types';

/**
 * Extended Indian cities — added in batches.
 * Batch 1 (10 cities): Jaisalmer, Srinagar, Dharamshala, Hyderabad,
 *   Chennai, Nainital, Lucknow, Khajuraho, Puri, Coorg
 *
 * Batch 2 (10 cities): Gulmarg, Kasol, Spiti, Mussoorie, Haridwar,
 *   Jim Corbett, Bikaner, Madurai, Ooty, Mahabalipuram
 *
 * TO ADD NEXT: Batch 4 — Amritsar, Kanyakumari, Hampi, Udaipur, Mount Abu,
 *   Rann of Kutch, Shillong, Gangtok, Auroville, Mysore
 */
export const indianCitiesExtended: City[] = [

  // ── BATCH 1 ──────────────────────────────────────────────────

  {
    slug: 'jaisalmer', name: 'Jaisalmer', state: 'Rajasthan',
    country: 'India', flag: '🇮🇳', tagline: 'The Golden City',
    description: 'A 12th-century fort city rising from the Thar Desert — golden sandstone havelis, camel safaris, and the vast Sam Sand Dunes at sunset.',
    heroDescription: 'The Sonar Quila (Golden Fort) is one of the largest living forts in the world. Half the old city still lives inside its walls, making it unique in all of India.',
    stats: { bestTime: 'Oct – Feb', budget: '$15–$60/day', language: 'Hindi, Rajasthani', currency: 'INR (Rupee)' },
    vibes: ['Adventure', 'Cultural', 'Romantic'],
    gradient: 'from-amber-800 to-orange-900', accentColor: '#D97706',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Jaisalmer Fort', emoji: '🏯', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'Living golden fort', spots: [
          { name: 'Sonar Quila (Golden Fort)', tag: 'UNESCO' },
          { name: 'Patwon Ki Haveli', tag: 'Architecture' },
          { name: 'Jain Temples inside fort', tag: 'Sacred' },
          { name: 'Gadisar Lake', tag: 'Sunset' },
          { name: 'Folklore Museum', tag: 'Culture' },
        ]},
      { name: 'Sam Sand Dunes', emoji: '🐪', accentColor: '#F59E0B',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'Camel safaris & desert camps', spots: [
          { name: 'Sam Dunes camel safari', tag: 'Must-do' },
          { name: 'Overnight desert camps', tag: 'Stay' },
          { name: 'Sunrise over the dunes', tag: 'Photography' },
          { name: 'Kuldhara abandoned village', tag: 'Haunting' },
        ]},
      { name: 'Desert Villages', emoji: '🌵', accentColor: '#EA580C',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'Authentic Thar life', spots: [
          { name: 'Bada Bagh cenotaphs', tag: 'Heritage' },
          { name: 'Desert National Park', tag: 'Wildlife' },
          { name: 'Khuri dunes (quieter)', tag: 'Hidden gem' },
          { name: 'Thar Heritage Museum', tag: 'Culture' },
        ]},
    ],
  },

  {
    slug: 'srinagar', name: 'Srinagar', state: 'Jammu & Kashmir',
    country: 'India', flag: '🇮🇳', tagline: 'Paradise on Earth',
    description: 'Kashmir\'s capital sits on Dal Lake — houseboats, Mughal gardens, and snow-capped peaks make it India\'s most romantic destination.',
    heroDescription: 'Wake up on a wooden houseboat as the morning mist lifts off Dal Lake, with the Pir Panjal mountains reflected in the water. There is nowhere else like Srinagar.',
    stats: { bestTime: 'Apr – Oct', budget: '$20–$80/day', language: 'Kashmiri, Urdu, Hindi', currency: 'INR (Rupee)' },
    vibes: ['Romantic', 'Cultural', 'Nature'],
    gradient: 'from-blue-900 to-cyan-900', accentColor: '#0891B2',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Dal Lake', emoji: '🚣', accentColor: '#0891B2',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
        tagline: 'Houseboats & floating markets', spots: [
          { name: 'Shikara ride at sunrise', tag: 'Must-do' },
          { name: 'Floating Vegetable Market (dawn)', tag: 'Unique' },
          { name: 'Dal Lake houseboats', tag: 'Stay' },
          { name: 'Nehru Park island', tag: 'Scenic' },
        ]},
      { name: 'Mughal Gardens', emoji: '🌸', accentColor: '#7C3AED',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
        tagline: 'Persian paradise gardens', spots: [
          { name: 'Shalimar Bagh (most famous)', tag: 'Mughal' },
          { name: 'Nishat Bagh (terraced)', tag: 'Garden' },
          { name: 'Chashme Shahi (smallest, sweetest water)', tag: 'Sacred' },
          { name: 'Pari Mahal ruins', tag: 'Views' },
        ]},
      { name: 'Old City & Bazaars', emoji: '🛍️', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80',
        tagline: 'Crafts, carpets & Kashmiri food', spots: [
          { name: 'Jama Masjid', tag: 'Sacred' },
          { name: 'Lal Chowk (city centre)', tag: 'Shopping' },
          { name: 'Kashmiri carpet & shawl shops', tag: 'Crafts' },
          { name: 'Wazwan (royal feast) dinner', tag: 'Culinary' },
        ]},
    ],
  },

  {
    slug: 'dharamshala', name: 'Dharamshala', state: 'Himachal Pradesh',
    country: 'India', flag: '🇮🇳', tagline: 'Little Lhasa in the Himalayas',
    description: 'Home of the Dalai Lama and the Tibetan government-in-exile — McLeod Ganj has Tibetan monasteries, great trekking, and arguably India\'s best café culture.',
    heroDescription: 'The Dhauladhar Range rises dramatically behind McLeod Ganj, where red-robed monks share the lanes with backpackers. The Dalai Lama\'s temple is open to visitors every morning.',
    stats: { bestTime: 'Mar – Jun, Sep – Nov', budget: '$12–$45/day', language: 'Hindi, Tibetan, English', currency: 'INR (Rupee)' },
    vibes: ['Spiritual', 'Adventure', 'Cultural'],
    gradient: 'from-slate-800 to-blue-900', accentColor: '#2563EB',
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'McLeod Ganj', emoji: '🙏', accentColor: '#2563EB',
        image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80',
        tagline: 'Tibetan culture & Dalai Lama', spots: [
          { name: 'Tsuglagkhang (Dalai Lama Temple)', tag: 'Sacred' },
          { name: 'Tibet Museum', tag: 'Moving' },
          { name: 'Bhagsu waterfall short trek', tag: 'Nature' },
          { name: 'Tibetan restaurants & momos', tag: 'Food' },
        ]},
      { name: 'Dharamkot & Triund', emoji: '🏔️', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80',
        tagline: 'Best day trek in Himachal', spots: [
          { name: 'Triund hilltop (9km trek)', tag: 'Best trek' },
          { name: 'Dharamkot village cafes', tag: 'Chill' },
          { name: 'Guna Devi Temple', tag: 'Views' },
          { name: 'Yoga & meditation centres', tag: 'Wellness' },
        ]},
      { name: 'Kangra Valley', emoji: '🌿', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=600&q=80',
        tagline: 'Tea gardens & ancient temples', spots: [
          { name: 'Kangra Fort (oldest in Himachal)', tag: 'Historical' },
          { name: 'Masrur Rock Temple', tag: 'Hidden gem' },
          { name: 'Kangra Art Museum', tag: 'Culture' },
          { name: 'Palampur tea estates', tag: 'Scenic' },
        ]},
    ],
  },

  {
    slug: 'hyderabad', name: 'Hyderabad', state: 'Telangana',
    country: 'India', flag: '🇮🇳', tagline: 'City of Pearls & Biryani',
    description: 'The city of Nizams — Charminar, Golconda Fort, the world\'s finest biryani, and a booming tech sector that has made it India\'s most cosmopolitan southern city.',
    heroDescription: 'Hyderabad straddles old and new India perfectly — 16th-century mosques beside glass tech campuses, street-side biryani beside Michelin-rated restaurants.',
    stats: { bestTime: 'Oct – Feb', budget: '$20–$80/day', language: 'Telugu, Urdu, Hindi', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Foodie', 'Historical'],
    gradient: 'from-orange-900 to-red-900', accentColor: '#C2410C',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Old City', emoji: '🕌', accentColor: '#C2410C',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Charminar, biryani & bazaars', spots: [
          { name: 'Charminar', tag: 'Iconic' },
          { name: 'Laad Bazaar (bangles)', tag: 'Shopping' },
          { name: 'Mecca Masjid', tag: 'Sacred' },
          { name: 'Hyderabadi Biryani at Paradise', tag: 'Must-eat' },
          { name: 'Chowmahalla Palace', tag: 'Nizam heritage' },
        ]},
      { name: 'Golconda & Hussain Sagar', emoji: '🏯', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Fort & lake city highlights', spots: [
          { name: 'Golconda Fort (Sound & Light show)', tag: 'Must-see' },
          { name: 'Qutb Shahi Tombs', tag: 'UNESCO' },
          { name: 'Hussain Sagar Lake boat ride', tag: 'Scenic' },
          { name: 'Birla Mandir (hilltop temple)', tag: 'Views' },
        ]},
      { name: 'Banjara Hills & HITEC', emoji: '☕', accentColor: '#7C3AED',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Modern Hyderabad', spots: [
          { name: 'Ramoji Film City (world\'s largest)', tag: 'Entertainment' },
          { name: 'Salar Jung Museum', tag: 'Best museum' },
          { name: 'Shilparamam crafts village', tag: 'Culture' },
          { name: 'Irani Chai at Nimrah Cafe', tag: 'Institution' },
        ]},
    ],
  },

  {
    slug: 'chennai', name: 'Chennai', state: 'Tamil Nadu',
    country: 'India', flag: '🇮🇳', tagline: 'Gateway to South India',
    description: 'India\'s fourth-largest city — Marina Beach (world\'s second longest), Dravidian temples, classical music, filter coffee, and the warmest hospitality in the country.',
    heroDescription: 'Chennai is where South Indian civilization is most concentrated — ancient temples, Bharatanatyam dance, and a culinary tradition that makes every other Indian cuisine jealous.',
    stats: { bestTime: 'Nov – Feb', budget: '$20–$70/day', language: 'Tamil, English', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Foodie', 'Historical'],
    gradient: 'from-red-900 to-orange-900', accentColor: '#DC2626',
    image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Marina Beach & Mylapore', emoji: '🌊', accentColor: '#DC2626',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'World\'s second longest beach', spots: [
          { name: 'Marina Beach at dawn', tag: 'Must-see' },
          { name: 'Kapaleeshwarar Temple', tag: 'Sacred' },
          { name: 'Filter coffee at Murugan Idli', tag: 'Breakfast' },
          { name: 'San Thome Cathedral', tag: 'Colonial' },
        ]},
      { name: 'Fort & Georgetown', emoji: '🏛️', accentColor: '#B91C1C',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'Colonial heritage & temples', spots: [
          { name: 'Fort St George & Museum', tag: 'Historical' },
          { name: 'Parthasarathy Temple (8th c)', tag: 'Ancient' },
          { name: 'Armenian Street', tag: 'Heritage' },
          { name: 'Parry\'s Corner market', tag: 'Chaotic' },
        ]},
      { name: 'T. Nagar & Pondy Bazaar', emoji: '🛍️', accentColor: '#F97316',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'Shopping & local life', spots: [
          { name: 'Ranganathan Street (busiest in Asia)', tag: 'Shopping' },
          { name: 'Saravana Bhavan (legendary thali)', tag: 'Must-eat' },
          { name: 'Mahabalipuram day trip (58km)', tag: 'UNESCO' },
          { name: 'Government Museum (free)', tag: 'Culture' },
        ]},
    ],
  },

  {
    slug: 'nainital', name: 'Nainital', state: 'Uttarakhand',
    country: 'India', flag: '🇮🇳', tagline: 'Lake District of India',
    description: 'A crescent-shaped lake encircled by seven hills — the most romantic hill station in Uttarakhand, with Himalayan panoramas, boating, and the Governor\'s colonial estate.',
    heroDescription: 'Naini Lake reflects the surrounding Kumaon Himalayan peaks in perfect clarity. The Mall Road circling the lake is the most pleasant promenade in North India\'s hills.',
    stats: { bestTime: 'Mar – Jun, Sep – Nov', budget: '$15–$50/day', language: 'Hindi, Kumaoni', currency: 'INR (Rupee)' },
    vibes: ['Romantic', 'Nature', 'Wellness'],
    gradient: 'from-blue-900 to-teal-900', accentColor: '#0D9488',
    image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Naini Lake & Mall Road', emoji: '🚣', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Boating & colonial promenade', spots: [
          { name: 'Naini Lake boating', tag: 'Must-do' },
          { name: 'Naini Devi Temple', tag: 'Sacred' },
          { name: 'Mall Road evening walk', tag: 'Classic' },
          { name: 'Boat house club sunset', tag: 'Views' },
        ]},
      { name: 'Snow View & Tiffin Top', emoji: '🏔️', accentColor: '#2563EB',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Himalayan panoramas', spots: [
          { name: 'Snow View Point (cable car)', tag: 'Views' },
          { name: 'Tiffin Top (Dorothy\'s Seat) trek', tag: 'Short trek' },
          { name: 'Land\'s End viewpoint', tag: 'Sunset' },
          { name: 'Ayarpatta Hill', tag: 'Forest walk' },
        ]},
      { name: 'Corbett Surrounds', emoji: '🐘', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Wildlife & nearby villages', spots: [
          { name: 'Bhimtal Lake (nearby)', tag: 'Day trip' },
          { name: 'Sattal (seven lakes)', tag: 'Birdwatching' },
          { name: 'Mukteshwar temple trek', tag: 'Views' },
          { name: 'Ramgarh fruit orchards', tag: 'Unique' },
        ]},
    ],
  },

  {
    slug: 'lucknow', name: 'Lucknow', state: 'Uttar Pradesh',
    country: 'India', flag: '🇮🇳', tagline: 'City of Nawabs',
    description: 'The most graceful city in North India — Nawabi architecture, the finest Awadhi cuisine, Chikankari embroidery, and a refinement of manners (tehzeeb) that defines the city.',
    heroDescription: 'Lucknow perfected the art of living — the Bara Imambara\'s labyrinthine Bhulbhulaiya, biryani slow-cooked in sealed pots, and an elegance that survived every upheaval.',
    stats: { bestTime: 'Oct – Mar', budget: '$15–$50/day', language: 'Hindi, Urdu', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Foodie', 'Historical'],
    gradient: 'from-amber-900 to-orange-900', accentColor: '#B45309',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Old City (Chowk)', emoji: '🕌', accentColor: '#B45309',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Nawabi monuments & street food', spots: [
          { name: 'Bara Imambara & Bhulbhulaiya', tag: 'Must-see' },
          { name: 'Rumi Darwaza (Turkish Gate)', tag: 'Iconic' },
          { name: 'Chota Imambara (Palace of Lights)', tag: 'Beautiful' },
          { name: 'Tunday Kababi (150 yr old)', tag: 'Institution' },
          { name: 'Chowk bazaar', tag: 'Chikankari' },
        ]},
      { name: 'Hazratganj & Residency', emoji: '🏛️', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'British-era boulevard & ruins', spots: [
          { name: 'The Residency (1857 siege ruins)', tag: 'Historical' },
          { name: 'Hazratganj promenade', tag: 'Strolling' },
          { name: 'Nawabi cuisine at Idrees Biryani', tag: 'Food' },
          { name: 'State Museum', tag: 'Culture' },
        ]},
      { name: 'Aminabad & Bazaars', emoji: '🧵', accentColor: '#92400E',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Chikankari & Awadhi sweets', spots: [
          { name: 'Chikankari embroidery workshops', tag: 'Craft' },
          { name: 'Aminabad cloth market', tag: 'Shopping' },
          { name: 'Malai ki Gilori (seasonal sweet)', tag: 'Unique' },
          { name: 'Paranthe wali gali', tag: 'Street food' },
        ]},
    ],
  },

  {
    slug: 'khajuraho', name: 'Khajuraho', state: 'Madhya Pradesh',
    country: 'India', flag: '🇮🇳', tagline: 'Temples of Love & Devotion',
    description: 'A UNESCO World Heritage Site — 85 medieval Hindu and Jain temples famous for their intricate erotic carvings, but also masterpieces of spiritual architecture and cosmic symbolism.',
    heroDescription: 'Built between 950–1050 AD by the Chandela dynasty, Khajuraho\'s temples are covered in 10% erotic sculptures representing divine love. The remaining 90% is pure spiritual devotion.',
    stats: { bestTime: 'Oct – Mar', budget: '$15–$50/day', language: 'Hindi, Bundeli', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Historical', 'Spiritual'],
    gradient: 'from-stone-800 to-amber-900', accentColor: '#92400E',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Western Group', emoji: '🛕', accentColor: '#92400E',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'UNESCO main complex', spots: [
          { name: 'Kandariya Mahadeva Temple', tag: 'Most famous' },
          { name: 'Chitragupta Temple', tag: 'Sun god' },
          { name: 'Devi Jagadambi Temple', tag: 'Carvings' },
          { name: 'Light & Sound Show (evenings)', tag: 'Experience' },
        ]},
      { name: 'Eastern & Southern Groups', emoji: '🏛️', accentColor: '#B45309',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Jain temples & village life', spots: [
          { name: 'Parsvanatha Jain Temple', tag: 'Finest Jain' },
          { name: 'Chaturbhuja Temple', tag: 'Unique' },
          { name: 'Local village walks', tag: 'Authentic' },
          { name: 'Archaeological Museum', tag: 'Context' },
        ]},
      { name: 'Panna & Surrounds', emoji: '🐯', accentColor: '#166534',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Tigers & diamond mines', spots: [
          { name: 'Panna Tiger Reserve (25km)', tag: 'Wildlife' },
          { name: 'Raneh Falls Canyon', tag: 'Nature' },
          { name: 'Ken River safari', tag: 'Adventure' },
          { name: 'Ajaygarh Fort (60km)', tag: 'Day trip' },
        ]},
    ],
  },

  {
    slug: 'puri', name: 'Puri', state: 'Odisha',
    country: 'India', flag: '🇮🇳', tagline: 'Abode of Lord Jagannath',
    description: 'One of the four sacred dhams of Hinduism — the Jagannath Temple, the annual Rath Yatra chariot festival, and a long golden beach where pilgrims and beach-lovers coexist.',
    heroDescription: 'Puri\'s sacred geography is unique — the Jagannath Temple\'s flag is always visible from the sea, and the beach stretches unbroken for miles. The Rath Yatra draws a million devotees.',
    stats: { bestTime: 'Oct – Feb', budget: '$12–$40/day', language: 'Odia, Hindi', currency: 'INR (Rupee)' },
    vibes: ['Spiritual', 'Beach', 'Cultural'],
    gradient: 'from-orange-900 to-amber-900', accentColor: '#EA580C',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Jagannath Temple & Grand Road', emoji: '🛕', accentColor: '#EA580C',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Holiest dham of Odisha', spots: [
          { name: 'Jagannath Temple (non-Hindus from rooftop only)', tag: 'Sacred' },
          { name: 'Grand Road (Rath Yatra route)', tag: 'Pilgrimage' },
          { name: 'Matha (monastery) complexes', tag: 'Culture' },
          { name: 'Mahaprasad (temple food)', tag: 'Unique' },
        ]},
      { name: 'Puri Beach', emoji: '🏖️', accentColor: '#F59E0B',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Long golden coast', spots: [
          { name: 'Puri Beach sunrise', tag: 'Beautiful' },
          { name: 'Swargadwar cremation ghat', tag: 'Sacred' },
          { name: 'Chilika Lake day trip (largest lagoon)', tag: 'Nature' },
          { name: 'Konark Sun Temple (35km)', tag: 'UNESCO' },
        ]},
      { name: 'Pipili & Raghurajpur', emoji: '🎨', accentColor: '#7C3AED',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Odisha\'s craft villages', spots: [
          { name: 'Pipili appliqué craft village', tag: 'Handicrafts' },
          { name: 'Raghurajpur artists\' village', tag: 'Pattachitra' },
          { name: 'Bhubaneswar temple trail (60km)', tag: 'Day trip' },
          { name: 'Odisha State Museum', tag: 'Culture' },
        ]},
    ],
  },

  {
    slug: 'coorg', name: 'Coorg (Kodagu)', state: 'Karnataka',
    country: 'India', flag: '🇮🇳', tagline: 'Scotland of India',
    description: 'A mist-covered district of coffee and cardamom estates, sacred rivers, ancient Kodava warrior culture, and the most pristine forest landscape in South India.',
    heroDescription: 'The Kodava people — India\'s only warrior community allowed to carry firearms — have maintained a unique culture amid estates that produce 30% of India\'s coffee. Coorg is unlike any other India.',
    stats: { bestTime: 'Oct – Apr', budget: '$20–$80/day', language: 'Kodava, Kannada', currency: 'INR (Rupee)' },
    vibes: ['Nature', 'Wellness', 'Adventure'],
    gradient: 'from-green-900 to-emerald-900', accentColor: '#166534',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Madikeri & Coffee Estates', emoji: '☕', accentColor: '#166534',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        tagline: 'Coffee, cardamom & misty hills', spots: [
          { name: 'Coffee estate plantation stay', tag: 'Must-do' },
          { name: 'Madikeri Fort', tag: 'Historic' },
          { name: 'Raja\'s Seat sunset viewpoint', tag: 'Views' },
          { name: 'Omkareshwara Temple', tag: 'Sacred' },
        ]},
      { name: 'Waterfalls & Nature', emoji: '💧', accentColor: '#059669',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        tagline: 'Jungle & cascading falls', spots: [
          { name: 'Abbey Falls', tag: 'Most visited' },
          { name: 'Iruppu Falls trek', tag: 'Remote' },
          { name: 'Nagarhole National Park', tag: 'Tigers' },
          { name: 'Nisargadhama river island', tag: 'Nature' },
        ]},
      { name: 'Talacauvery & Brahmagiri', emoji: '🏔️', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        tagline: 'Sacred source of Cauvery', spots: [
          { name: 'Talacauvery (Cauvery source)', tag: 'Sacred' },
          { name: 'Brahmagiri peak trek', tag: 'Adventure' },
          { name: 'Bylakuppe Tibetan settlement', tag: 'Unique' },
          { name: 'Dubare elephant camp', tag: 'Elephants' },
        ]},
    ],
  },

  // ── BATCH 2 ──────────────────────────────────────────────────

  {
    slug: 'gulmarg', name: 'Gulmarg', state: 'Jammu & Kashmir',
    country: 'India', flag: '🇮🇳', tagline: 'Meadow of Flowers',
    description: 'India\'s premier ski resort sits at 2,650m — world\'s highest cable car, powder snow from December to March, and wildflower meadows the rest of the year.',
    heroDescription: 'The Gondola cable car rises to 3,979m over a sea of snow-capped Himalayan peaks. In winter it\'s skiing paradise; in summer it\'s a meadow of wildflowers with Nanga Parbat as backdrop.',
    stats: { bestTime: 'Dec – Mar (ski) · May – Sep (summer)', budget: '$20–$80/day', language: 'Kashmiri, Urdu, Hindi', currency: 'INR (Rupee)' },
    vibes: ['Adventure', 'Nature', 'Romantic'],
    gradient: 'from-blue-900 to-slate-800', accentColor: '#0891B2',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Gondola & Ski Slopes', emoji: '🚡', accentColor: '#0891B2',
        image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80',
        tagline: 'World\'s highest cable car', spots: [
          { name: 'Gulmarg Gondola Phase 1 (2,650m)', tag: 'Must-ride' },
          { name: 'Gondola Phase 2 (3,979m)', tag: 'Highest point' },
          { name: 'Ski slopes (Dec–Mar)', tag: 'Skiing' },
          { name: 'Apharwat Peak panorama', tag: 'Views' },
        ]},
      { name: 'Gulmarg Village', emoji: '🌸', accentColor: '#7C3AED',
        image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80',
        tagline: 'Meadows & historic church', spots: [
          { name: 'St Mary\'s Church (1895)', tag: 'Colonial' },
          { name: 'Maharani Temple', tag: 'Sacred' },
          { name: 'Golf Course (highest in world)', tag: 'Unique' },
          { name: 'Strawberry fields (summer)', tag: 'Seasonal' },
        ]},
      { name: 'Khilanmarg & Alpather', emoji: '🏔️', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80',
        tagline: 'Treks & frozen lakes', spots: [
          { name: 'Khilanmarg meadow trek (5km)', tag: 'Day trek' },
          { name: 'Alpather Lake (frozen in winter)', tag: 'Beautiful' },
          { name: 'Ningle Nallah stream', tag: 'Picnic' },
          { name: 'Ferozepur Nallah', tag: 'Nature' },
        ]},
    ],
  },

  {
    slug: 'kasol', name: 'Kasol', state: 'Himachal Pradesh',
    country: 'India', flag: '🇮🇳', tagline: 'Mini Israel of India',
    description: 'A tiny village in the Parvati Valley beloved by backpackers — Israeli cafes, Parvati River, Kheerganga hot springs trek, and the most laid-back vibe in the Himalayas.',
    heroDescription: 'Hebrew menus, hammocks over the Parvati River, and pine forests stretching to snow peaks — Kasol became the go-to Himalayan escape for budget travellers and trekkers worldwide.',
    stats: { bestTime: 'Mar – Jun · Sep – Nov', budget: '$8–$30/day', language: 'Hindi, Pahadi, Hebrew', currency: 'INR (Rupee)' },
    vibes: ['Adventure', 'Bohemian', 'Nature'],
    gradient: 'from-green-900 to-teal-900', accentColor: '#059669',
    image: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Kasol Village', emoji: '🏕️', accentColor: '#059669',
        image: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=600&q=80',
        tagline: 'Riverside cafes & chill vibes', spots: [
          { name: 'Parvati River banks', tag: 'Hangout' },
          { name: 'Israeli bakeries & cafes', tag: 'Famous' },
          { name: 'Chalal village walk (2km)', tag: 'Short trek' },
          { name: 'Night sky stargazing', tag: 'Magical' },
        ]},
      { name: 'Kheerganga Trek', emoji: '♨️', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=600&q=80',
        tagline: 'Hot springs at 2,950m', spots: [
          { name: 'Kheerganga hot spring pool', tag: 'Must-do' },
          { name: 'Shiva temple at summit', tag: 'Sacred' },
          { name: 'Forest trail (12km one way)', tag: 'Trek' },
          { name: 'Overnight camping', tag: 'Stay' },
        ]},
      { name: 'Tosh & Pulga', emoji: '🌿', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=600&q=80',
        tagline: 'Remote Parvati Valley villages', spots: [
          { name: 'Tosh village viewpoint', tag: 'Stunning views' },
          { name: 'Pulga hidden village', tag: 'Offbeat' },
          { name: 'Pin Parvati Pass base', tag: 'Advanced trek' },
          { name: 'Manikaran Sahib Gurudwara (18km)', tag: 'Sacred hot springs' },
        ]},
    ],
  },

  {
    slug: 'spiti', name: 'Spiti Valley', state: 'Himachal Pradesh',
    country: 'India', flag: '🇮🇳', tagline: 'Middle Land Between Tibet & India',
    description: 'A high-altitude cold desert at 3,800m — ancient Buddhist monasteries perched on cliffs, fossil-filled riverbeds, and moonscapes that look nothing like the rest of India.',
    heroDescription: 'Only accessible June to October, Spiti is one of India\'s most extreme and beautiful landscapes — Key Monastery at 4,166m, the fossilised sea bed at Langza, and zero light pollution nights.',
    stats: { bestTime: 'Jun – Oct only', budget: '$15–$50/day', language: 'Spitian, Hindi, Tibetan', currency: 'INR (Rupee)' },
    vibes: ['Adventure', 'Spiritual', 'Nature'],
    gradient: 'from-amber-900 to-stone-900', accentColor: '#D97706',
    image: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Kaza & Key Monastery', emoji: '🛕', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=600&q=80',
        tagline: 'Valley capital & famous monastery', spots: [
          { name: 'Key Monastery (4,166m)', tag: 'Iconic' },
          { name: 'Kaza village & market', tag: 'Base' },
          { name: 'Kibber village (4,200m)', tag: 'High altitude' },
          { name: 'Chicham Bridge (Asia\'s highest)', tag: 'Engineering' },
        ]},
      { name: 'Langza & Komic', emoji: '🦕', accentColor: '#92400E',
        image: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=600&q=80',
        tagline: 'Fossils & Buddha statues', spots: [
          { name: 'Langza fossil village (sea bed)', tag: 'Unique' },
          { name: 'Giant Buddha statue at Langza', tag: 'Beautiful' },
          { name: 'Komic (world\'s highest motorable village)', tag: 'Record' },
          { name: 'Hikkim Post Office (world\'s highest)', tag: 'Novelty' },
        ]},
      { name: 'Chandratal & Kunzum', emoji: '💎', accentColor: '#0891B2',
        image: 'https://images.unsplash.com/photo-1617859047452-8510bcf207fd?auto=format&fit=crop&w=600&q=80',
        tagline: 'Moon Lake & high passes', spots: [
          { name: 'Chandratal Lake (Moon Lake)', tag: 'Most beautiful' },
          { name: 'Kunzum Pass (4,590m)', tag: 'High pass' },
          { name: 'Losar border village', tag: 'Remote' },
          { name: 'Dhankar Monastery & lake', tag: 'Hidden gem' },
        ]},
    ],
  },

  {
    slug: 'mussoorie', name: 'Mussoorie', state: 'Uttarakhand',
    country: 'India', flag: '🇮🇳', tagline: 'Queen of Hill Stations',
    description: 'The most visited hill station in India — a colonial-era Himalayan resort town with panoramic views of the Doon Valley, Kempty Falls, and the charming Landour cantonment.',
    heroDescription: 'Ruskin Bond still lives in Landour, the old cantonment above Mussoorie. The Mall Road, Christ Church, and views over Dehradun have drawn visitors since the British era.',
    stats: { bestTime: 'Mar – Jun · Sep – Nov', budget: '$15–$55/day', language: 'Hindi, Garhwali', currency: 'INR (Rupee)' },
    vibes: ['Romantic', 'Nature', 'Cultural'],
    gradient: 'from-green-900 to-emerald-800', accentColor: '#059669',
    image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Mall Road & Library Bazaar', emoji: '🛍️', accentColor: '#059669',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Colonial promenade & shops', spots: [
          { name: 'Mall Road evening walk', tag: 'Classic' },
          { name: 'Christ Church (1836)', tag: 'Colonial' },
          { name: 'Gun Hill cable car', tag: 'Views' },
          { name: 'Library Chowk food stalls', tag: 'Street food' },
        ]},
      { name: 'Landour', emoji: '📚', accentColor: '#166534',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Ruskin Bond\'s village & bakeries', spots: [
          { name: 'Landour cantonment lanes', tag: 'Charming' },
          { name: 'Char Dukan (four shops) bakery', tag: 'Institution' },
          { name: 'Lal Tibba highest point', tag: 'Best views' },
          { name: 'Sisters Bazaar', tag: 'Heritage' },
        ]},
      { name: 'Kempty Falls & Surrounds', emoji: '💧', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Waterfalls & viewpoints', spots: [
          { name: 'Kempty Falls (15km)', tag: 'Most visited' },
          { name: 'George Everest peak', tag: 'Historical' },
          { name: 'Doon Valley sunset views', tag: 'Panorama' },
          { name: 'Mussoorie Lake', tag: 'Boating' },
        ]},
    ],
  },

  {
    slug: 'haridwar', name: 'Haridwar', state: 'Uttarakhand',
    country: 'India', flag: '🇮🇳', tagline: 'Gateway to the Gods',
    description: 'Where the Ganges descends from the Himalayas to the plains — one of India\'s seven holiest cities, home to the Har Ki Pauri Ganga Aarti and the Kumbh Mela.',
    heroDescription: 'Every evening at dusk, thousands of diyas (oil lamps) are floated on the Ganges at Har Ki Pauri as priests perform the most atmospheric fire ceremony in India.',
    stats: { bestTime: 'Sep – Apr', budget: '$10–$35/day', language: 'Hindi, Sanskrit', currency: 'INR (Rupee)' },
    vibes: ['Spiritual', 'Cultural', 'Adventure'],
    gradient: 'from-orange-900 to-amber-900', accentColor: '#EA580C',
    image: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Har Ki Pauri', emoji: '🔥', accentColor: '#EA580C',
        image: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=600&q=80',
        tagline: 'Most sacred ghat in Haridwar', spots: [
          { name: 'Ganga Aarti (6pm daily)', tag: 'Must-see' },
          { name: 'Brahma Kund sacred bathing', tag: 'Pilgrimage' },
          { name: 'Upper Ganga Canal viewpoint', tag: 'Scenic' },
          { name: 'Astrologers & priests at ghats', tag: 'Cultural' },
        ]},
      { name: 'Temples & Ashrams', emoji: '🛕', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=600&q=80',
        tagline: 'Spiritual heart of the city', spots: [
          { name: 'Mansa Devi Temple (cable car)', tag: 'Hilltop' },
          { name: 'Chandi Devi Temple', tag: 'Sacred' },
          { name: 'Shantikunj Ashram', tag: 'Meditation' },
          { name: 'Patanjali Yogpeeth', tag: 'Yoga' },
        ]},
      { name: 'Rajaji National Park', emoji: '🐘', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=600&q=80',
        tagline: 'Wildlife at the Himalayan foothills', spots: [
          { name: 'Rajaji Tiger Reserve jeep safari', tag: 'Wildlife' },
          { name: 'Elephants & tigers sighting', tag: 'Adventure' },
          { name: 'Chilla range', tag: 'Forest' },
          { name: 'Rishikesh (24km, day trip)', tag: 'Rafting' },
        ]},
    ],
  },

  {
    slug: 'jim-corbett', name: 'Jim Corbett', state: 'Uttarakhand',
    country: 'India', flag: '🇮🇳', tagline: 'India\'s Oldest National Park',
    description: 'Established in 1936, Jim Corbett is India\'s oldest and most prestigious national park — the best place to spot Bengal tigers in their natural habitat.',
    heroDescription: 'The Ramganga river winds through sal forests, grasslands, and rocky ridges. Corbett has the highest tiger density of any park in India — and the most atmospheric jungle lodges.',
    stats: { bestTime: 'Nov – Jun', budget: '$25–$150/day', language: 'Hindi, Garhwali', currency: 'INR (Rupee)' },
    vibes: ['Adventure', 'Nature', 'Wildlife'],
    gradient: 'from-green-900 to-stone-800', accentColor: '#166534',
    image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Dhikala Zone', emoji: '🐅', accentColor: '#166534',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Best tiger sighting zone', spots: [
          { name: 'Dhikala jeep & canter safari', tag: 'Best zone' },
          { name: 'Ramganga Reservoir viewpoint', tag: 'Scenic' },
          { name: 'Chaur grasslands elephant herds', tag: 'Wildlife' },
          { name: 'Overnight forest rest house', tag: 'Unique stay' },
        ]},
      { name: 'Bijrani & Jhirna', emoji: '🦅', accentColor: '#059669',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Year-round accessible zones', spots: [
          { name: 'Bijrani zone jeep safari', tag: 'Day visit' },
          { name: 'Jhirna (open all year)', tag: 'Always open' },
          { name: 'Sitabani buffer zone', tag: 'Walking allowed' },
          { name: 'Corbett Museum, Kaladhungi', tag: 'History' },
        ]},
      { name: 'Ramnagar & Resorts', emoji: '🏕️', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1626015365107-b35bfd13e7ae?auto=format&fit=crop&w=600&q=80',
        tagline: 'Base town & jungle lodges', spots: [
          { name: 'Luxury jungle resorts by Ramganga', tag: 'Stay' },
          { name: 'Bird watching (600+ species)', tag: 'Birdwatching' },
          { name: 'White water rafting Kosi river', tag: 'Adventure' },
          { name: 'Corbett Waterfall', tag: 'Nature' },
        ]},
    ],
  },

  {
    slug: 'bikaner', name: 'Bikaner', state: 'Rajasthan',
    country: 'India', flag: '🇮🇳', tagline: 'Camel Country & Forts',
    description: 'A walled desert city famous for its massive Junagarh Fort, the extraordinary Karni Mata Rat Temple, Bikaneri bhujia snacks, and the finest camel breeding traditions in Rajasthan.',
    heroDescription: 'Bikaner sits deeper in the Thar than Jaisalmer and feels more authentic — the Junagarh Fort has never been conquered, and the Karni Mata temple\'s 20,000 sacred rats are genuinely unlike anything else in India.',
    stats: { bestTime: 'Oct – Feb', budget: '$12–$45/day', language: 'Hindi, Rajasthani', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Historical', 'Adventure'],
    gradient: 'from-amber-900 to-red-900', accentColor: '#B45309',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Junagarh Fort', emoji: '🏯', accentColor: '#B45309',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'Unconquered fort since 1478', spots: [
          { name: 'Junagarh Fort & palace complex', tag: 'Must-see' },
          { name: 'Anup Mahal (gilded chambers)', tag: 'Exquisite' },
          { name: 'Laxmi Niwas Palace hotel', tag: 'Heritage stay' },
          { name: 'Old City havelis walk', tag: 'Architecture' },
        ]},
      { name: 'Karni Mata & Temples', emoji: '🐀', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'Rat temple & desert shrines', spots: [
          { name: 'Karni Mata Rat Temple (30km)', tag: 'Bizarre & sacred' },
          { name: 'Bhandasar Jain Temple', tag: 'Architecture' },
          { name: 'Lalgarh Palace & Museum', tag: 'Heritage' },
          { name: 'Sadul Museum', tag: 'History' },
        ]},
      { name: 'Camel Research & Desert', emoji: '🐪', accentColor: '#92400E',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'Camel safaris & research', spots: [
          { name: 'National Camel Research Centre', tag: 'Unique' },
          { name: 'Camel safari in Thar Desert', tag: 'Adventure' },
          { name: 'Bikaneri bhujia & sweets', tag: 'Food' },
          { name: 'Gajner Palace Lake (30km)', tag: 'Wildlife' },
        ]},
    ],
  },

  {
    slug: 'madurai', name: 'Madurai', state: 'Tamil Nadu',
    country: 'India', flag: '🇮🇳', tagline: 'City of Temples',
    description: 'One of the oldest continuously inhabited cities in the world — the Meenakshi Amman Temple\'s towering gopurams, jasmine flowers everywhere, and a street food culture that rivals Chennai.',
    heroDescription: 'The Meenakshi Temple is one of India\'s most extraordinary monuments — 14 gateway towers covered in thousands of painted sculptures, active since the 6th century BC.',
    stats: { bestTime: 'Oct – Mar', budget: '$12–$45/day', language: 'Tamil', currency: 'INR (Rupee)' },
    vibes: ['Spiritual', 'Cultural', 'Foodie'],
    gradient: 'from-red-900 to-amber-900', accentColor: '#DC2626',
    image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Meenakshi Temple & Old City', emoji: '🛕', accentColor: '#DC2626',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'Ancient temple city heart', spots: [
          { name: 'Meenakshi Amman Temple', tag: 'Must-see' },
          { name: 'Hall of 1,000 Pillars', tag: 'Architecture' },
          { name: 'Evening temple ceremony (9pm)', tag: 'Sacred ritual' },
          { name: 'East Masi Street flower market', tag: 'Fragrant' },
        ]},
      { name: 'Gandhi Museum & Markets', emoji: '🧵', accentColor: '#B91C1C',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'History & handicrafts', spots: [
          { name: 'Gandhi Memorial Museum', tag: 'Moving' },
          { name: 'Pudhu Mandapam market', tag: 'Textiles' },
          { name: 'Thirumalai Nayakkar Mahal palace', tag: 'Historical' },
          { name: 'Kothari Market', tag: 'Shopping' },
        ]},
      { name: 'Food & Surrounds', emoji: '🍛', accentColor: '#F97316',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'South Indian food & day trips', spots: [
          { name: 'Murugan Idli Shop (legendary)', tag: 'Must-eat' },
          { name: 'Jigarthanda (local cold drink)', tag: 'Unique' },
          { name: 'Rameshwaram day trip (175km)', tag: 'Pilgrimage' },
          { name: 'Kodaikanal hill station (120km)', tag: 'Day trip' },
        ]},
    ],
  },

  {
    slug: 'ooty', name: 'Ooty (Udhagamandalam)', state: 'Tamil Nadu',
    country: 'India', flag: '🇮🇳', tagline: 'Queen of Hill Stations',
    description: 'The crown jewel of the Nilgiri Hills — a UNESCO Biosphere with tea estates, the famous Toy Train, Botanical Gardens, and the most pleasant climate in South India.',
    heroDescription: 'The Nilgiri Mountain Railway toy train chugs through tunnels of eucalyptus and tea at 2,240m altitude. Ooty\'s British-era clubs, lake, and rose gardens still feel like a different era.',
    stats: { bestTime: 'Apr – Jun · Sep – Nov', budget: '$15–$55/day', language: 'Tamil, Badaga, Kannada', currency: 'INR (Rupee)' },
    vibes: ['Nature', 'Romantic', 'Wellness'],
    gradient: 'from-green-900 to-teal-900', accentColor: '#0D9488',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Toy Train & Gardens', emoji: '🚂', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        tagline: 'UNESCO railway & botanical gardens', spots: [
          { name: 'Nilgiri Mountain Railway (UNESCO)', tag: 'Must-ride' },
          { name: 'Government Botanical Gardens', tag: 'Beautiful' },
          { name: 'Ooty Lake boating', tag: 'Classic' },
          { name: 'Rose Garden (2,000+ varieties)', tag: 'Fragrant' },
        ]},
      { name: 'Tea Estates & Viewpoints', emoji: '🍵', accentColor: '#166534',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        tagline: 'Nilgiri tea & panoramic views', spots: [
          { name: 'Tea factory tours', tag: 'Nilgiri tea' },
          { name: 'Doddabetta Peak (2,637m)', tag: 'Highest point' },
          { name: 'Lamb\'s Rock viewpoint', tag: 'Views' },
          { name: 'Wenlock Downs grasslands', tag: 'Scenic' },
        ]},
      { name: 'Coonoor & Mudumalai', emoji: '🌿', accentColor: '#059669',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        tagline: 'Quieter Nilgiris & wildlife', spots: [
          { name: 'Coonoor (16km, quieter)', tag: 'Charming' },
          { name: 'Sim\'s Park Coonoor', tag: 'Garden' },
          { name: 'Mudumalai Tiger Reserve', tag: 'Wildlife' },
          { name: 'Tribal villages & culture', tag: 'Authentic' },
        ]},
    ],
  },

  {
    slug: 'mahabalipuram', name: 'Mahabalipuram', state: 'Tamil Nadu',
    country: 'India', flag: '🇮🇳', tagline: 'Shore Temple & Ancient Sculpted Rocks',
    description: 'A UNESCO World Heritage coastal town 60km from Chennai — 7th-century rock-cut temples, the Shore Temple above the Bay of Bengal, and one of India\'s best surf beaches.',
    heroDescription: 'The Pallava kings carved entire temples from single boulders here in the 7th century. Krishna\'s Butter Ball (a 250-tonne rock balanced impossibly) and the Shore Temple at sunrise are extraordinary.',
    stats: { bestTime: 'Nov – Feb', budget: '$15–$55/day', language: 'Tamil, English', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Historical', 'Beach'],
    gradient: 'from-blue-900 to-teal-900', accentColor: '#0891B2',
    image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Shore Temple & Rock Carvings', emoji: '🏛️', accentColor: '#0891B2',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'UNESCO Pallava monuments', spots: [
          { name: 'Shore Temple (UNESCO, 7th century)', tag: 'Iconic' },
          { name: 'Arjuna\'s Penance (world\'s largest bas-relief)', tag: 'Must-see' },
          { name: 'Krishna\'s Butter Ball (250-tonne balancing rock)', tag: 'Unique' },
          { name: 'Five Rathas (monolithic temples)', tag: 'UNESCO' },
        ]},
      { name: 'Beach & Surf', emoji: '🏄', accentColor: '#14B8A6',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'Bay of Bengal coast', spots: [
          { name: 'Mahabalipuram Beach', tag: 'Beach' },
          { name: 'Surf lessons at surf schools', tag: 'Surfing' },
          { name: 'Tiger Cave rock temple (5km)', tag: 'Hidden gem' },
          { name: 'Crocodile Bank (14km)', tag: 'Wildlife' },
        ]},
      { name: 'Craft Villages', emoji: '🗿', accentColor: '#7C3AED',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: '1,300-year tradition of stone carving', spots: [
          { name: 'Stone carving workshops', tag: 'Craft' },
          { name: 'Government Sculpture Museum', tag: 'Museum' },
          { name: 'Kanchipuram silk town (65km)', tag: 'Silk' },
          { name: 'Vedanthangal Bird Sanctuary (50km)', tag: 'Nature' },
        ]},
    ],
  },

  // ── BATCH 3 ──────────────────────────────────────────────────

  {
    slug: 'ranthambore', name: 'Ranthambore', state: 'Rajasthan',
    country: 'India', flag: '🇮🇳', tagline: 'Tiger Fort of Rajasthan',
    description: 'A former royal hunting ground turned legendary tiger reserve — ruined forts, lakes, dry forests, and some of India\'s most reliable Bengal tiger sightings.',
    heroDescription: 'Ranthambore is where wild tigers walk below a 10th-century hill fort. The landscape feels cinematic: stone ruins, banyan roots, lakes full of crocodiles, and striped cats moving through golden grass.',
    stats: { bestTime: 'Oct – Jun', budget: '$25–$180/day', language: 'Hindi, Rajasthani', currency: 'INR (Rupee)' },
    vibes: ['Wildlife', 'Adventure', 'Historical'],
    gradient: 'from-orange-900 to-stone-900', accentColor: '#C2410C',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d040a94?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1549366021-9f761d040a94?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Tiger Safari Zones', emoji: '🐅', accentColor: '#C2410C',
        image: 'https://images.unsplash.com/photo-1549366021-9f761d040a94?auto=format&fit=crop&w=600&q=80',
        tagline: 'Jeep and canter safaris', spots: [
          { name: 'Zones 1–5 core tiger habitat', tag: 'Best sightings' },
          { name: 'Padam Talao lake', tag: 'Classic view' },
          { name: 'Rajbagh ruins', tag: 'Wild scenery' },
          { name: 'Malik Talao birdlife', tag: 'Birdwatching' },
        ]},
      { name: 'Ranthambore Fort', emoji: '🏯', accentColor: '#B45309',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        tagline: 'UNESCO hill fort above the park', spots: [
          { name: 'Ranthambore Fort climb', tag: 'UNESCO' },
          { name: 'Trinetra Ganesh Temple', tag: 'Pilgrimage' },
          { name: 'Fort ramparts tiger views', tag: 'Panorama' },
          { name: 'Ancient stepwells and gates', tag: 'History' },
        ]},
      { name: 'Sawai Madhopur', emoji: '🏕️', accentColor: '#166534',
        image: 'https://images.unsplash.com/photo-1549366021-9f761d040a94?auto=format&fit=crop&w=600&q=80',
        tagline: 'Safari base and craft villages', spots: [
          { name: 'Dastkar Ranthambore crafts', tag: 'Shopping' },
          { name: 'Jungle lodges on Ranthambore Road', tag: 'Stay' },
          { name: 'Surwal Lake winter birds', tag: 'Seasonal' },
          { name: 'Kachida Valley leopards', tag: 'Wildlife' },
        ]},
    ],
  },

  {
    slug: 'gokarna', name: 'Gokarna', state: 'Karnataka',
    country: 'India', flag: '🇮🇳', tagline: 'Temple Town with Secret Beaches',
    description: 'A quieter alternative to Goa where sacred temples meet crescent beaches — Om Beach, Kudle, cliff walks, beach shacks, and a barefoot backpacker rhythm.',
    heroDescription: 'Gokarna begins as a Shiva pilgrimage town and ends in a chain of hidden beaches. Walk the headlands at sunset and the Arabian Sea opens into one perfect cove after another.',
    stats: { bestTime: 'Oct – Mar', budget: '$10–$45/day', language: 'Kannada, Hindi, English', currency: 'INR (Rupee)' },
    vibes: ['Beach', 'Spiritual', 'Bohemian'],
    gradient: 'from-cyan-900 to-orange-900', accentColor: '#0891B2',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Om Beach & Kudle', emoji: '🏖️', accentColor: '#0891B2',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        tagline: 'Classic Gokarna beach life', spots: [
          { name: 'Om Beach viewpoint', tag: 'Iconic' },
          { name: 'Kudle Beach sunset', tag: 'Relax' },
          { name: 'Beach shacks and cafes', tag: 'Food' },
          { name: 'Kayaking around Om Beach', tag: 'Adventure' },
        ]},
      { name: 'Half Moon & Paradise', emoji: '🌙', accentColor: '#14B8A6',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
        tagline: 'Cliff trails and secluded coves', spots: [
          { name: 'Half Moon Beach trek', tag: 'Short hike' },
          { name: 'Paradise Beach boat ride', tag: 'Hidden' },
          { name: 'Coastal cliff trail', tag: 'Views' },
          { name: 'Sunrise swim in quiet coves', tag: 'Peaceful' },
        ]},
      { name: 'Temple Town', emoji: '🛕', accentColor: '#EA580C',
        image: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=600&q=80',
        tagline: 'Pilgrimage lanes and local life', spots: [
          { name: 'Mahabaleshwar Temple', tag: 'Sacred' },
          { name: 'Main Beach pilgrimage rituals', tag: 'Cultural' },
          { name: 'Kotitirtha holy tank', tag: 'Historic' },
          { name: 'Mirjan Fort day trip', tag: 'Heritage' },
        ]},
    ],
  },

  {
    slug: 'thekkady', name: 'Thekkady', state: 'Kerala',
    country: 'India', flag: '🇮🇳', tagline: 'Periyar Spice Country',
    description: 'Kerala\'s mountain wildlife gateway — Periyar Tiger Reserve, spice plantations, bamboo rafting, elephant country, and cool cardamom-scented air.',
    heroDescription: 'Mist hangs over Periyar Lake while sambar deer graze on the banks and hornbills cross the canopy. Thekkady is Kerala at its greenest: jungle, spice gardens, and slow mountain mornings.',
    stats: { bestTime: 'Oct – Mar', budget: '$18–$90/day', language: 'Malayalam, Tamil, English', currency: 'INR (Rupee)' },
    vibes: ['Nature', 'Wildlife', 'Wellness'],
    gradient: 'from-green-900 to-lime-900', accentColor: '#15803D',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Periyar Reserve', emoji: '🐘', accentColor: '#15803D',
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=600&q=80',
        tagline: 'Lake safaris and forest trails', spots: [
          { name: 'Periyar Lake boat safari', tag: 'Classic' },
          { name: 'Bamboo rafting programme', tag: 'Adventure' },
          { name: 'Nature walk with forest guides', tag: 'Wildlife' },
          { name: 'Border hiking full-day trek', tag: 'Active' },
        ]},
      { name: 'Kumily Spice Belt', emoji: '🌶️', accentColor: '#65A30D',
        image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
        tagline: 'Cardamom, pepper and tea', spots: [
          { name: 'Spice plantation tour', tag: 'Must-do' },
          { name: 'Cardamom hills viewpoints', tag: 'Scenic' },
          { name: 'Local spice markets', tag: 'Shopping' },
          { name: 'Tea estates near Vandiperiyar', tag: 'Day trip' },
        ]},
      { name: 'Culture & Ayurveda', emoji: '🥥', accentColor: '#0D9488',
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=600&q=80',
        tagline: 'Kerala performances and wellness', spots: [
          { name: 'Kalaripayattu martial arts show', tag: 'Performance' },
          { name: 'Kathakali evening theatre', tag: 'Culture' },
          { name: 'Ayurvedic massage centres', tag: 'Wellness' },
          { name: 'Elephant Junction experiences', tag: 'Family' },
        ]},
    ],
  },

  {
    slug: 'varkala', name: 'Varkala', state: 'Kerala',
    country: 'India', flag: '🇮🇳', tagline: 'Clifftop Beach Escape',
    description: 'Kerala\'s most dramatic beach town — red laterite cliffs, Arabian Sea sunsets, yoga studios, surf lessons, seafood cafes, and the sacred Janardhana Swamy Temple.',
    heroDescription: 'Varkala is all cliff edge and sea breeze. Cafes balance above the waves, mineral springs trickle down rust-red rock, and every evening ends with the sun dissolving into the Arabian Sea.',
    stats: { bestTime: 'Nov – Mar', budget: '$12–$60/day', language: 'Malayalam, English', currency: 'INR (Rupee)' },
    vibes: ['Beach', 'Wellness', 'Bohemian'],
    gradient: 'from-sky-900 to-rose-900', accentColor: '#0EA5E9',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'North Cliff', emoji: '🌅', accentColor: '#0EA5E9',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        tagline: 'Cafes, yoga and sunset walks', spots: [
          { name: 'North Cliff promenade', tag: 'Main strip' },
          { name: 'Papanasam Beach', tag: 'Sacred beach' },
          { name: 'Cliff sunset cafes', tag: 'Views' },
          { name: 'Yoga and Ayurveda studios', tag: 'Wellness' },
        ]},
      { name: 'Edava & Kappil', emoji: '🌊', accentColor: '#14B8A6',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
        tagline: 'Quiet beaches and backwaters', spots: [
          { name: 'Kappil Beach and lake', tag: 'Scenic' },
          { name: 'Edava Beach', tag: 'Quiet' },
          { name: 'Backwater kayaking', tag: 'Adventure' },
          { name: 'Odayam Beach stays', tag: 'Relaxed' },
        ]},
      { name: 'Temple & Local Town', emoji: '🛕', accentColor: '#EA580C',
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=600&q=80',
        tagline: 'Pilgrimage and Kerala life', spots: [
          { name: 'Janardhana Swamy Temple', tag: 'Ancient' },
          { name: 'Sivagiri Mutt', tag: 'Spiritual' },
          { name: 'Varkala Aquarium', tag: 'Family' },
          { name: 'Local seafood restaurants', tag: 'Food' },
        ]},
    ],
  },

  {
    slug: 'pune', name: 'Pune', state: 'Maharashtra',
    country: 'India', flag: '🇮🇳', tagline: 'Culture, Campuses & Cafes',
    description: 'A youthful Deccan city of universities, forts, bakeries, music, Maratha history, and weekend escapes to the Sahyadri hills.',
    heroDescription: 'Pune moves at a gentler rhythm than Mumbai but has just as much personality: Peshwa palaces, leafy campuses, Irani cafes, craft beer, and hill forts waiting beyond the city.',
    stats: { bestTime: 'Oct – Feb', budget: '$18–$70/day', language: 'Marathi, Hindi, English', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Foodie', 'Urban'],
    gradient: 'from-indigo-900 to-rose-900', accentColor: '#4F46E5',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Old Pune', emoji: '🏛️', accentColor: '#4F46E5',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Peshwa history and markets', spots: [
          { name: 'Shaniwar Wada palace fort', tag: 'Historic' },
          { name: 'Dagdusheth Halwai Ganpati', tag: 'Sacred' },
          { name: 'Tulshibaug market', tag: 'Shopping' },
          { name: 'Raja Dinkar Kelkar Museum', tag: 'Culture' },
        ]},
      { name: 'Koregaon Park & Camp', emoji: '☕', accentColor: '#BE123C',
        image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80',
        tagline: 'Cafes, bakeries and nightlife', spots: [
          { name: 'German Bakery and cafe lanes', tag: 'Food' },
          { name: 'Osho Teerth Park', tag: 'Green space' },
          { name: 'MG Road in Camp', tag: 'Shopping' },
          { name: 'Kayani Bakery shrewsbury biscuits', tag: 'Institution' },
        ]},
      { name: 'Sahyadri Escapes', emoji: '⛰️', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
        tagline: 'Hill forts and monsoon treks', spots: [
          { name: 'Sinhagad Fort', tag: 'Weekend trek' },
          { name: 'Lonavala and Khandala', tag: 'Day trip' },
          { name: 'Lavasa lakeside drive', tag: 'Scenic' },
          { name: 'Mulshi Dam backwaters', tag: 'Nature' },
        ]},
    ],
  },

  {
    slug: 'aurangabad', name: 'Aurangabad', state: 'Maharashtra',
    country: 'India', flag: '🇮🇳', tagline: 'Gateway to Ajanta & Ellora',
    description: 'A historic Deccan base for two of India\'s greatest UNESCO sites — Ellora\'s rock-cut temples, Ajanta\'s painted caves, Daulatabad Fort, and Mughal-era monuments.',
    heroDescription: 'Ellora\'s Kailasa Temple was carved downward from a single mountain of basalt. Ajanta hides 2,000-year-old Buddhist murals in a horseshoe gorge. Aurangabad is the doorway to both.',
    stats: { bestTime: 'Oct – Mar', budget: '$15–$60/day', language: 'Marathi, Hindi, Urdu', currency: 'INR (Rupee)' },
    vibes: ['Historical', 'Cultural', 'Spiritual'],
    gradient: 'from-stone-900 to-amber-900', accentColor: '#B45309',
    image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Ellora & Daulatabad', emoji: '🏛️', accentColor: '#B45309',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'Rock-cut temples and hill forts', spots: [
          { name: 'Ellora Caves (UNESCO)', tag: 'Must-see' },
          { name: 'Kailasa Temple', tag: 'Masterpiece' },
          { name: 'Daulatabad Fort climb', tag: 'Adventure' },
          { name: 'Grishneshwar Jyotirlinga Temple', tag: 'Sacred' },
        ]},
      { name: 'Ajanta Caves', emoji: '🎨', accentColor: '#7C2D12',
        image: 'https://images.unsplash.com/photo-1585468274952-66591eb14165?auto=format&fit=crop&w=600&q=80',
        tagline: 'Ancient Buddhist murals', spots: [
          { name: 'Ajanta Caves (UNESCO)', tag: 'Day trip' },
          { name: 'Cave 1 Padmapani mural', tag: 'Famous' },
          { name: 'Horseshoe gorge viewpoint', tag: 'Panorama' },
          { name: 'Buddhist chaitya halls', tag: 'Spiritual' },
        ]},
      { name: 'Aurangabad City', emoji: '🕌', accentColor: '#0F766E',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Mughal monuments and bazaars', spots: [
          { name: 'Bibi Ka Maqbara', tag: 'Mini Taj' },
          { name: 'Panchakki water mill', tag: 'Historic' },
          { name: 'Himroo shawl workshops', tag: 'Craft' },
          { name: 'Aurangabad caves', tag: 'Quiet ruins' },
        ]},
    ],
  },

  {
    slug: 'bodh-gaya', name: 'Bodh Gaya', state: 'Bihar',
    country: 'India', flag: '🇮🇳', tagline: 'Where Buddha Awakened',
    description: 'The most sacred Buddhist pilgrimage site in the world — the Mahabodhi Temple, Bodhi Tree, monasteries from across Asia, and a rare atmosphere of global devotion.',
    heroDescription: 'Under the Bodhi Tree in Bodh Gaya, Siddhartha Gautama became the Buddha. Today the Mahabodhi Temple complex gathers monks, pilgrims, and seekers from every Buddhist tradition.',
    stats: { bestTime: 'Oct – Mar', budget: '$10–$45/day', language: 'Hindi, Magahi, English', currency: 'INR (Rupee)' },
    vibes: ['Spiritual', 'Cultural', 'Historical'],
    gradient: 'from-yellow-900 to-red-900', accentColor: '#CA8A04',
    image: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Mahabodhi Complex', emoji: '🛕', accentColor: '#CA8A04',
        image: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=600&q=80',
        tagline: 'The heart of Buddhist pilgrimage', spots: [
          { name: 'Mahabodhi Temple (UNESCO)', tag: 'Sacred' },
          { name: 'Bodhi Tree meditation', tag: 'Must-do' },
          { name: 'Vajrasana diamond throne', tag: 'Holy site' },
          { name: 'Prayer lamps at dusk', tag: 'Atmospheric' },
        ]},
      { name: 'International Monasteries', emoji: '🙏', accentColor: '#DC2626',
        image: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=600&q=80',
        tagline: 'Buddhist traditions from across Asia', spots: [
          { name: 'Thai Monastery', tag: 'Architecture' },
          { name: 'Japanese Indosan Nippon Temple', tag: 'Peaceful' },
          { name: 'Tibetan monasteries', tag: 'Prayer halls' },
          { name: 'Great Buddha statue', tag: 'Landmark' },
        ]},
      { name: 'Around Gaya', emoji: '🌾', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
        tagline: 'Sacred geography and river plains', spots: [
          { name: 'Dungeshwari Cave Temples', tag: 'Buddha trail' },
          { name: 'Sujata Stupa', tag: 'Pilgrimage' },
          { name: 'Vishnupad Temple in Gaya', tag: 'Hindu sacred site' },
          { name: 'Phalgu River ghats', tag: 'Rituals' },
        ]},
    ],
  },

  {
    slug: 'guwahati', name: 'Guwahati', state: 'Assam',
    country: 'India', flag: '🇮🇳', tagline: 'Gateway to Northeast India',
    description: 'A river city on the Brahmaputra with ancient temples, tea culture, river cruises, hilltop sunsets, and easy access to Meghalaya and Kaziranga.',
    heroDescription: 'The Brahmaputra moves past Guwahati like an inland sea. Ferries cross to river islands, temple bells ring from hilltops, and the city works as the Northeast\'s most useful travel launchpad.',
    stats: { bestTime: 'Oct – Apr', budget: '$15–$55/day', language: 'Assamese, Hindi, English', currency: 'INR (Rupee)' },
    vibes: ['Cultural', 'Urban', 'Nature'],
    gradient: 'from-teal-900 to-slate-900', accentColor: '#0F766E',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Nilachal & Temples', emoji: '🛕', accentColor: '#DC2626',
        image: 'https://images.unsplash.com/photo-1592635196078-9fdc5f6b01c9?auto=format&fit=crop&w=600&q=80',
        tagline: 'Ancient Shakti and hilltop shrines', spots: [
          { name: 'Kamakhya Temple', tag: 'Must-see' },
          { name: 'Umananda Temple on Peacock Island', tag: 'River island' },
          { name: 'Navagraha Temple', tag: 'Hilltop' },
          { name: 'Basistha Ashram', tag: 'Peaceful' },
        ]},
      { name: 'Brahmaputra Riverfront', emoji: '🚢', accentColor: '#0891B2',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
        tagline: 'Cruises, sunsets and ferries', spots: [
          { name: 'Brahmaputra sunset cruise', tag: 'Classic' },
          { name: 'Fancy Bazaar riverside', tag: 'Market' },
          { name: 'Guwahati Planetarium area', tag: 'Evening walk' },
          { name: 'Saraighat Bridge views', tag: 'Landmark' },
        ]},
      { name: 'Northeast Gateway', emoji: '🌿', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=600&q=80',
        tagline: 'Day trips and onward routes', spots: [
          { name: 'Deepor Beel bird sanctuary', tag: 'Wetland' },
          { name: 'Pobitora Wildlife Sanctuary', tag: 'Rhinos' },
          { name: 'Shillong road trip', tag: 'Meghalaya' },
          { name: 'Assam State Museum', tag: 'Culture' },
        ]},
    ],
  },

  {
    slug: 'kaziranga', name: 'Kaziranga', state: 'Assam',
    country: 'India', flag: '🇮🇳', tagline: 'Rhino Kingdom of Assam',
    description: 'A UNESCO World Heritage floodplain of tall elephant grass and wetlands — the world\'s great stronghold of one-horned rhinoceros, plus elephants, wild buffalo, birds, and tigers.',
    heroDescription: 'Kaziranga feels primeval at sunrise: rhinos grazing through silver grass, swamp deer in the mist, and the Brahmaputra floodplain stretching wide under an enormous Assam sky.',
    stats: { bestTime: 'Nov – Apr', budget: '$25–$130/day', language: 'Assamese, Hindi, English', currency: 'INR (Rupee)' },
    vibes: ['Wildlife', 'Nature', 'Adventure'],
    gradient: 'from-green-900 to-yellow-900', accentColor: '#4D7C0F',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d040a94?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1549366021-9f761d040a94?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Central & Western Ranges', emoji: '🦏', accentColor: '#4D7C0F',
        image: 'https://images.unsplash.com/photo-1549366021-9f761d040a94?auto=format&fit=crop&w=600&q=80',
        tagline: 'Prime rhino country', spots: [
          { name: 'Kohora Central Range safari', tag: 'Popular' },
          { name: 'Bagori Western Range', tag: 'Rhinos' },
          { name: 'Elephant grass landscapes', tag: 'Photography' },
          { name: 'Mihimukh viewpoint', tag: 'Wetlands' },
        ]},
      { name: 'Eastern Range', emoji: '🦅', accentColor: '#0F766E',
        image: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=600&q=80',
        tagline: 'Birdlife and quieter safaris', spots: [
          { name: 'Agaratoli Eastern Range', tag: 'Birdwatching' },
          { name: 'Sohola Beel wetland', tag: 'Waterbirds' },
          { name: 'Brahmaputra river edge', tag: 'Landscape' },
          { name: 'Jeep safari at dawn', tag: 'Best light' },
        ]},
      { name: 'Karbi Hills & Villages', emoji: '🌾', accentColor: '#CA8A04',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
        tagline: 'Tea gardens and local culture', spots: [
          { name: 'Tea estate visits', tag: 'Assam tea' },
          { name: 'Karbi village experiences', tag: 'Culture' },
          { name: 'Kaziranga Orchid Park', tag: 'Local food' },
          { name: 'Panbari Reserve Forest', tag: 'Nature walk' },
        ]},
    ],
  },

  {
    slug: 'chandigarh', name: 'Chandigarh', state: 'Chandigarh',
    country: 'India', flag: '🇮🇳', tagline: 'Le Corbusier\'s Garden City',
    description: 'India\'s planned modernist city — clean sectors, monumental architecture, the surreal Rock Garden, Sukhna Lake, and easy access to the Himalayan foothills.',
    heroDescription: 'Chandigarh is unlike any other Indian city: a modernist grid designed by Le Corbusier, softened by gardens, lakefront mornings, and some of North India\'s most relaxed urban living.',
    stats: { bestTime: 'Oct – Mar', budget: '$20–$80/day', language: 'Hindi, Punjabi, English', currency: 'INR (Rupee)' },
    vibes: ['Urban', 'Design', 'Nature'],
    gradient: 'from-slate-900 to-emerald-900', accentColor: '#475569',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=85',
    areas: [
      { name: 'Capitol & Design Icons', emoji: '🏛️', accentColor: '#475569',
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
        tagline: 'Modernist architecture and civic scale', spots: [
          { name: 'Capitol Complex (UNESCO)', tag: 'Architecture' },
          { name: 'Open Hand Monument', tag: 'Iconic' },
          { name: 'Government Museum and Art Gallery', tag: 'Design' },
          { name: 'Sector 17 plaza', tag: 'City centre' },
        ]},
      { name: 'Lake & Gardens', emoji: '🌳', accentColor: '#16A34A',
        image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
        tagline: 'The city at its most relaxed', spots: [
          { name: 'Sukhna Lake sunrise walk', tag: 'Classic' },
          { name: 'Rock Garden by Nek Chand', tag: 'Must-see' },
          { name: 'Zakir Hussain Rose Garden', tag: 'Seasonal' },
          { name: 'Leisure Valley greenbelt', tag: 'Cycling' },
        ]},
      { name: 'Food & Foothills', emoji: '🍽️', accentColor: '#D97706',
        image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80',
        tagline: 'Punjabi food and mountain gateways', spots: [
          { name: 'Sector 26 restaurants', tag: 'Dining' },
          { name: 'Elante Mall', tag: 'Shopping' },
          { name: 'Pinjore Gardens day trip', tag: 'Mughal garden' },
          { name: 'Kasauli hill escape', tag: 'Weekend' },
        ]},
    ],
  },

  // ── BATCH 4 PLACEHOLDER ──────────────────────────────────────
  // Add next 10 cities in the next session:
  // Amritsar, Kanyakumari, Hampi, Udaipur, Mount Abu,
  // Rann of Kutch, Shillong, Gangtok, Auroville, Mysore
];
