import type { BlogPost } from './blog';

type ArticleSeed = {
  slug: string;
  citySlug: string;
  city: string;
  country: string;
  title: string;
  excerpt: string;
  intro: string;
  duration: string;
  when: string;
  arrival: string;
  dayOne: string;
  dayTwo: string;
  dayThree: string;
  food: string;
  stay: string;
  practical: string[];
  mistakes: string[];
};

const seeds: ArticleSeed[] = [
  {
    slug: 'varna-itinerary-black-sea-bulgaria', citySlug: 'varna', city: 'Varna', country: 'Bulgaria',
    title: 'Varna Itinerary: 3 Days of Black Sea Beaches and Ancient History',
    excerpt: 'A practical three-day Varna plan covering the Sea Garden, Varna Gold, Roman baths, beaches and the best nearby day trip.',
    intro: 'Varna works because it is both a real Bulgarian city and a seaside break. The archaeological collection and Roman remains justify a cultural trip, while the long park-and-beach strip makes the schedule feel unhurried. Three days gives first-time visitors enough time for the centre, the coast and one excursion without treating Varna as only an airport for beach resorts.',
    duration: 'Three full days; add a fourth for Balchik and Cape Kaliakra or a slower beach day.',
    when: 'Late May, June and September offer warm coastal weather with less pressure than the July–August peak. Museums make a winter visit possible, but beach facilities and excursions are more limited outside the warm season.',
    arrival: 'Varna Airport is west of the centre. Check the airport and city transport sites for the current bus route and operating hours; a licensed taxi is the simplest late-night option. The central sights, pedestrian zone and Sea Garden are manageable on foot.',
    dayOne: 'Start at the Dormition Cathedral, follow the pedestrian centre toward the Archaeological Museum, and allow real time for the prehistoric Varna Gold rather than rushing the collection. Continue to the Roman Thermae, then walk through the Greek Quarter to the waterfront. Finish in the Sea Garden at sunset.',
    dayTwo: 'Use the morning for Central Beach and the promenade before the strongest sun. Continue north through the Sea Garden, choosing the Naval Museum or another indoor stop that suits your interests. Return to the centre for a Bulgarian dinner rather than eating every meal on the resort-facing waterfront.',
    dayThree: 'Choose one focused excursion. Pobiti Kamani, the Stone Forest, is the easiest landscape contrast. Travellers with a car or organised tour can instead combine Balchik’s palace and botanical garden with Cape Kaliakra; confirm opening and transport details before setting out.',
    food: 'Look for shopska salad, grilled vegetables, banitsa and tarator; seafood is prominent on the coast. Vegetarian travellers should still ask whether soups, beans or stuffed vegetables use meat stock.',
    stay: 'Stay between the pedestrian centre and the southern Sea Garden for the best balance of museums, restaurants and beach access.',
    practical: ['Carry beach shoes for pebbly sections and strong sun protection in summer.', 'Keep museum-heavy sightseeing for midday heat.', 'Use official taxi ranks or an established app where available.', 'Check the Archaeological Museum schedule before fixing your itinerary.'],
    mistakes: ['Staying at a distant resort when the goal is to explore Varna itself.', 'Treating the Sea Garden as a quick photo stop instead of the city’s main public space.', 'Planning both Balchik and Stone Forest by public transport without checking connections.'],
  },
  {
    slug: 'ljubljana-itinerary-3-days', citySlug: 'ljubljana', city: 'Ljubljana', country: 'Slovenia',
    title: 'Ljubljana in 3 Days: Castle, Riverfront and Easy Day Trips',
    excerpt: 'A walkable three-day Ljubljana itinerary with Plečnik architecture, Central Market, Tivoli Park and a smart choice of day trip.',
    intro: 'Ljubljana is small enough to understand on foot but interesting enough not to reduce to a transit stop. Plečnik’s bridges and market architecture turn the river into the city’s main room, while the castle and green spaces add easy contrasts. A three-day plan leaves room for café time and one Slovenian excursion.',
    duration: 'Two days for the capital itself, plus one day for Bled, Postojna or another regional priority.',
    when: 'April to June and September to October are comfortable for walking. July and August bring long days but also peak visitor numbers; winter is atmospheric and can be cold, with shorter attraction hours.',
    arrival: 'The railway and bus stations sit close to the centre. From the airport, use the current official airport or Visit Ljubljana guidance for bus and shuttle choices. Inside the compact centre, walk first; city buses are most useful for outer districts.',
    dayOne: 'Begin at Prešeren Square and cross the Triple Bridge before the centre becomes busy. Browse Central Market, see Dragon Bridge and follow the Ljubljanica embankments through the old town. Walk or take the funicular to Ljubljana Castle for late-afternoon views, checking exhibition and tower access separately.',
    dayTwo: 'Visit Tivoli Park and the National Gallery or a museum aligned with your interests. Return through Plečnik’s city, including Congress Square and the National and University Library exterior. Keep the evening open for the riverfront, but eat one street back if you want quieter tables.',
    dayThree: 'Choose rather than cram. Lake Bled is the classic first trip and is well served by buses; Postojna Cave and Predjama Castle suit geology and history; Škocjan requires more careful transport planning. Verify the day’s timetable and attraction slot before departure.',
    food: 'Use Central Market to sample Slovenian produce and bakery snacks. Ljubljana also has strong vegetarian coverage; for traditional menus, ask about štruklji, jota and seasonal dumplings.',
    stay: 'The centre between the station and the river is convenient. Krakovo and Trnovo feel more residential while remaining walkable.',
    practical: ['Market activity varies by day and weather.', 'Castle funicular tickets and castle exhibition tickets are not always the same product.', 'Reserve headline cave visits in busy months.', 'Do not assume every regional attraction is equally easy without a car.'],
    mistakes: ['Using Ljubljana only as a sleeping base and never slowing down by the river.', 'Scheduling Bled and a major cave on the same day.', 'Dragging luggage across pedestrian cobbles when a short transfer would help.'],
  },
  {
    slug: 'lake-bled-itinerary-without-car', citySlug: 'lake-bled', city: 'Lake Bled', country: 'Slovenia',
    title: 'Lake Bled Without a Car: A Complete 2-Day Itinerary',
    excerpt: 'How to visit Lake Bled by public transport, sequence the castle, island and viewpoints, and decide whether Vintgar Gorge fits.',
    intro: 'Lake Bled is easy to photograph and surprisingly easy to plan badly. Day visitors often arrive with the same midday crowd, queue for a boat, skip the viewpoints and leave before the lake becomes calm again. Staying one night creates two quiet windows and makes a car unnecessary for the core experience.',
    duration: 'One long day covers the lake highlights; two days is far better for viewpoints, weather flexibility and Vintgar Gorge.',
    when: 'Late spring and early autumn balance trail conditions with manageable crowds. Summer has the widest service but busy buses and parking. In winter, snow can be beautiful, while boats, paths and gorge access may be restricted.',
    arrival: 'Direct buses from Ljubljana are usually the simplest public-transport choice and stop near the lake. Trains use different stations at varying distances, so check the exact station and onward link rather than searching only for “Bled”.',
    dayOne: 'Arrive early and walk the lake circuit clockwise or counter-clockwise before deciding on the boat. Visit Bled Castle when visibility is good. Take a traditional pletna or scheduled boat to Bled Island if operating, then save the lakeside promenade and cream cake for late afternoon after many day groups leave.',
    dayTwo: 'Start the Ojstrica climb early on a dry morning; the short trail is steep and requires proper shoes. Continue to Mala Osojnica only if conditions and fitness suit. After lunch, visit Vintgar Gorge when its seasonal route is open, using the official access and shuttle instructions rather than an outdated map.',
    dayThree: 'If adding another day, choose Lake Bohinj and Triglav National Park. It is a distinct destination, not a quick add-on to a packed Bled day, and deserves time for the lake shore or a cable-car and hiking plan.',
    food: 'Bled cream cake is the famous stop, but the town also has Slovenian inns and modern cafés. Prices directly on the waterfront tend to be higher; reserve dinner in peak season.',
    stay: 'Stay within walking distance of the eastern or southern lake shore if arriving by bus, unless your accommodation provides a transfer.',
    practical: ['Use shoes with grip for Ojstrica.', 'Confirm Vintgar’s seasonal opening and one-way visitor system.', 'Swimming is permitted only in designated areas.', 'Keep a rain alternative because mountain weather changes quickly.'],
    mistakes: ['Trying to see the island, castle, gorge and Bohinj in one day.', 'Relying on a generic “Bled train station” without checking which one.', 'Walking viewpoint trails in sandals or after heavy rain.'],
  },
  {
    slug: 'piran-day-trip-or-overnight-guide', citySlug: 'piran', city: 'Piran', country: 'Slovenia',
    title: 'Piran Day Trip or Overnight? The Practical Slovenia Coast Guide',
    excerpt: 'A realistic Piran plan covering Tartini Square, town walls, St George’s, parking, swimming and the salt pans.',
    intro: 'Piran is often treated as a fast coastal stop, but its best hours come after the midday groups leave. The old town is tiny and largely pedestrian, so a day trip covers the monuments; an overnight stay adds sunset, an early waterfront walk and time for the salt-making landscape nearby.',
    duration: 'Allow a full day for the old town; stay one night if the coast matters more than ticking sights.',
    when: 'May, June and September are ideal for warm weather and walking. July and August are busiest and hottest. Spring and autumn suit culture and food even when the sea is too cool for a long swim.',
    arrival: 'Cars are restricted in the historic core. Use the designated garages and shuttle or walk into town. Regional buses connect the coast, but frequency can vary by day and season, so check the operator rather than relying on old blog timetables.',
    dayOne: 'Enter through Tartini Square, note the Venetian House and climb toward St George’s Church and bell tower. Continue to the town walls while the light is clear. Descend through the lanes to Punta and follow the waterfront for sunset, leaving time to swim only in designated, safe areas.',
    dayTwo: 'If staying overnight, walk the waterfront early and visit the Maritime Museum or Tartini House when open. Use the afternoon for Sečovlje Salina Nature Park, a guided salt experience, or a coastal walk toward Strunjan. Confirm transport back before committing.',
    dayThree: 'A longer Slovenian Istria plan can include Portorož for resort facilities and Koper for a larger historic centre. Keep expectations clear: Piran’s appeal is atmosphere, architecture and sea, not a long checklist.',
    food: 'Istrian menus focus on seafood, olive oil, wine, truffles and pasta. Vegetarian diners can ask for seasonal vegetable dishes, but should clarify fish stock and anchovy-based sauces.',
    stay: 'Inside or immediately beside the old town gives the full experience; travellers with cars should confirm parking arrangements with the property.',
    practical: ['Wear grippy shoes on polished lanes and wall steps.', 'Carry water for exposed viewpoints in summer.', 'Check bell-tower and wall closing times.', 'Do not drive into restricted streets following a generic map route.'],
    mistakes: ['Arriving only at noon and leaving before sunset.', 'Expecting a broad sandy beach in the old town.', 'Booking an old-town room without understanding luggage and parking access.'],
  },
  {
    slug: 'belgrade-itinerary-first-time-visitors', citySlug: 'belgrade', city: 'Belgrade', country: 'Serbia',
    title: 'Belgrade in 3 Days: A First-Timer’s Fortress, Food and Nightlife Plan',
    excerpt: 'A balanced Belgrade itinerary covering Kalemegdan, Saint Sava, Zemun, museums and the city’s famous evenings.',
    intro: 'Belgrade reveals itself through layers rather than postcard perfection. Roman, Ottoman, Habsburg, Yugoslav and contemporary stories overlap at the river confluence. Three days lets visitors understand the fortress and centre, see Saint Sava and the twentieth-century city, and cross to Zemun without making nightlife the whole trip.',
    duration: 'Three full days; add a fourth for museums, Avala or a slower Danube schedule.',
    when: 'Late spring and early autumn are best for long walks and outdoor evenings. Summer can be hot, while winter is cold and smoky days are possible; indoor opening hours should shape the plan.',
    arrival: 'Airport buses and fixed or metered taxi options change, so use current airport guidance. The centre is walkable, but buses and trams help with Saint Sava, Zemun and New Belgrade. Validate the correct ticket product under the current system.',
    dayOne: 'Walk Knez Mihailova to Belgrade Fortress and spend several hours across Kalemegdan, museums and river viewpoints. Continue toward Dorćol before dinner in Skadarlija, understanding that its best-known restaurants are atmospheric and tourist-facing.',
    dayTwo: 'Visit the Church of Saint Sava and its crypt, then choose the Nikola Tesla Museum or Museum of Yugoslavia. Timed or guided museum access can sell out, so reserve where the official site recommends. Finish with riverside or neighbourhood dining rather than chasing a generic “best nightlife” list.',
    dayThree: 'Explore Zemun’s lanes, market and Gardoš area, then walk the Danube quay. Return through New Belgrade for a different architectural reading of the city. If taking a river cruise, verify the licensed operator, route and weather policy.',
    food: 'Serbian meals are often meat-heavy, but bakeries, grilled peppers, beans, kajmak, shopska-style salads and modern vegetarian restaurants broaden the choice. Ask whether bean dishes contain smoked meat.',
    stay: 'Dorćol and the central area suit first visits; Vračar is useful for Saint Sava and cafés; Zemun is atmospheric but less convenient for a short central itinerary.',
    practical: ['Carry some dinars even where cards are common.', 'Book small museums with timed tours ahead.', 'Use registered taxis or established apps.', 'Check demonstrations and major events that may alter central transport.'],
    mistakes: ['Spending only one hour at the fortress.', 'Assuming every floating venue offers the same safe or reputable experience.', 'Quoting obsolete public-transport rules from an old article.'],
  },
  {
    slug: 'novi-sad-day-trip-from-belgrade', citySlug: 'novi-sad', city: 'Novi Sad', country: 'Serbia',
    title: 'Novi Sad Day Trip from Belgrade: Fortress, Old Town and Fruška Gora',
    excerpt: 'Plan Novi Sad from Belgrade with Petrovaradin Fortress, the old centre and a clear choice between a day trip and overnight stay.',
    intro: 'Novi Sad is Serbia’s strongest city break after Belgrade: calmer, more Central European in appearance and dominated by Petrovaradin Fortress across the Danube. A day trip covers the historic core and fortress, while an overnight stay is better for tunnels, galleries, wine country or festival dates.',
    duration: 'One full day for the city; two days if adding Fruška Gora or Sremski Karlovci.',
    when: 'April to June and September to October are comfortable. EXIT and other major events transform prices and access, so travellers should decide whether a festival is the purpose of the visit or something to avoid.',
    arrival: 'Rail and bus operations have changed during recent infrastructure works, so verify the active Belgrade departure station, Novi Sad arrival point and any replacement transport on the official operator site immediately before travel.',
    dayOne: 'Begin at Liberty Square and walk Zmaj Jovina and Dunavska streets to Danube Park. Cross toward Petrovaradin, explore the Lower Town and climb to the clock-tower plateau. The fortress deserves time for views, art studios and the City Museum rather than only a single photograph.',
    dayTwo: 'On an overnight visit, book an authorised tour of the underground military galleries if available. Then choose Sremski Karlovci for baroque streets and wine culture or Fruška Gora for monasteries and trails. These are easier with a planned transfer than improvised late in the day.',
    dayThree: 'Travellers continuing north can build Novi Sad into a wider Vojvodina route, but should avoid assuming rural attractions have frequent public transport.',
    food: 'Vojvodina cuisine reflects Serbian, Hungarian and wider Central European influences. Try pastries, river fish and seasonal produce; vegetarians should clarify broths and cooking fats.',
    stay: 'The central pedestrian area is easiest without a car. Petrovaradin is more atmospheric for a second visit but adds a river crossing to most city services.',
    practical: ['Check fortress museum and tunnel-tour times.', 'Expect event-related closures in festival periods.', 'Carry sun protection on exposed fortress areas.', 'Confirm the live rail situation rather than repeating the usual journey time.'],
    mistakes: ['Treating Petrovaradin as only an EXIT venue.', 'Adding Fruška Gora to a short winter day without transport arranged.', 'Building a tight connection around an unverified train schedule.'],
  },
  {
    slug: 'kotor-itinerary-bay-of-kotor', citySlug: 'kotor', city: 'Kotor', country: 'Montenegro',
    title: 'Kotor Itinerary: 3 Days in Montenegro’s Most Dramatic Bay',
    excerpt: 'A three-day Kotor plan for the old town, fortress hike, Perast, boat trips and avoiding cruise-hour congestion.',
    intro: 'Kotor’s geography dictates the trip: a walled town at the narrow edge of a mountain-ringed bay, with fortifications climbing almost vertically behind it. The old town is small, but cruise traffic, summer heat and the fortress ascent make timing crucial. Two nights produce a much better experience than a rushed port stop.',
    duration: 'Two full days for Kotor and Perast; three days for a bay boat trip or Lovćen extension.',
    when: 'May, June, September and early October offer the best balance. July and August can be intensely hot and crowded; heavy rain can make stone steps and hiking routes unsafe.',
    arrival: 'Kotor has no airport. Tivat is closest, while Podgorica and Dubrovnik may offer more flights. Border and coastal-road delays vary sharply, so avoid tight same-day flight connections and confirm cross-border transfer requirements.',
    dayOne: 'Enter the old town early through the Sea Gate, following lanes to St Tryphon Cathedral, St Luke’s Church and the Maritime Museum. Break during peak cruise hours, then return for an evening circuit when the squares become calmer.',
    dayTwo: 'Start the San Giovanni fortress route at first light only if the weather, footwear and fitness are suitable. Carry water and use the official entrance. Recover after lunch, then walk the waterfront or join a shorter licensed bay trip.',
    dayThree: 'Travel to Perast and take the authorised local boat to Our Lady of the Rocks. With more time, choose a bay circuit or Lovćen and Cetinje—not both in a hurried day. Confirm seasonal buses and last return options.',
    food: 'Bay cuisine centres on seafood, smoked ham, cheeses and simple Mediterranean vegetables. Ask for meat-free preparation explicitly, especially with risotto and soups.',
    stay: 'Inside the walls is atmospheric but can be noisy and difficult with luggage. Dobrota offers waterfront stays and a walk or short ride into the old town.',
    practical: ['Do the fortress climb outside peak heat.', 'Use shoes with grip on polished stone.', 'Check cruise schedules as a crowd indicator.', 'Allow large buffers for coastal and border traffic.'],
    mistakes: ['Attempting the fortress in midday summer heat.', 'Booking a Dubrovnik airport transfer with no border-delay margin.', 'Assuming every advertised boat follows the same route or safety standard.'],
  },
  {
    slug: 'budva-itinerary-beaches-old-town', citySlug: 'budva', city: 'Budva', country: 'Montenegro',
    title: 'Budva in 3 Days: Old Town, Beaches and the Right Riviera Base',
    excerpt: 'A realistic Budva guide balancing the walled town, Mogren Beach, Sveti Stefan viewpoints and summer nightlife.',
    intro: 'Budva is Montenegro’s busiest resort city, which is exactly why expectations matter. It offers an attractive walled old town, accessible beaches and a strong summer nightlife scene, but peak-season congestion can overwhelm a short visit. A structured three-day plan finds the history before the crowds and treats the wider riviera selectively.',
    duration: 'Two days for Budva itself; three days with Sveti Stefan, a boat trip or a quieter coastal stop.',
    when: 'Late May, June and September bring swimmable conditions with fewer peak-season pressures. July and August suit travellers seeking nightlife but require early reservations and patience with traffic.',
    arrival: 'Tivat is the nearest airport, with Podgorica and Dubrovnik as alternatives. Coastal buses serve Budva, but summer roads can be slow. Confirm airport transfers and cross-border rules before booking.',
    dayOne: 'Enter Budva Old Town early, visit the Citadel and churches, and walk the walls where access is open. Follow the coastal path to Mogren Beach later in the morning. Return for an evening walk, when the stone lanes and squares are most atmospheric.',
    dayTwo: 'Use a public bus, licensed taxi or organised excursion for the Sveti Stefan viewpoints and Praskvica Monastery. The famous islet’s access arrangements can change and parts are private, so plan around confirmed public viewpoints rather than assuming entry.',
    dayThree: 'Choose a beach day, licensed boat trip or quieter Petrovac excursion. Travellers interested mainly in heritage may prefer to continue to Kotor; those seeking clubs and resort energy should keep the evening free in Budva.',
    food: 'The riviera offers seafood, grills, Italian-influenced dishes and modern international menus. Prices and quality vary most on the busiest strips, so compare recent menus before sitting down.',
    stay: 'Near the old town is convenient and lively. Bečići works for a resort beach; quieter travellers should avoid rooms directly beside major nightlife venues.',
    practical: ['Confirm whether accommodation includes parking.', 'Use official public viewpoints at Sveti Stefan.', 'Reserve popular summer rooms early.', 'Check beach conditions and flags before swimming.'],
    mistakes: ['Expecting Budva to feel quiet in August.', 'Driving between every nearby beach at peak hour.', 'Booking solely by map distance without reading noise and hill-access details.'],
  },
  {
    slug: 'bratislava-one-day-or-weekend', citySlug: 'bratislava', city: 'Bratislava', country: 'Slovakia',
    title: 'Bratislava in One Day or a Weekend: The Best Walking Route',
    excerpt: 'A practical Bratislava route linking the castle, old town, Blue Church and Devín, with advice on when to stay overnight.',
    intro: 'Bratislava is often visited between Vienna and Budapest, and its compact scale makes that possible. Yet a day trip usually misses Devín, the evening old town and the city’s Danube setting. One day covers the essentials; a weekend creates a more complete Slovak stop without overfilling the schedule.',
    duration: 'One full day for the central route; two days if adding Devín Castle and museums.',
    when: 'April to June and September to October suit walking. Summer is lively and warm; December brings markets and early darkness. Danube boat services and some outdoor attractions are seasonal.',
    arrival: 'Trains and buses arrive at different stations, both linked to the centre by public transport. From Vienna, compare the live rail, bus and seasonal boat options. Do not plan around a historic timetable.',
    dayOne: 'Start at Bratislava Castle before group traffic builds, then descend past St Martin’s Cathedral into the Old Town. Walk Michael’s Gate, Main Square and the Old Town Hall. Continue to the Blue Church, then return to the Danube for sunset or a viewpoint chosen according to weather.',
    dayTwo: 'Take the official city bus or seasonal boat to Devín Castle and allow time for the museum, ruins and Danube–Morava landscape. Back in town, choose the City Museum, Slovak National Gallery or Slavín rather than racing through all three.',
    dayThree: 'With extra time, explore the Little Carpathian wine towns or continue deeper into Slovakia. Bratislava is a useful gateway, not a substitute for the Tatras or the country’s central historic towns.',
    food: 'Try bryndza-based dishes, dumplings and soups, but ask about bacon garnish and meat stock. The centre also has broad vegetarian and international choices.',
    stay: 'The Old Town edge gives easy walking without the highest square-side prices. Areas near the main station are practical for early departures.',
    practical: ['Validate public-transport tickets correctly.', 'Confirm seasonal Danube sailings.', 'Wear comfortable shoes for the castle and old-town slopes.', 'Check Monday museum closures.'],
    mistakes: ['Allocating only a rushed two-hour transfer window.', 'Assuming Vienna transit products cover Bratislava.', 'Adding Devín without checking the return timetable.'],
  },
  {
    slug: 'tallinn-itinerary-3-days', citySlug: 'tallinn', city: 'Tallinn', country: 'Estonia',
    title: 'Tallinn in 3 Days: Medieval Old Town, Kadriorg and Creative Districts',
    excerpt: 'A researched Tallinn itinerary with the UNESCO old town, museum planning, Telliskivi, Kadriorg and current transport basics.',
    intro: 'Tallinn’s old town earns the attention, but the city becomes more interesting when the itinerary crosses the medieval walls. Kadriorg shows imperial and art history, Telliskivi and Kalamaja reveal the creative city, and the Seaplane Harbour explains Estonia’s maritime position. Three days balances all four.',
    duration: 'Two days cover the old town and one outer district; three days allows Kadriorg and the maritime museums without rushing.',
    when: 'May to September has long daylight and the broadest opening schedules. December is atmospheric for winter markets, while January and February are cold with short days and potentially icy streets.',
    arrival: 'The airport, ferry port, coach station and Balti Jaam rail station all connect to the centre. Current Visit Tallinn guidance lists bus and tram options. Visitors must hold a valid ticket; free city transport for registered residents does not generally mean tourists ride free.',
    dayOne: 'Enter the UNESCO old town early at Viru Gate, walk Town Hall Square and the guild streets, then climb to Toompea for cathedral architecture and viewing platforms. Choose one fortification museum rather than spending the entire day underground. Return after dark for a second look at the lanes.',
    dayTwo: 'Walk through Kalamaja to Telliskivi Creative City and Balti Jaam Market, then continue to the Seaplane Harbour. The museum is substantial, so protect at least two hours. Return by public transport if weather turns.',
    dayThree: 'Take a tram or bus toward Kadriorg Palace and park, pairing it with Kumu Art Museum if your interests and opening day align. In summer, continue toward Pirita; in poor weather, choose another central museum.',
    food: 'Tallinn ranges from modern Estonian tasting menus to market counters and bakeries. Expect rye bread, fish, potatoes, forest berries and seasonal ingredients, with strong vegetarian coverage in creative districts.',
    stay: 'The old-town edge is easier for luggage and transport than an address deep inside cobbled lanes. Kalamaja suits repeat visitors and design-focused trips.',
    practical: ['Many museums close on Monday.', 'Contactless validation rules still require the correct tap.', 'Use shoes suited to cobbles and winter ice.', 'Compare the Tallinn Card only against attractions you will genuinely visit.'],
    mistakes: ['Believing public transport is free for all visitors.', 'Spending all three days inside the old walls.', 'Buying a sightseeing pass without checking closures and actual admission savings.'],
  },
];

function buildPost(seed: ArticleSeed): BlogPost {
  const cityUrl = `/cities/${seed.citySlug}`;
  return {
    slug: seed.slug,
    title: seed.title,
    excerpt: seed.excerpt,
    date: '2026-07-28',
    readTime: 8,
    category: 'Europe',
    tags: [seed.city, seed.country, 'Itinerary', 'Europe', 'Trip Planning'],
    coverPhoto: `/city-images/${seed.citySlug}.jpg`,
    citySlug: seed.citySlug,
    cities: [seed.citySlug],
    content: [
      { type: 'p', text: seed.intro },
      { type: 'callout', emoji: '✅', text: 'Research note: routes, sights and planning advice were checked against official destination sources in July 2026. Opening hours, fares, transport operations and entry rules can change; verify them on official sites immediately before travel.' },
      { type: 'h2', text: `How Many Days Do You Need in ${seed.city}?` },
      { type: 'p', text: seed.duration },
      { type: 'h2', text: `Best Time to Visit ${seed.city}` },
      { type: 'p', text: seed.when },
      { type: 'h2', text: 'Arrival and Getting Around' },
      { type: 'p', text: seed.arrival },
      { type: 'h2', text: `Day 1 — ${seed.city} Essentials` },
      { type: 'p', text: seed.dayOne },
      { type: 'h2', text: 'Day 2 — Go Beyond the Postcard' },
      { type: 'p', text: seed.dayTwo },
      { type: 'h2', text: 'Day 3 or Best Extension' },
      { type: 'p', text: seed.dayThree },
      { type: 'h2', text: 'What and Where to Eat' },
      { type: 'p', text: seed.food },
      { type: 'h2', text: 'Best Area to Stay' },
      { type: 'p', text: seed.stay },
      { type: 'h2', text: 'Budget and Booking Strategy' },
      {
        type: 'p',
        text: `Build the ${seed.city} budget from the trip’s fixed costs first: intercity or airport transport, accommodation, and the two or three paid sights that matter most. Then add meals, local transport and a contingency allowance. Daily-budget figures are only a planning range because festival dates, weekends and school holidays can move room prices sharply. Compare the direct price on an attraction or transport operator’s official site with any reseller, and check what the ticket actually includes. For accommodation, map the walking route to the first sight or departure stop rather than judging convenience by straight-line distance. A cheaper room can become poor value if it adds repeated transfers, steep luggage access or late-night taxi rides.`,
      },
      { type: 'h2', text: 'How to Verify the Plan Before You Travel' },
      {
        type: 'p',
        text: `Re-check the itinerary in three stages. One month before departure, confirm passport and visa requirements on the relevant government site and reserve capacity-limited stays or tours. One week before, review official attraction calendars, public-transport notices and any seasonal closures. On the morning of each excursion, check weather, service alerts and the last return connection. Save offline copies of bookings and the address of your accommodation, but do not rely on screenshots of old timetables. This guide intentionally avoids promising a fixed fare or opening hour where the operator can change it. That small verification routine is especially important when ${seed.city} is part of a multi-country trip, because border delays or a missed final connection can affect the next day as well.`,
      },
      { type: 'h2', text: 'Practical Planning Checklist' },
      { type: 'ul', items: seed.practical },
      { type: 'h2', text: 'Mistakes to Avoid' },
      { type: 'ul', items: seed.mistakes },
      { type: 'link-cta', text: `Open the complete ${seed.city} city guide for sights, maps and trip-planning modules.`, href: cityUrl },
    ],
    faqs: [
      { question: `How many days are enough for ${seed.city}?`, answer: seed.duration },
      { question: `What is the best time to visit ${seed.city}?`, answer: seed.when },
      { question: `Where should a first-time visitor stay in ${seed.city}?`, answer: seed.stay },
      { question: `Is ${seed.city} suitable without a car?`, answer: `The core itinerary is designed to work without a car. Read the arrival section carefully and verify current public-transport timetables for excursions outside ${seed.city}.` },
    ],
  };
}

export const tourismExpansionPosts: BlogPost[] = seeds.map(buildPost);
