import { City } from './types';

export const worldCities: City[] = [
  // ── ASIA ─────────────────────────────────────────────────────────────────
  {
    slug: 'singapore', name: 'Singapore', country: 'Singapore', flag: '🇸🇬',
    tagline: 'Lion City', gradient: 'from-red-600 to-white',
    accentColor: '#EF4444', heroDescription: 'A city-state that runs on efficiency, hawker food, and ambition. Singapore somehow fits world-class architecture, jungle parks, and the planet\'s best street food into 733 square kilometres.',
    description: 'Singapore is Asia\'s most liveable, cleanest, and arguably most delicious city. Gardens by the Bay, Hawker centres, and Marina Bay Sands make it unmissable.',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Feb – Apr', budget: '$80–$200/day', language: 'English, Mandarin', currency: 'SGD' },
    vibes: ['Foodie', 'Modern', 'Cultural'],
    areas: [
      { name: 'Marina Bay', emoji: '🌃', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=600&q=80', tagline: 'Iconic skyline & luxury', spots: [{ name: 'Marina Bay Sands Skypark', tag: 'Iconic' }, { name: 'Gardens by the Bay', tag: 'Must-see' }, { name: 'ArtScience Museum', tag: 'Art' }, { name: 'Merlion Park', tag: 'Landmark' }, { name: 'Helix Bridge', tag: 'Photo spot' }] },
      { name: 'Chinatown', emoji: '🏮', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=600&q=80', tagline: 'Heritage temples & hawker food', spots: [{ name: 'Buddha Tooth Relic Temple', tag: 'Cultural' }, { name: 'Maxwell Food Centre', tag: 'Hawker' }, { name: 'Chinatown Heritage Centre', tag: 'Museum' }, { name: 'Sri Mariamman Temple', tag: 'Hindu temple' }, { name: 'Pagoda Street night market', tag: 'Shopping' }] },
      { name: 'Little India', emoji: '🌺', accentColor: '#FF6B35', image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=600&q=80', tagline: 'Spices, temples & street art', spots: [{ name: 'Sri Veeramakaliamman Temple', tag: 'Temple' }, { name: 'Mustafa Centre (24hr)', tag: 'Shopping' }, { name: 'Tekka Centre hawker', tag: 'Food' }, { name: 'Haji Lane street art', tag: 'Art' }, { name: 'Kampong Glam', tag: 'Malay quarter' }] },
      { name: 'Sentosa Island', emoji: '🎢', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=600&q=80', tagline: 'Beaches, resorts & Universal Studios', spots: [{ name: 'Universal Studios Singapore', tag: 'Theme park' }, { name: 'Siloso Beach', tag: 'Beach' }, { name: 'S.E.A. Aquarium', tag: 'Family' }, { name: 'iFly Singapore', tag: 'Adventure' }, { name: 'Sentosa Cable Car', tag: 'Views' }] },
    ],
  },
  {
    slug: 'seoul', name: 'Seoul', country: 'South Korea', flag: '🇰🇷',
    tagline: 'Dynamic Capital', gradient: 'from-blue-600 to-red-500',
    accentColor: '#3B82F6', heroDescription: 'Ancient palaces alongside K-pop studios, world-class skincare, late-night street food markets, and the Han River.',
    description: 'Seoul is a city of dizzying contrasts — 600-year-old palaces next to neon-lit shopping districts, Buddhist temples above subway stations.',
    image: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Apr – Jun, Sep – Nov', budget: '$50–$150/day', language: 'Korean', currency: 'KRW (Won)' },
    vibes: ['Cultural', 'Foodie', 'Modern'],
    areas: [
      { name: 'Myeongdong', emoji: '🛍️', accentColor: '#3B82F6', image: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=600&q=80', tagline: 'Shopping, street food & K-beauty', spots: [{ name: 'K-beauty skincare shops', tag: 'Shopping' }, { name: 'Myeongdong Street Food Alley', tag: 'Food' }, { name: '명동성당 (Cathedral)', tag: 'Landmark' }, { name: 'Lotte Department Store', tag: 'Luxury' }, { name: 'Namdaemun Market nearby', tag: 'Market' }] },
      { name: 'Bukchon Hanok Village', emoji: '🏯', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=600&q=80', tagline: 'Traditional Korean architecture', spots: [{ name: 'Hanok traditional houses', tag: 'Heritage' }, { name: 'Gyeongbokgung Palace', tag: 'Must-see' }, { name: 'Insadong antique market', tag: 'Culture' }, { name: 'Changdeokgung Secret Garden', tag: 'Garden' }, { name: 'National Folk Museum', tag: 'Museum' }] },
      { name: 'Hongdae', emoji: '🎸', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=600&q=80', tagline: 'University nightlife & indie art', spots: [{ name: 'Hongdae Free Market (weekends)', tag: 'Art market' }, { name: 'Street buskers & performers', tag: 'Entertainment' }, { name: 'Vinyl record shops', tag: 'Music' }, { name: 'Craft beer bars', tag: 'Nightlife' }, { name: 'Ewha Womans University area', tag: 'Fashion' }] },
      { name: 'Gangnam', emoji: '💎', accentColor: '#8B5CF6', image: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=600&q=80', tagline: 'Luxury & K-pop culture', spots: [{ name: 'COEX Mall underground', tag: 'Shopping' }, { name: 'SM Town (K-pop)', tag: 'Fan culture' }, { name: 'Garosu-gil café street', tag: 'Cafes' }, { name: 'Bongeunsa Temple', tag: 'Hidden gem' }, { name: 'Starfield Library at COEX', tag: 'Iconic' }] },
    ],
  },
  {
    slug: 'kyoto', name: 'Kyoto', country: 'Japan', flag: '🇯🇵',
    tagline: 'Ancient Imperial Capital', gradient: 'from-red-800 to-pink-600',
    accentColor: '#DC2626', heroDescription: 'Japan\'s soul. Over 1,600 Buddhist temples, geisha districts, bamboo groves, and a living tradition of tea ceremony, kaiseki cuisine, and seasonal beauty.',
    description: 'Kyoto is where Japan\'s cultural heritage is most completely preserved — a city where ancient ritual and natural beauty coexist in every neighbourhood.',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Mar – May, Oct – Nov', budget: '$80–$200/day', language: 'Japanese', currency: 'JPY (Yen)' },
    vibes: ['Cultural', 'Spiritual', 'Romantic'],
    areas: [
      { name: 'Arashiyama', emoji: '🎋', accentColor: '#DC2626', image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80', tagline: 'Bamboo groves & riverside temples', spots: [{ name: 'Arashiyama Bamboo Grove', tag: 'Iconic' }, { name: 'Tenryu-ji Temple garden', tag: 'UNESCO' }, { name: 'Monkey Park Iwatayama', tag: 'Wildlife' }, { name: 'Togetsukyo Bridge', tag: 'Scenic' }, { name: 'Boat rides on Oi River', tag: 'Experience' }] },
      { name: 'Gion', emoji: '🏮', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80', tagline: 'Geisha district & stone-paved lanes', spots: [{ name: 'Hanamikoji Street at dusk', tag: 'Must-see' }, { name: 'Yasaka Shrine', tag: 'Temple' }, { name: 'Gion Hatanaka (geisha dinner)', tag: 'Cultural' }, { name: 'Nishiki Market', tag: 'Food market' }, { name: 'Pontocho dining alley', tag: 'Dining' }] },
      { name: 'Fushimi', emoji: '⛩️', accentColor: '#FF6B35', image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80', tagline: '10,000 torii gates', spots: [{ name: 'Fushimi Inari (dawn visit)', tag: 'Iconic' }, { name: 'Sake brewery district', tag: 'Sake' }, { name: 'Gekkeikan Okura Sake Museum', tag: 'Museum' }, { name: 'Momoyama Castle ruins', tag: 'History' }, { name: 'Tofuku-ji Temple garden', tag: 'Zen garden' }] },
      { name: 'Higashiyama', emoji: '🎑', accentColor: '#8B5CF6', image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80', tagline: 'Stone lanes & hilltop shrines', spots: [{ name: 'Kiyomizudera Temple', tag: 'Must-see' }, { name: 'Sannen-zaka & Ninen-zaka lanes', tag: 'Shopping' }, { name: 'Kodai-ji Temple', tag: 'Zen' }, { name: 'Maruyama Park', tag: 'Cherry blossom' }, { name: 'Chion-in Gate', tag: 'Landmark' }] },
    ],
  },
  {
    slug: 'hong-kong', name: 'Hong Kong', country: 'China SAR', flag: '🇭🇰',
    tagline: 'Pearl of the Orient', gradient: 'from-red-600 to-gray-800',
    accentColor: '#EF4444', heroDescription: 'Vertical city meets ancient fishing village. The world\'s most dramatic skyline, dim sum for breakfast, night markets, and mountains accessible by subway.',
    description: 'Hong Kong defies easy description — a global financial hub where British colonial history, Chinese tradition, and ultramodern life collide spectacularly.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Oct – Dec', budget: '$80–$200/day', language: 'Cantonese, English', currency: 'HKD' },
    vibes: ['Foodie', 'Modern', 'Adventure'],
    areas: [
      { name: 'Victoria Harbour', emoji: '🌃', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80', tagline: 'The world\'s best skyline', spots: [{ name: 'Avenue of Stars (Tsim Sha Tsui)', tag: 'Promenade' }, { name: 'Symphony of Lights show (8pm)', tag: 'Free' }, { name: 'Star Ferry crossing', tag: 'Iconic' }, { name: 'Peak Tram to Victoria Peak', tag: 'Must-do' }, { name: 'Hong Kong Museum of Art', tag: 'Museum' }] },
      { name: 'Mong Kok', emoji: '🎯', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80', tagline: 'Markets, neon & street food', spots: [{ name: 'Ladies Market', tag: 'Bargains' }, { name: 'Temple Street Night Market', tag: 'Night market' }, { name: 'Goldfish Market', tag: 'Quirky' }, { name: 'Flower Market', tag: 'Beautiful' }, { name: 'Dim sum restaurants', tag: 'Food' }] },
      { name: 'Lantau Island', emoji: '🏔️', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80', tagline: 'Big Buddha & fishing villages', spots: [{ name: 'Tian Tan Big Buddha', tag: 'Iconic' }, { name: 'Po Lin Monastery', tag: 'Temple' }, { name: 'Ngong Ping Cable Car', tag: 'Views' }, { name: 'Tai O fishing village', tag: 'Traditional' }, { name: 'Disneyland Hong Kong', tag: 'Family' }] },
    ],
  },
  {
    slug: 'phuket', name: 'Phuket', country: 'Thailand', flag: '🇹🇭',
    tagline: 'Pearl of the Andaman', gradient: 'from-teal-500 to-blue-600',
    accentColor: '#14B8A6', heroDescription: 'Thailand\'s largest island — limestone cliffs rising from emerald water, long-tail boats, beach clubs, and some of Southeast Asia\'s most spectacular diving.',
    description: 'Phuket is Thailand\'s island playground — each coast has a different personality, from backpacker Patong to exclusive Surin and the rugged northwest.',
    image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Nov – Apr', budget: '$40–$150/day', language: 'Thai', currency: 'THB (Baht)' },
    vibes: ['Beach', 'Adventure', 'Luxury'],
    areas: [
      { name: 'Patong Beach', emoji: '🎉', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=600&q=80', tagline: 'Phuket\'s liveliest beach', spots: [{ name: 'Bangla Road nightlife', tag: 'Nightlife' }, { name: 'Patong Beach sunsets', tag: 'Beach' }, { name: 'Parasailing & jet skis', tag: 'Adventure' }, { name: 'Jungceylon Mall', tag: 'Shopping' }, { name: 'Muay Thai stadiums', tag: 'Sport' }] },
      { name: 'Old Phuket Town', emoji: '🏛️', accentColor: '#8B5CF6', image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=600&q=80', tagline: 'Sino-Portuguese heritage', spots: [{ name: 'Thalang Road Sino-Portuguese architecture', tag: 'Heritage' }, { name: 'Sunday Walking Street', tag: 'Market' }, { name: 'Shrine of Serene Light', tag: 'Temple' }, { name: 'Artisan cafes & galleries', tag: 'Culture' }, { name: 'Phuket Museum', tag: 'History' }] },
      { name: 'Phi Phi Islands', emoji: '🏝️', accentColor: '#14B8A6', image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=600&q=80', tagline: 'Limestone cliffs & Maya Bay', spots: [{ name: 'Maya Bay (The Beach)', tag: 'Iconic' }, { name: 'Monkey Beach', tag: 'Wildlife' }, { name: 'Viking Cave', tag: 'Unique' }, { name: 'Pileh Lagoon', tag: 'Snorkeling' }, { name: 'Phi Phi Viewpoint', tag: 'Best view' }] },
      { name: 'Kata & Karon', emoji: '🌊', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=600&q=80', tagline: 'Family beaches & surf', spots: [{ name: 'Kata Beach surf school', tag: 'Surf' }, { name: 'Karon Beach (quiet)', tag: 'Peaceful' }, { name: 'Kata Viewpoint (3 bays)', tag: 'Views' }, { name: 'Tiger Kingdom', tag: 'Wildlife' }, { name: 'Big Buddha statue', tag: 'Landmark' }] },
    ],
  },
  {
    slug: 'chiang-mai', name: 'Chiang Mai', country: 'Thailand', flag: '🇹🇭',
    tagline: 'Rose of the North', gradient: 'from-amber-600 to-orange-500',
    accentColor: '#F59E0B', heroDescription: 'Northern Thailand\'s mountain capital — ancient walled city, over 300 temples, elephant sanctuaries, cooking schools, and a legendary Sunday Walking Street.',
    description: 'Chiang Mai is everything Bangkok isn\'t — slower, cooler, more spiritual, and completely charming. The old city moat, lantern festivals, and trekking make it unforgettable.',
    image: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Nov – Feb', budget: '$25–$80/day', language: 'Thai', currency: 'THB (Baht)' },
    vibes: ['Cultural', 'Adventure', 'Spiritual'],
    areas: [
      { name: 'Old City', emoji: '🏯', accentColor: '#F59E0B', image: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?auto=format&fit=crop&w=600&q=80', tagline: 'Ancient temples inside the moat', spots: [{ name: 'Wat Phra Singh Temple', tag: 'Must-see' }, { name: 'Wat Chedi Luang ruins', tag: 'History' }, { name: 'Three Kings Monument', tag: 'Landmark' }, { name: 'Tha Phae Gate', tag: 'Iconic' }, { name: 'Saturday Walking Street', tag: 'Market' }] },
      { name: 'Nimman (Nimmanhaemin)', emoji: '☕', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?auto=format&fit=crop&w=600&q=80', tagline: 'Digital nomads, cafes & art', spots: [{ name: 'Maya Mall rooftop', tag: 'Shopping' }, { name: 'Specialty coffee shops', tag: 'Cafes' }, { name: 'NIMMAN Art & Design', tag: 'Gallery' }, { name: 'Sunday brunch spots', tag: 'Brunch' }, { name: 'Boutique fashion stores', tag: 'Fashion' }] },
      { name: 'Doi Suthep', emoji: '🌄', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1568992688065-536aad8a12f6?auto=format&fit=crop&w=600&q=80', tagline: 'Sacred mountain temple', spots: [{ name: 'Wat Phra That Doi Suthep', tag: 'Sacred' }, { name: 'Hmong hill tribe village', tag: 'Culture' }, { name: 'Doi Inthanon National Park', tag: 'Nature' }, { name: 'Royal gardens', tag: 'Garden' }, { name: 'Forest hiking trails', tag: 'Hiking' }] },
    ],
  },

  // ── EUROPE ───────────────────────────────────────────────────────────────
  {
    slug: 'london', name: 'London', country: 'United Kingdom', flag: '🇬🇧',
    tagline: 'Where History Meets Now', gradient: 'from-blue-900 to-red-800',
    accentColor: '#1D4ED8', heroDescription: 'Eight royal parks, world\'s best museums (free), West End theatre, and a pub on every corner. London rewards repeat visitors — there is always more.',
    description: 'London is one of the world\'s great cities — endlessly layered, relentlessly diverse, and surprisingly green. Every neighbourhood has a distinct personality.',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'May – Sep', budget: '$120–$350/day', language: 'English', currency: 'GBP (Pound)' },
    vibes: ['Cultural', 'Foodie', 'Luxury'],
    areas: [
      { name: 'South Bank & Westminster', emoji: '🎡', accentColor: '#1D4ED8', image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80', tagline: 'Landmarks, museums & riverside walks', spots: [{ name: 'Big Ben & Houses of Parliament', tag: 'Iconic' }, { name: 'Tate Modern (free)', tag: 'Art' }, { name: 'Borough Market', tag: 'Food market' }, { name: 'London Eye', tag: 'Views' }, { name: 'Shakespeare\'s Globe Theatre', tag: 'Theatre' }] },
      { name: 'East London', emoji: '🎨', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80', tagline: 'Street art, markets & creativity', spots: [{ name: 'Brick Lane street art & bagels', tag: 'Culture' }, { name: 'Spitalfields Market', tag: 'Market' }, { name: 'Shoreditch bar scene', tag: 'Nightlife' }, { name: 'Columbia Road Flower Market (Sunday)', tag: 'Market' }, { name: 'Boxpark food market', tag: 'Food' }] },
      { name: 'Notting Hill & West', emoji: '🌸', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80', tagline: 'Pastel houses & Portobello Road', spots: [{ name: 'Portobello Road Market (Saturday)', tag: 'Antiques' }, { name: 'Hyde Park & Kensington Gardens', tag: 'Park' }, { name: 'V&A Museum (free)', tag: 'Museum' }, { name: 'Natural History Museum (free)', tag: 'Museum' }, { name: 'Holland Park peacocks', tag: 'Hidden gem' }] },
      { name: 'Covent Garden & West End', emoji: '🎭', accentColor: '#8B5CF6', image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80', tagline: 'Theatre, opera & street performers', spots: [{ name: 'West End theatre shows', tag: 'Must-do' }, { name: 'Covent Garden piazza', tag: 'Free entertainment' }, { name: 'National Gallery (free)', tag: 'Art' }, { name: 'Leicester Square cinemas', tag: 'Entertainment' }, { name: 'Seven Dials shopping', tag: 'Shopping' }] },
    ],
  },
  {
    slug: 'barcelona', name: 'Barcelona', country: 'Spain', flag: '🇪🇸',
    tagline: 'Gaudí\'s Playground', gradient: 'from-yellow-500 to-red-600',
    accentColor: '#EAB308', heroDescription: 'The most seductive city in Europe — Gaudí\'s impossible architecture, tapas from midnight, beaches in the middle of a cultural metropolis, and a football club that is more than a club.',
    description: 'Barcelona runs on its own clock. Lunch at 2pm, dinner at 10pm, and nightlife until dawn — in between, there\'s more art and architecture per square kilometre than almost anywhere.',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'May – Jun, Sep – Oct', budget: '$90–$220/day', language: 'Spanish, Catalan', currency: 'EUR (Euro)' },
    vibes: ['Cultural', 'Beach', 'Foodie'],
    areas: [
      { name: 'Gothic Quarter', emoji: '🏛️', accentColor: '#EAB308', image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=600&q=80', tagline: 'Medieval streets & hidden squares', spots: [{ name: 'Barcelona Cathedral', tag: 'Must-see' }, { name: 'Plaça Reial', tag: 'Square' }, { name: 'El Call (Jewish Quarter)', tag: 'History' }, { name: 'Pont del Bisbe bridge', tag: 'Photo spot' }, { name: 'La Boqueria market', tag: 'Food market' }] },
      { name: 'Eixample', emoji: '🎨', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=600&q=80', tagline: 'Gaudí masterpieces & fine dining', spots: [{ name: 'Sagrada Família', tag: 'Icon' }, { name: 'Casa Batlló', tag: 'Gaudí' }, { name: 'Casa Milà (La Pedrera)', tag: 'Gaudí' }, { name: 'Passeig de Gràcia', tag: 'Shopping' }, { name: 'Tapas restaurants', tag: 'Food' }] },
      { name: 'Barceloneta & Waterfront', emoji: '🏖️', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=600&q=80', tagline: 'Beach clubs & seafood', spots: [{ name: 'Barceloneta Beach', tag: 'Beach' }, { name: 'Port Olímpic restaurants', tag: 'Seafood' }, { name: 'W Barcelona hotel sky bar', tag: 'Views' }, { name: 'Aquarium Barcelona', tag: 'Family' }, { name: 'Frank Gehry\'s Fish sculpture', tag: 'Art' }] },
      { name: 'Gràcia', emoji: '🌿', accentColor: '#8B5CF6', image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=600&q=80', tagline: 'Bohemian village within the city', spots: [{ name: 'Park Güell (Gaudí)', tag: 'Must-see' }, { name: 'Plaça del Sol (evening drinks)', tag: 'Local vibe' }, { name: 'Mercat de l\'Abaceria', tag: 'Market' }, { name: 'Verdi cinema district', tag: 'Indie film' }, { name: 'Fontana neighbourhood bars', tag: 'Nightlife' }] },
    ],
  },
  {
    slug: 'rome', name: 'Rome', country: 'Italy', flag: '🇮🇹',
    tagline: 'Eternal City', gradient: 'from-amber-700 to-red-600',
    accentColor: '#B45309', heroDescription: 'Two thousand years of history on every street corner. The Colosseum at sunset, carbonara at a red-checked tablecloth trattoria, and three coins in the Trevi Fountain.',
    description: 'Rome is overwhelming in the best way — every piazza has a fountain, every church has a Caravaggio, and every meal is the best you\'ve ever had.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Apr – Jun, Sep – Oct', budget: '$100–$250/day', language: 'Italian', currency: 'EUR (Euro)' },
    vibes: ['Cultural', 'Romantic', 'Foodie'],
    areas: [
      { name: 'Ancient Rome', emoji: '🏛️', accentColor: '#B45309', image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80', tagline: '2,000 years in one neighbourhood', spots: [{ name: 'Colosseum', tag: 'Book ahead' }, { name: 'Roman Forum', tag: 'Must-see' }, { name: 'Palatine Hill', tag: 'Views' }, { name: 'Circus Maximus', tag: 'Free' }, { name: 'Capitoline Museums', tag: 'Museum' }] },
      { name: 'Vatican City', emoji: '⛪', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80', tagline: 'St Peter\'s & the Sistine Chapel', spots: [{ name: 'St Peter\'s Basilica (free)', tag: 'Must-see' }, { name: 'Sistine Chapel', tag: 'Book ahead' }, { name: 'Vatican Museums', tag: 'Museum' }, { name: 'Castel Sant\'Angelo', tag: 'Fortress' }, { name: 'Via della Conciliazione', tag: 'Photo spot' }] },
      { name: 'Trastevere', emoji: '🍝', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80', tagline: 'Rome\'s most charming neighbourhood', spots: [{ name: 'Santa Maria in Trastevere', tag: 'Church' }, { name: 'Piazza di Santa Maria', tag: 'Square' }, { name: 'Trattorias & wine bars', tag: 'Food' }, { name: 'Janiculum Hill views', tag: 'Views' }, { name: 'Nightlife & aperitivo', tag: 'Evening' }] },
      { name: 'Centro Storico', emoji: '⛲', accentColor: '#8B5CF6', image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80', tagline: 'Fountains, piazzas & gelato', spots: [{ name: 'Trevi Fountain', tag: 'Iconic' }, { name: 'Spanish Steps', tag: 'Landmark' }, { name: 'Piazza Navona', tag: 'Square' }, { name: 'Pantheon (free AM)', tag: 'Must-see' }, { name: 'Campo de\' Fiori market', tag: 'Market' }] },
    ],
  },
  {
    slug: 'amsterdam', name: 'Amsterdam', country: 'Netherlands', flag: '🇳🇱',
    tagline: 'Venice of the North', gradient: 'from-red-600 to-blue-600',
    accentColor: '#EF4444', heroDescription: 'Golden Age canal houses, 800,000 bicycles, world-class art, and a liberalism that dates back 400 years. Amsterdam rewards slow exploration by bike and boat.',
    description: 'Amsterdam is perfectly human-scaled — easily walkable, bikeable, and surprisingly intimate despite its international fame. The Jordaan and Vondelpark are its warm heart.',
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Apr – May, Sep', budget: '$100–$250/day', language: 'Dutch, English', currency: 'EUR (Euro)' },
    vibes: ['Cultural', 'Romantic', 'Bohemian'],
    areas: [
      { name: 'Museum Quarter', emoji: '🎨', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=600&q=80', tagline: 'Rijksmuseum & Van Gogh', spots: [{ name: 'Rijksmuseum', tag: 'Must-see' }, { name: 'Van Gogh Museum', tag: 'Book ahead' }, { name: 'Stedelijk Museum', tag: 'Modern art' }, { name: 'Vondelpark', tag: 'Free' }, { name: 'Museumplein square', tag: 'Landmark' }] },
      { name: 'Jordaan', emoji: '🌷', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=600&q=80', tagline: 'Cozy canals & independent shops', spots: [{ name: 'Noordermarkt Saturday market', tag: 'Market' }, { name: 'Anne Frank House', tag: 'Unmissable' }, { name: 'Westerkerk church', tag: 'Tower views' }, { name: 'Boutique shops & galleries', tag: 'Shopping' }, { name: 'Brown cafes (bruine kroegen)', tag: 'Bars' }] },
      { name: 'Oud-Zuid & De Pijp', emoji: '🍺', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=600&q=80', tagline: 'Albert Cuyp Market & young Amsterdam', spots: [{ name: 'Albert Cuyp Market (daily)', tag: 'Best market' }, { name: 'Heineken Experience', tag: 'Tour' }, { name: 'Sarphatipark', tag: 'Local park' }, { name: 'Gerard Douplein bar street', tag: 'Nightlife' }, { name: 'Dutch cheese shops', tag: 'Food' }] },
    ],
  },
  {
    slug: 'prague', name: 'Prague', country: 'Czech Republic', flag: '🇨🇿',
    tagline: 'City of a Hundred Spires', gradient: 'from-blue-800 to-red-700',
    accentColor: '#1E40AF', heroDescription: 'Europe\'s most fairy-tale city — medieval Old Town, a castle on a hill, Charles Bridge at dawn, and world\'s best beer in a cellar bar below cobblestone streets.',
    description: 'Prague survived the 20th century\'s wars almost intact, leaving it one of Europe\'s most beautifully preserved capitals — and now one of its most visited.',
    image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'May – Jun, Sep – Oct', budget: '$60–$150/day', language: 'Czech', currency: 'CZK (Koruna)' },
    vibes: ['Cultural', 'Romantic', 'Bohemian'],
    areas: [
      { name: 'Old Town (Staré Město)', emoji: '🏰', accentColor: '#1E40AF', image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=600&q=80', tagline: 'Astronomical clock & Gothic squares', spots: [{ name: 'Old Town Square & Astronomical Clock', tag: 'Iconic' }, { name: 'Charles Bridge at dawn', tag: 'Must-do' }, { name: 'Church of Our Lady before Týn', tag: 'Gothic' }, { name: 'Old Jewish Cemetery', tag: 'History' }, { name: 'Franz Kafka Museum', tag: 'Museum' }] },
      { name: 'Prague Castle & Hradčany', emoji: '⚔️', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=600&q=80', tagline: 'Europe\'s largest castle complex', spots: [{ name: 'Prague Castle (largest in world)', tag: 'Must-see' }, { name: 'St Vitus Cathedral', tag: 'Cathedral' }, { name: 'Golden Lane', tag: 'Medieval' }, { name: 'Lobkowicz Palace', tag: 'Museum' }, { name: 'View over red rooftops', tag: 'Best view' }] },
      { name: 'Malá Strana', emoji: '🌹', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=600&q=80', tagline: 'Baroque palaces & garden terraces', spots: [{ name: 'St Nicholas Church', tag: 'Baroque' }, { name: 'Kampa Island art museum', tag: 'Art' }, { name: 'Lennon Wall', tag: 'Street art' }, { name: 'Vrtba Garden (terraced)', tag: 'Garden' }, { name: 'Local restaurants on cobblestones', tag: 'Dining' }] },
    ],
  },
  {
    slug: 'lisbon', name: 'Lisbon', country: 'Portugal', flag: '🇵🇹',
    tagline: 'City of Seven Hills', gradient: 'from-yellow-600 to-green-700',
    accentColor: '#D97706', heroDescription: 'Fado music drifting from tiled buildings, custard tarts at every pastelaria, and the world\'s most melancholic yet joyful city — Lisbon gets under your skin fast.',
    description: 'Lisbon is having its cultural moment and deservedly so — beautiful hilltop viewpoints, exceptional food and wine, warm people, and year-round sunshine.',
    image: 'https://images.unsplash.com/photo-1588693590563-0a4a6e4ea462?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1588693590563-0a4a6e4ea462?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Mar – May, Sep – Oct', budget: '$80–$180/day', language: 'Portuguese', currency: 'EUR (Euro)' },
    vibes: ['Cultural', 'Foodie', 'Romantic'],
    areas: [
      { name: 'Alfama', emoji: '🎵', accentColor: '#D97706', image: 'https://images.unsplash.com/photo-1588693590563-0a4a6e4ea462?auto=format&fit=crop&w=600&q=80', tagline: 'Fado, castle & tiled houses', spots: [{ name: 'São Jorge Castle', tag: 'Hilltop fortress' }, { name: 'Portas do Sol viewpoint', tag: 'Views' }, { name: 'Fado restaurant evenings', tag: 'Must-do' }, { name: 'LX Factory market (Sunday)', tag: 'Market' }, { name: 'Museu do Azulejo (tile museum)', tag: 'Museum' }] },
      { name: 'Belém', emoji: '⛵', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1588693590563-0a4a6e4ea462?auto=format&fit=crop&w=600&q=80', tagline: 'Discoverers\' monuments & pastéis', spots: [{ name: 'Pastéis de Belém (original custard tarts)', tag: 'Must-eat' }, { name: 'Jerónimos Monastery', tag: 'UNESCO' }, { name: 'Torre de Belém', tag: 'Iconic' }, { name: 'Monument to the Discoveries', tag: 'Landmark' }, { name: 'MAAT Museum', tag: 'Modern art' }] },
      { name: 'Chiado & Bairro Alto', emoji: '🍷', accentColor: '#8B5CF6', image: 'https://images.unsplash.com/photo-1588693590563-0a4a6e4ea462?auto=format&fit=crop&w=600&q=80', tagline: 'Literary cafes & late-night wine bars', spots: [{ name: 'A Brasileira cafe (Fernando Pessoa\'s table)', tag: 'Historic cafe' }, { name: 'Livraria Bertrand (world\'s oldest bookshop)', tag: 'Unique' }, { name: 'Bairro Alto wine bars', tag: 'Nightlife' }, { name: 'Príncipe Real antiques', tag: 'Shopping' }, { name: 'Miradouro de São Pedro viewpoint', tag: 'Views' }] },
    ],
  },
  {
    slug: 'istanbul', name: 'Istanbul', country: 'Turkey', flag: '🇹🇷',
    tagline: 'Where East Meets West', gradient: 'from-red-700 to-amber-600',
    accentColor: '#DC2626', heroDescription: 'The only city on two continents — Byzantine mosaics in one church, Ottoman domes in the next, bazaars selling everything, and the Bosphorus connecting it all.',
    description: 'Istanbul is a city that has been the centre of three empires, and it shows — layers of history, cuisine, and culture stack up in a city that never quite settles.',
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Apr – Jun, Sep – Oct', budget: '$40–$120/day', language: 'Turkish', currency: 'TRY (Lira)' },
    vibes: ['Cultural', 'Foodie', 'Adventure'],
    areas: [
      { name: 'Sultanahmet', emoji: '🕌', accentColor: '#DC2626', image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=600&q=80', tagline: 'Byzantine & Ottoman masterpieces', spots: [{ name: 'Hagia Sophia', tag: 'Must-see' }, { name: 'Blue Mosque (Sultanahmet Mosque)', tag: 'Iconic' }, { name: 'Topkapi Palace', tag: 'Palace museum' }, { name: 'Basilica Cistern underground', tag: 'Unique' }, { name: 'Grand Bazaar (4,400 shops)', tag: 'Shopping' }] },
      { name: 'Beyoglu & Istiklal', emoji: '🎭', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=600&q=80', tagline: 'Modern Istanbul & pedestrian boulevard', spots: [{ name: 'Istiklal Street', tag: 'Promenade' }, { name: 'Galata Tower', tag: 'Views' }, { name: 'Spice Bazaar (Mısır Çarşısı)', tag: 'Market' }, { name: 'Balık ekmek (fish sandwiches)', tag: 'Street food' }, { name: 'Pera Museum', tag: 'Art' }] },
      { name: 'Kadiköy (Asian side)', emoji: '⚓', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=600&q=80', tagline: 'Real Istanbul on the Asian shore', spots: [{ name: 'Kadıköy market (Tuesday)', tag: 'Local market' }, { name: 'Moda coastal walk', tag: 'Scenic' }, { name: 'Street food & meyhanes', tag: 'Food' }, { name: 'Bosphorus ferry crossing', tag: 'Experience' }, { name: 'Çiya Sofrası restaurant', tag: 'Best food' }] },
    ],
  },
  {
    slug: 'athens', name: 'Athens', country: 'Greece', flag: '🇬🇷',
    tagline: 'Cradle of Civilization', gradient: 'from-blue-600 to-white',
    accentColor: '#2563EB', heroDescription: 'The Acropolis at dawn, cold Mythos beer on a rooftop with the Parthenon glowing above — Athens is simultaneously ancient and alive, chaotic and beautiful.',
    description: 'Athens gets better with every visit — the archaeological sites are world-class, the food scene has transformed, and the neighbourhoods beyond the tourist trail are genuinely wonderful.',
    image: 'https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Apr – Jun, Sep – Oct', budget: '$70–$160/day', language: 'Greek', currency: 'EUR (Euro)' },
    vibes: ['Cultural', 'Foodie', 'Adventure'],
    areas: [
      { name: 'Acropolis & Plaka', emoji: '🏛️', accentColor: '#2563EB', image: 'https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=600&q=80', tagline: '2,500 years of Western civilization', spots: [{ name: 'Acropolis & Parthenon', tag: 'Must-see' }, { name: 'Acropolis Museum', tag: 'World-class' }, { name: 'Plaka old neighbourhood', tag: 'Charming' }, { name: 'Ancient Agora', tag: 'Ruins' }, { name: 'Monastiraki Flea Market', tag: 'Market' }] },
      { name: 'Monastiraki & Psiri', emoji: '☕', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=600&q=80', tagline: 'Rooftop bars & souvlaki', spots: [{ name: 'Monastiraki Square', tag: 'Landmark' }, { name: 'Acropolis rooftop views', tag: 'Best view' }, { name: 'Souvlaki restaurants', tag: 'Food' }, { name: 'Flea market browsing', tag: 'Shopping' }, { name: 'Psiri nightlife', tag: 'Nightlife' }] },
      { name: 'Exarcheia & Kolonaki', emoji: '🍷', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=600&q=80', tagline: 'Student bars & upscale dining', spots: [{ name: 'National Archaeological Museum (free)', tag: 'Best in world' }, { name: 'Exarcheia square bars', tag: 'Bohemian' }, { name: 'Kolonaki boutiques', tag: 'Fashion' }, { name: 'Benaki Museum', tag: 'Museum' }, { name: 'Strefi Hill sunset', tag: 'Free views' }] },
    ],
  },
  {
    slug: 'budapest', name: 'Budapest', country: 'Hungary', flag: '🇭🇺',
    tagline: 'Pearl of the Danube', gradient: 'from-red-600 to-green-700',
    accentColor: '#DC2626', heroDescription: 'Thermal baths, ruin bars, Habsburg grandeur, and a Parliament building that rivals anything in Europe. Budapest is Europe\'s most underrated great capital.',
    description: 'Budapest is two cities in one — hilly Buda on the west bank, flat Pest on the east. The Danube between them creates one of the world\'s great urban vistas.',
    image: 'https://images.unsplash.com/photo-1541732648377-b2f0f1b6a082?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1541732648377-b2f0f1b6a082?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Apr – Jun, Sep – Oct', budget: '$50–$130/day', language: 'Hungarian', currency: 'HUF (Forint)' },
    vibes: ['Cultural', 'Bohemian', 'Romantic'],
    areas: [
      { name: 'Buda Castle & Castle Hill', emoji: '🏰', accentColor: '#DC2626', image: 'https://images.unsplash.com/photo-1541732648377-b2f0f1b6a082?auto=format&fit=crop&w=600&q=80', tagline: 'Castle, views & Fisherman\'s Bastion', spots: [{ name: 'Buda Castle', tag: 'Must-see' }, { name: 'Fisherman\'s Bastion', tag: 'Iconic view' }, { name: 'Matthias Church', tag: 'Church' }, { name: 'Funicular up Castle Hill', tag: 'Experience' }, { name: 'Danube panorama', tag: 'Best view' }] },
      { name: 'Pest & Parliament', emoji: '🏛️', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1541732648377-b2f0f1b6a082?auto=format&fit=crop&w=600&q=80', tagline: 'Grand boulevards & Parliament', spots: [{ name: 'Hungarian Parliament Building', tag: 'Iconic' }, { name: 'St Stephen\'s Basilica', tag: 'Church' }, { name: 'Andrássy Avenue', tag: 'Boulevard' }, { name: 'Heroes\' Square', tag: 'Landmark' }, { name: 'Great Market Hall', tag: 'Market' }] },
      { name: 'Jewish Quarter & Ruin Bars', emoji: '🍻', accentColor: '#8B5CF6', image: 'https://images.unsplash.com/photo-1541732648377-b2f0f1b6a082?auto=format&fit=crop&w=600&q=80', tagline: 'Quirky bars in derelict buildings', spots: [{ name: 'Szimpla Kert (original ruin bar)', tag: 'Iconic' }, { name: 'Great Synagogue', tag: 'Europe\'s largest' }, { name: 'Gozsdu Courtyard', tag: 'Food & bars' }, { name: 'Kazinczy Street bars', tag: 'Nightlife' }, { name: 'Cserzy Mihály street food', tag: 'Local food' }] },
      { name: 'Thermal Baths', emoji: '♨️', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1541732648377-b2f0f1b6a082?auto=format&fit=crop&w=600&q=80', tagline: 'Budapest\'s thermal spa tradition', spots: [{ name: 'Széchenyi Thermal Bath', tag: 'Most famous' }, { name: 'Gellért Baths (most beautiful)', tag: 'Art Nouveau' }, { name: 'Rudas Baths (Turkish, 16th c)', tag: 'Historic' }, { name: 'Lukács Baths (local favourite)', tag: 'Local' }, { name: 'Bath party at Széchenyi', tag: 'Party' }] },
    ],
  },

  // ── AMERICAS ─────────────────────────────────────────────────────────────
  {
    slug: 'new-york', name: 'New York', country: 'USA', flag: '🇺🇸',
    tagline: 'The City That Never Sleeps', gradient: 'from-blue-600 to-slate-800',
    accentColor: '#1D4ED8', heroDescription: 'Central Park, the High Line, a different world cuisine on every block, Broadway, and a skyline that still takes your breath away every time. There is nowhere else like it.',
    description: 'New York City operates at a frequency unlike anywhere else — more energy, more variety, more ambition per square mile than any place on earth.',
    image: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Apr – Jun, Sep – Oct', budget: '$150–$400/day', language: 'English', currency: 'USD' },
    vibes: ['Cultural', 'Foodie', 'Adventure'],
    areas: [
      { name: 'Manhattan', emoji: '🗽', accentColor: '#1D4ED8', image: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=600&q=80', tagline: 'The world\'s most famous island', spots: [{ name: 'Central Park', tag: 'Free' }, { name: 'Times Square', tag: 'Iconic' }, { name: 'The High Line park', tag: 'Must-walk' }, { name: 'MoMA (Modern Art)', tag: 'Museum' }, { name: 'Empire State Building views', tag: 'Views' }] },
      { name: 'Brooklyn', emoji: '🎸', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=600&q=80', tagline: 'DUMBO, Williamsburg & food scene', spots: [{ name: 'Brooklyn Bridge walk', tag: 'Free & iconic' }, { name: 'DUMBO art galleries & views', tag: 'Neighbourhood' }, { name: 'Smorgasburg food market (weekends)', tag: 'Food' }, { name: 'Prospect Park', tag: 'Park' }, { name: 'Brooklyn Museum', tag: 'Museum' }] },
      { name: 'Midtown South', emoji: '🌆', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=600&q=80', tagline: 'Chelsea, Flatiron & SoHo', spots: [{ name: 'Chelsea Market', tag: 'Food hall' }, { name: 'Flatiron Building photo', tag: 'Landmark' }, { name: 'SoHo designer shopping', tag: 'Shopping' }, { name: 'Little Italy & Nolita', tag: 'Food' }, { name: 'Whitney Museum', tag: 'Art' }] },
    ],
  },
  {
    slug: 'mexico-city', name: 'Mexico City', country: 'Mexico', flag: '🇲🇽',
    tagline: 'Capital of the Sun', gradient: 'from-green-600 to-red-600',
    accentColor: '#16A34A', heroDescription: 'One of the world\'s great capitals — Aztec ruins beneath Spanish churches, the finest Mexican food in the world, world-class art, and a cultural energy that never stops.',
    description: 'Mexico City (CDMX) is having a golden moment — a booming food scene, extraordinary museums, Frida Kahlo\'s house, and trendy neighbourhoods that rival any city on earth.',
    image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Mar – May, Oct – Nov', budget: '$40–$120/day', language: 'Spanish', currency: 'MXN (Peso)' },
    vibes: ['Cultural', 'Foodie', 'Adventure'],
    areas: [
      { name: 'Centro Histórico', emoji: '⛪', accentColor: '#16A34A', image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=600&q=80', tagline: 'Aztec, colonial & modern history', spots: [{ name: 'Zócalo (main square)', tag: 'Iconic' }, { name: 'Templo Mayor Aztec ruins', tag: 'Must-see' }, { name: 'Metropolitan Cathedral', tag: 'Cathedral' }, { name: 'Palacio de Bellas Artes', tag: 'Art' }, { name: 'Diego Rivera murals (Palacio Nacional)', tag: 'Art' }] },
      { name: 'Roma & Condesa', emoji: '☕', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=600&q=80', tagline: 'Art deco, cafes & restaurants', spots: [{ name: 'Parque México', tag: 'Park' }, { name: 'Mercado Medellín', tag: 'Market' }, { name: 'Specialty coffee scene', tag: 'Cafes' }, { name: 'Restaurant row on Álvaro Obregón', tag: 'Food' }, { name: 'Art deco architecture', tag: 'Architecture' }] },
      { name: 'Coyoacán', emoji: '🎨', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=600&q=80', tagline: 'Frida Kahlo\'s neighbourhood', spots: [{ name: 'Museo Frida Kahlo (La Casa Azul)', tag: 'Must-see' }, { name: 'Mercado de Coyoacán', tag: 'Market' }, { name: 'Jardín Centenario square', tag: 'Charming' }, { name: 'Trotsky Museum', tag: 'History' }, { name: 'Cafes & artisan shops', tag: 'Shopping' }] },
    ],
  },
  {
    slug: 'rio-de-janeiro', name: 'Rio de Janeiro', country: 'Brazil', flag: '🇧🇷',
    tagline: 'Marvelous City', gradient: 'from-green-600 to-yellow-500',
    accentColor: '#16A34A', heroDescription: 'Christ the Redeemer watching over golden beaches, samba schools rehearsing in favelas, and the most dramatic urban setting on earth. Rio is sensory overload in the best way.',
    description: 'Rio is breathtaking — the mountains, the ocean, the forest, and the city all collide in a way that no other place manages. Copacabana, Ipanema, and the Sugarloaf are just the beginning.',
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'May – Sep', budget: '$50–$150/day', language: 'Portuguese', currency: 'BRL (Real)' },
    vibes: ['Beach', 'Adventure', 'Cultural'],
    areas: [
      { name: 'Copacabana & Ipanema', emoji: '🏖️', accentColor: '#16A34A', image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=600&q=80', tagline: 'World\'s most famous beaches', spots: [{ name: 'Copacabana Beach (4km)', tag: 'Iconic' }, { name: 'Ipanema Beach (most beautiful)', tag: 'Beach' }, { name: 'Feira Hippie Ipanema (Sunday market)', tag: 'Market' }, { name: 'Leblon bars & restaurants', tag: 'Dining' }, { name: 'Arpoador sunset rock', tag: 'Free views' }] },
      { name: 'Santa Teresa & Lapa', emoji: '🎸', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=600&q=80', tagline: 'Artists, samba & colonial charm', spots: [{ name: 'Escadaria Selarón (tiled steps)', tag: 'Must-see' }, { name: 'Lapa Arches', tag: 'Iconic' }, { name: 'Forró & samba clubs (Thursday+)', tag: 'Nightlife' }, { name: 'Santa Teresa tram ride', tag: 'Experience' }, { name: 'Museu Chácara do Céu', tag: 'Art' }] },
      { name: 'Cristo & Sugarloaf', emoji: '🏔️', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=600&q=80', tagline: 'Rio\'s iconic viewpoints', spots: [{ name: 'Christ the Redeemer', tag: 'Must-do' }, { name: 'Sugarloaf Mountain cable car', tag: 'Iconic' }, { name: 'Tijuca National Forest', tag: 'Nature' }, { name: 'Pão de Açúcar sunset', tag: 'Best views' }, { name: 'Hang gliding from Pedra Bonita', tag: 'Adventure' }] },
    ],
  },
  {
    slug: 'buenos-aires', name: 'Buenos Aires', country: 'Argentina', flag: '🇦🇷',
    tagline: 'Paris of South America', gradient: 'from-blue-600 to-white',
    accentColor: '#2563EB', heroDescription: 'Tango in the streets, football religion, the best steakhouses on earth, and a European-influenced elegance in a city that knows how to throw a party.',
    description: 'Buenos Aires is a city that lives at night — late dinners at midnight, milongas (tango halls) until 5am, and the kind of conversation that goes until the sun comes up.',
    image: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Mar – May, Sep – Nov', budget: '$40–$120/day', language: 'Spanish', currency: 'ARS (Peso)' },
    vibes: ['Cultural', 'Foodie', 'Romantic'],
    areas: [
      { name: 'San Telmo & La Boca', emoji: '💃', accentColor: '#2563EB', image: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=600&q=80', tagline: 'Tango, antiques & colourful Caminito', spots: [{ name: 'El Caminito colourful street', tag: 'Iconic' }, { name: 'San Telmo Sunday market', tag: 'Antiques' }, { name: 'Milonga tango halls', tag: 'Culture' }, { name: 'La Boca street tango', tag: 'Free' }, { name: 'Mercado de San Telmo', tag: 'Food market' }] },
      { name: 'Palermo', emoji: '🌿', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=600&q=80', tagline: 'Parks, restaurants & boutiques', spots: [{ name: 'Palermo Soho boutiques', tag: 'Fashion' }, { name: 'Parque Tres de Febrero', tag: 'Park' }, { name: 'MALBA Modern Art Museum', tag: 'Art' }, { name: 'Restaurant row (Nicaragua/Armenia)', tag: 'Food' }, { name: 'Weekend street markets', tag: 'Markets' }] },
      { name: 'Recoleta', emoji: '🏛️', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=600&q=80', tagline: 'Evita\'s tomb & elegant boulevards', spots: [{ name: 'Recoleta Cemetery (Evita\'s tomb)', tag: 'Must-see' }, { name: 'National Museum of Fine Arts', tag: 'Museum' }, { name: 'Floralis Genérica steel flower', tag: 'Landmark' }, { name: 'Recoleta Cultural Centre', tag: 'Culture' }, { name: 'Buenos Aires Design mall', tag: 'Design' }] },
    ],
  },
  {
    slug: 'marrakech', name: 'Marrakech', country: 'Morocco', flag: '🇲🇦',
    tagline: 'Red City of the Atlas', gradient: 'from-red-700 to-orange-500',
    accentColor: '#B91C1C', heroDescription: 'The most overwhelming sensory experience in travel — snake charmers in the main square, souks where you can get lost for hours, and riads with rooftop gardens hidden behind blank walls.',
    description: 'Marrakech operates at a frequency of pure intensity. The medina is a UNESCO-protected labyrinth; beyond it, the Sahara, the Atlas Mountains, and villages unchanged for centuries.',
    image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Mar – May, Sep – Nov', budget: '$40–$150/day', language: 'Arabic, French, Berber', currency: 'MAD (Dirham)' },
    vibes: ['Cultural', 'Adventure', 'Spiritual'],
    areas: [
      { name: 'Medina & Djemaa el-Fna', emoji: '🕌', accentColor: '#B91C1C', image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=600&q=80', tagline: 'The ancient walled city', spots: [{ name: 'Djemaa el-Fna square (evening)', tag: 'Iconic' }, { name: 'Koutoubia Mosque', tag: 'Landmark' }, { name: 'Ben Youssef Medersa', tag: 'Architecture' }, { name: 'Bahia Palace', tag: 'Palace' }, { name: 'El Badi Palace ruins', tag: 'History' }] },
      { name: 'Souks', emoji: '🧿', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=600&q=80', tagline: 'Labyrinthine markets of colour', spots: [{ name: 'Souk Semmarine (main souk)', tag: 'Shopping' }, { name: 'Leather tanneries (Chouara)', tag: 'Unique' }, { name: 'Spice market', tag: 'Aromas' }, { name: 'Carpet souk (bargain hard)', tag: 'Rugs' }, { name: 'Lamp & lantern souk', tag: 'Artisan' }] },
      { name: 'Majorelle Garden & Gueliz', emoji: '🌺', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=600&q=80', tagline: 'Yves Saint Laurent\'s garden & new town', spots: [{ name: 'Jardin Majorelle (YSL garden)', tag: 'Must-see' }, { name: 'Yves Saint Laurent Museum', tag: 'Fashion art' }, { name: 'Gueliz modern restaurants', tag: 'Dining' }, { name: 'Carré Eden mall', tag: 'Shopping' }, { name: 'Agdal Gardens', tag: 'Park' }] },
    ],
  },
  {
    slug: 'cape-town', name: 'Cape Town', country: 'South Africa', flag: '🇿🇦',
    tagline: 'Mother City', gradient: 'from-blue-600 to-green-600',
    accentColor: '#2563EB', heroDescription: 'Table Mountain watching over Camps Bay beach, Cape Point where two oceans meet, penguins on Boulders Beach, and one of the world\'s great wine regions an hour away.',
    description: 'Cape Town is Africa\'s most beautiful city — dramatically set between mountains and two oceans, with exceptional food, wine, and a complexity that rewards deep exploration.',
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Nov – Mar', budget: '$60–$180/day', language: 'English, Afrikaans, Xhosa', currency: 'ZAR (Rand)' },
    vibes: ['Adventure', 'Beach', 'Cultural'],
    areas: [
      { name: 'Table Mountain & City Bowl', emoji: '🏔️', accentColor: '#2563EB', image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=600&q=80', tagline: 'The icon & the city centre', spots: [{ name: 'Table Mountain cable car', tag: 'Must-do' }, { name: 'Signal Hill sunset', tag: 'Free views' }, { name: 'Company\'s Garden', tag: 'Park' }, { name: 'Bo-Kaap colourful quarter', tag: 'Iconic' }, { name: 'South African Museum (free)', tag: 'Museum' }] },
      { name: 'Camps Bay & Atlantic Seaboard', emoji: '🌊', accentColor: '#00C9A7', image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=600&q=80', tagline: 'Most beautiful beach strip in Africa', spots: [{ name: 'Camps Bay Beach', tag: 'Beach' }, { name: 'Clifton 4th Beach', tag: 'Exclusive' }, { name: 'Chapman\'s Peak Drive', tag: 'Scenic drive' }, { name: 'V&A Waterfront', tag: 'Dining & shopping' }, { name: 'Sunset drinks on Strip', tag: 'Evening' }] },
      { name: 'Cape Winelands', emoji: '🍷', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=600&q=80', tagline: 'Stellenbosch, Franschhoek & world-class wine', spots: [{ name: 'Stellenbosch wine estates', tag: 'Wine tasting' }, { name: 'Franschhoek (gourmet capital)', tag: 'Fine dining' }, { name: 'Paarl & Pearl Mountain', tag: 'Views' }, { name: 'Wine tram Franschhoek', tag: 'Experience' }, { name: 'Cape Point & two oceans', tag: 'Nature' }] },
    ],
  },
  // Maldives
  {
    slug: 'maldives', name: 'Maldives', country: 'Maldives', flag: '🇲🇻',
    tagline: 'Last Paradise on Earth', gradient: 'from-teal-400 to-blue-600',
    accentColor: '#0D9488', heroDescription: 'Overwater bungalows, the clearest water in the world, house reef snorkelling before breakfast, and a sky full of stars after dinner. The Maldives delivers exactly what it promises.',
    description: 'The Maldives is 1,200 coral islands spread across the Indian Ocean — every resort is its own island, and the lagoon colours are unlike anything else on earth.',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'Nov – Apr', budget: '$200–$1,500/day', language: 'Dhivehi, English', currency: 'MVR (Rufiyaa)' },
    vibes: ['Luxury', 'Romantic', 'Beach'],
    areas: [
      { name: 'Male & Hulhumale', emoji: '🏙️', accentColor: '#0D9488', image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=600&q=80', tagline: 'Capital city & transit hub', spots: [{ name: 'Male Friday Mosque', tag: 'Historic' }, { name: 'Fish Market at sunrise', tag: 'Local' }, { name: 'National Museum', tag: 'Museum' }, { name: 'Hulhumale beach', tag: 'Budget option' }, { name: 'Local guesthouses', tag: 'Budget stay' }] },
      { name: 'North Malé Atoll', emoji: '🤿', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=600&q=80', tagline: 'Top dive sites & luxury resorts', spots: [{ name: 'Banana Reef (best dive)', tag: 'Diving' }, { name: 'Manta Point snorkelling', tag: 'Wildlife' }, { name: 'Maafushi local island', tag: 'Budget' }, { name: 'Vaadhoo (bioluminescent beach)', tag: 'Magical' }, { name: 'Overwater bungalow resorts', tag: 'Luxury' }] },
      { name: 'Baa Atoll (UNESCO)', emoji: '🐋', accentColor: '#8B5CF6', image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=600&q=80', tagline: 'Whale sharks & manta rays', spots: [{ name: 'Hanifaru Bay (manta sanctuary)', tag: 'UNESCO' }, { name: 'Whale shark snorkelling', tag: 'Wildlife' }, { name: 'Dharavandhoo local island', tag: 'Local' }, { name: 'Bioluminescence beach nights', tag: 'Magical' }, { name: 'Coral restoration projects', tag: 'Eco' }] },
    ],
  },
  // Santorini
  {
    slug: 'santorini', name: 'Santorini', country: 'Greece', flag: '🇬🇷',
    tagline: 'Jewel of the Aegean', gradient: 'from-blue-500 to-white',
    accentColor: '#3B82F6', heroDescription: 'The world\'s most photographed sunset, white-washed clifftop villages, black-sand beaches, and red-domed churches above the caldera. Santorini is exactly as beautiful as the pictures suggest.',
    description: 'Santorini is the iconic Greek island — formed by a massive volcanic eruption, its crescent shape creates the spectacular caldera views that have made it world-famous.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'May – Jun, Sep – Oct', budget: '$150–$500/day', language: 'Greek, English', currency: 'EUR (Euro)' },
    vibes: ['Romantic', 'Luxury', 'Beach'],
    areas: [
      { name: 'Oia', emoji: '🌅', accentColor: '#3B82F6', image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=600&q=80', tagline: 'Santorini\'s famous sunset village', spots: [{ name: 'Castle of Oia sunset spot', tag: 'Iconic sunset' }, { name: 'Caldera cliff walk', tag: 'Scenic' }, { name: 'Blue domed churches photo', tag: 'Must-photo' }, { name: 'Boutique shops & galleries', tag: 'Shopping' }, { name: 'Cave houses & luxury hotels', tag: 'Unique stay' }] },
      { name: 'Fira & Firostefani', emoji: '🏛️', accentColor: '#FFD166', image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=600&q=80', tagline: 'Capital & caldera rim walks', spots: [{ name: 'Caldera rim walk (Fira to Oia)', tag: 'Best walk' }, { name: 'Museum of Prehistoric Thera', tag: 'Museum' }, { name: 'Cable car up from port', tag: 'Experience' }, { name: 'Restaurants over the caldera', tag: 'Dining' }, { name: 'Archaeological site of Akrotiri', tag: 'Must-see' }] },
      { name: 'Beaches', emoji: '🏖️', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=600&q=80', tagline: 'Volcanic beaches unique to Santorini', spots: [{ name: 'Red Beach (stunning cliffs)', tag: 'Unique' }, { name: 'Black Perissa Beach', tag: 'Black sand' }, { name: 'Kamari Beach', tag: 'Popular' }, { name: 'White Beach (boat access)', tag: 'Remote' }, { name: 'Hot springs boat trip', tag: 'Volcano' }] },
    ],
  },
  // Cusco / Machu Picchu
  {
    slug: 'cusco', name: 'Cusco', country: 'Peru', flag: '🇵🇪',
    tagline: 'Gateway to Machu Picchu', gradient: 'from-amber-700 to-red-700',
    accentColor: '#D97706', heroDescription: 'The former Inca capital at 3,400m — colonial Spanish churches built on Inca foundations, the Sacred Valley, Rainbow Mountain, and the lost city of Machu Picchu.',
    description: 'Cusco is extraordinary in its own right beyond Machu Picchu — the Plaza de Armas, Sacsayhuamán ruins, and San Pedro Market make it a destination for days, not just a transfer point.',
    image: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=1600&q=85',
    stats: { bestTime: 'May – Sep (dry)', budget: '$40–$120/day', language: 'Spanish, Quechua', currency: 'PEN (Sol)' },
    vibes: ['Adventure', 'Cultural', 'Spiritual'],
    areas: [
      { name: 'Cusco City', emoji: '🏔️', accentColor: '#D97706', image: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=600&q=80', tagline: 'Inca Empire capital & colonial city', spots: [{ name: 'Plaza de Armas', tag: 'Landmark' }, { name: 'Sacsayhuamán Inca fortress', tag: 'Must-see' }, { name: 'Coricancha (Temple of the Sun)', tag: 'Inca history' }, { name: 'San Pedro Market', tag: 'Market' }, { name: 'San Blas bohemian quarter', tag: 'Neighbourhood' }] },
      { name: 'Sacred Valley', emoji: '🌄', accentColor: '#16A34A', image: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=600&q=80', tagline: 'Inca terraces & markets', spots: [{ name: 'Pisac Inca ruins & market', tag: 'Must-do' }, { name: 'Ollantaytambo fortress', tag: 'Impressive' }, { name: 'Moray circular terraces', tag: 'Unique' }, { name: 'Maras salt pans', tag: 'Stunning' }, { name: 'Chinchero (Sunday market)', tag: 'Local' }] },
      { name: 'Machu Picchu', emoji: '🗿', accentColor: '#EF4444', image: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=600&q=80', tagline: 'The lost city of the Incas', spots: [{ name: 'Machu Picchu citadel', tag: 'Wonder of the world' }, { name: 'Huayna Picchu peak hike', tag: 'Book 6 months ahead' }, { name: 'Sun Gate (Inti Punku)', tag: 'Sunrise' }, { name: 'Aguas Calientes hot springs', tag: 'Relaxation' }, { name: 'Inca Trail trek (4 days)', tag: 'Epic hike' }] },
    ],
  },
];
