import { readFileSync, writeFileSync } from 'fs';

// FAQs for every post (Bali already done — skipped here)
const FAQ_DATA = {
  'goa-vs-kerala': [
    { question: 'Which is better for a first trip — Goa or Kerala?', answer: 'Goa is easier for first-timers: shorter travel distances, more English spoken, and a well-worn tourist trail. Kerala rewards slightly more planning but delivers richer cultural experiences. If you want beaches + nightlife, choose Goa. If you want backwaters + Ayurveda + nature, choose Kerala.' },
    { question: 'Can I combine Goa and Kerala in one trip?', answer: 'Yes. Goa and Kerala are about 10–12 hours apart by train (Konkan Railway). A popular 2-week itinerary is 4–5 days in Goa then travel south to Kerala for 6–7 days covering Kochi, Alleppey, and Munnar.' },
    { question: 'Which is cheaper — Goa or Kerala?', answer: 'They are broadly similar, but Kerala edges out Goa for budget travel. Kerala guesthouses and local food (sadhya, appam) are cheaper on average. North Goa beach shacks inflate prices significantly; South Goa and Kerala are comparable.' },
    { question: 'What is the best time to visit Goa vs Kerala?', answer: 'Goa is best from November to February — dry, cool, and festive. Kerala is best from September to March. Both states are best avoided during peak monsoon (June–August), though Kerala\'s backwaters are hauntingly beautiful in the rains.' },
  ],
  'bangkok-budget-travel-guide': [
    { question: 'Is Bangkok safe for solo travellers?', answer: 'Yes, Bangkok is very safe for solo travellers including solo women. The main risks are petty theft in crowded areas and tuk-tuk scams near major temples. Use Grab instead of hailing street taxis, and ignore any stranger who tells you a temple is "closed today".' },
    { question: 'How much does a day in Bangkok cost?', answer: 'A budget day in Bangkok costs around ₹2,500–4,000 (USD 30–50): hostel dorm or budget guesthouse, street food meals, BTS/MRT transport, and one or two paid attractions. Mid-range with a private hotel room and restaurant dinners runs ₹6,000–10,000/day.' },
    { question: 'Do Indians need a visa for Thailand?', answer: 'Indian passport holders get a 30-day visa-free entry to Thailand as of 2024. No prior application needed — just arrive with a return ticket and proof of accommodation. You can extend once at an immigration office for another 30 days.' },
    { question: 'What is the best area to stay in Bangkok?', answer: 'Sukhumvit (Asok/Nana area) is best for first-timers — central, well-connected by BTS, and packed with restaurants. Silom/Sathorn suits business travellers. Khao San Road is the backpacker hub. Ari is quieter and more local-feeling.' },
  ],
  'first-time-japan-travel-tips': [
    { question: 'Is Japan expensive for Indian tourists?', answer: 'Japan has become much more affordable due to the weak yen. Budget travellers can manage on ₹5,000–7,000/day (USD 60–85) including a capsule hotel or budget guesthouse, convenience store meals, and rail travel. Mid-range runs ₹10,000–15,000/day.' },
    { question: 'Do Indians need a visa for Japan?', answer: 'Yes, Indian passport holders require a visa for Japan. Apply at the Japanese consulate or embassy in your city. The process typically takes 5–7 working days and requires a confirmed itinerary, bank statements, and hotel bookings. There is no visa on arrival.' },
    { question: 'Is English widely spoken in Japan?', answer: 'In major tourist areas (Tokyo, Kyoto, Osaka), you can get by with English. Station signs, menus at tourist restaurants, and Google Translate (camera mode) make navigation easy. In rural areas, English is rare — download an offline Japanese phrase app before you go.' },
    { question: 'How many days do you need in Japan?', answer: 'Two weeks is the ideal first-time itinerary: 3–4 days Tokyo, 1 day Nikko or Hakone, 2 days Kyoto, 1 day Nara, 2 days Osaka, and a day trip to Hiroshima/Miyajima. Ten days is the comfortable minimum for Tokyo + Kyoto + Osaka.' },
  ],
  'best-beaches-india-2025': [
    { question: 'Which is the most beautiful beach in India?', answer: 'Radhanagar Beach on Havelock Island (Andaman) is consistently rated India\'s best beach — powder-white sand, turquoise water, and virtually no commercial development. On the mainland, Gokarna\'s Om Beach and Varkala in Kerala are top picks.' },
    { question: 'Which Indian beaches are safe for swimming?', answer: 'Calm, safe swimming beaches include Palolem (South Goa), Mararikulam (Kerala), Radhanagar (Andaman), and Tarkarli (Maharashtra). Avoid swimming at beaches with red flags or strong currents like Calangute (North Goa) during monsoon.' },
    { question: 'What is the best time to visit Indian beaches?', answer: 'October to February is the best period for most Indian beaches. The southwest monsoon (June–September) brings heavy rain and rough seas to the west coast. Andaman and east coast beaches (Puri, Mahabalipuram) are best from November to April.' },
    { question: 'Are there any undiscovered or less-crowded beaches in India?', answer: 'Yes — Gokarna (Karnataka), Agonda (South Goa), Mandrem (North Goa), Muzhappilangad drive-in beach (Kerala), and Bangaram Island (Lakshadweep) remain relatively uncrowded. Avoid visiting during peak December–January when even quiet beaches fill up.' },
  ],
  'manali-complete-travel-guide': [
    { question: 'What is the best time to visit Manali?', answer: 'October to February for snow and winter sports (Solang Valley skiing). March to June for trekking, Rohtang Pass access, and pleasant weather. July to September is monsoon — roads can be dangerous. The sweet spot is late September to early November for autumn colours and fewer tourists.' },
    { question: 'How do I get to Manali from Delhi?', answer: 'By bus: HRTC Volvo overnight buses run daily from Delhi\'s ISBT Kashmere Gate (~14–16 hours, ₹800–1,500). By car/cab: ~550 km, 10–12 hours. By air: Fly to Kullu-Manali (Bhuntar) Airport from Delhi (~1 hour), then 50 km drive to Manali. Buses are the most popular option.' },
    { question: 'Is Rohtang Pass always open?', answer: 'Rohtang Pass (3,978m) is open roughly May to October, depending on snowfall. It is closed in winter. A permit is required (available online or at the DC office in Manali) and only 1,200 vehicles are allowed per day. Arrive early to avoid permit delays.' },
    { question: 'What is the altitude of Manali and is altitude sickness a concern?', answer: 'Manali town sits at 2,050m — high enough to feel the difference from Delhi but low enough that serious altitude sickness is rare. Rohtang Pass (3,978m) and Leh (3,500m) are more concerning. Acclimatise for a day in Manali before going higher, stay hydrated, and avoid alcohol the first night.' },
  ],
  'rajasthan-7-day-itinerary': [
    { question: 'What is the best time to visit Rajasthan?', answer: 'October to March is the best time — cool days (15–25°C), clear skies, and all the major festivals (Pushkar Fair in November, Desert Festival in February). April to June is extremely hot (45°C+). Monsoon (July–September) is surprisingly green and less crowded but some forts close.' },
    { question: 'Is 7 days enough for Rajasthan?', answer: 'Seven days covers the Golden Triangle extension (Delhi–Jaipur–Agra) plus Jodhpur and Udaipur comfortably. For a fuller experience including Jaisalmer and Pushkar, plan 10–12 days. Rajasthan rewards slow travel — don\'t try to rush through it.' },
    { question: 'How do I get around Rajasthan?', answer: 'Trains are the best way to travel between major cities (Jaipur–Jodhpur: 6 hrs, Jodhpur–Jaisalmer: 5 hrs). Private car with driver (₹2,500–3,500/day) is popular and convenient for smaller towns. RSRTC buses are cheap but slower. Book trains via IRCTC well in advance.' },
    { question: 'Is Rajasthan safe for solo female travellers?', answer: 'Rajasthan is generally safe for solo women travellers. Tourist areas in Jaipur, Udaipur, and Jodhpur are well-policed and accustomed to international visitors. Dress modestly (cover shoulders and knees at temples), avoid isolated areas after dark, and book accommodation in advance.' },
  ],
  'ladakh-travel-guide': [
    { question: 'How do I get to Ladakh?', answer: 'By air: Leh Kushok Bakula Airport has direct flights from Delhi (1 hr), Mumbai (2.5 hrs), and Srinagar. By road: The Manali–Leh Highway (479 km, ~2 days) is open June–October. The Srinagar–Leh Highway is also seasonal. Most visitors fly in and acclimatise for 2 days before exploring.' },
    { question: 'Is altitude sickness a serious risk in Ladakh?', answer: 'Yes. Leh sits at 3,524m and high passes like Khardung La (5,359m) are significantly higher. Rest completely on your first 2 days in Leh, drink 3–4 litres of water daily, avoid alcohol, and don\'t exert yourself. Diamox (acetazolamide) can help — consult a doctor before travel. If symptoms worsen, descend immediately.' },
    { question: 'What permits are required for Ladakh?', answer: 'Indian nationals do not need a permit for Leh town or main areas. Inner Line Permits (ILP) are required for Pangong Lake, Nubra Valley, Tso Moriri, and Dah-Hanu. ILPs are obtained at the DC Office in Leh (same day, ₹200–400). Foreign nationals need additional permits.' },
    { question: 'What is the best time to visit Ladakh?', answer: 'June to September is peak season — roads are open, weather is pleasant (15–25°C days), and Pangong Lake is accessible. July–August is busiest. May and October are shoulder months with fewer crowds but colder nights. Ladakh in winter (December–February) is remote and extreme but increasingly popular for the Chadar frozen river trek.' },
  ],
  'kerala-honeymoon-guide': [
    { question: 'Is Kerala good for a honeymoon?', answer: 'Kerala is one of India\'s best honeymoon destinations. It offers everything: houseboat stays on the backwaters, private Ayurveda spa resorts in Munnar, quiet beach cottages in Varkala, and luxury tree-house resorts in Wayanad. The food, scenery, and hospitality make it feel genuinely special.' },
    { question: 'What is the best time for a Kerala honeymoon?', answer: 'September to March is ideal. October to February is peak honeymoon season with perfect weather. The monsoon (June–August) is surprisingly romantic for couples who don\'t mind rain — houseboat prices drop 30–40% and the backwaters and tea estates are at their greenest.' },
    { question: 'How many days is ideal for a Kerala honeymoon?', answer: 'Six to eight days works well. A popular itinerary: 1–2 days Kochi, 1 night houseboat in Alleppey, 2 days Munnar, 1–2 days Varkala/Kovalam. Ten days lets you add Thekkady or Wayanad for a wildlife experience.' },
    { question: 'What is the average cost of a Kerala honeymoon package?', answer: 'Budget Kerala honeymoon packages (basic hotels, standard houseboat) start around ₹25,000–35,000 per couple for 5 nights. Mid-range with boutique resorts runs ₹50,000–80,000. Luxury packages with premium houseboats and spa resorts cost ₹1,00,000–2,00,000+ for 7 nights.' },
  ],
  'bangkok-travel-guide-tips': [
    { question: 'How many days do you need in Bangkok?', answer: 'Three to four days is enough to cover the highlights: Grand Palace, Wat Pho, Chatuchak Weekend Market, the riverside, and a night out in one of the rooftop bars. Five to seven days lets you do day trips to Ayutthaya or Kanchanaburi and explore neighbourhoods like Ari or Thonglor.' },
    { question: 'What is the best way to get around Bangkok?', answer: 'The BTS Skytrain and MRT Metro cover most tourist areas and are cheap, fast, and air-conditioned (₹30–80/trip). Grab (ride-hailing app) is essential for areas not covered by rail. Tuk-tuks are for short trips only — always agree on a price before boarding. The Chao Phraya Express Boat is scenic and useful for the riverside temples.' },
    { question: 'What should I not miss eating in Bangkok?', answer: 'Pad Thai from a street cart near Wat Arun, mango sticky rice (April–June when mangoes are in season), boat noodles at Victory Monument, khao man gai (poached chicken rice) at any shophouse, and tom yum goong. The street food around Yaowarat (Chinatown) on Saturday evenings is unmissable.' },
    { question: 'What is the dress code at Bangkok temples?', answer: 'Both men and women must cover shoulders and knees at all Bangkok temples. Sarongs are often available to borrow or rent at the entrance of major temples like the Grand Palace. Wear light cotton layers — it is hot, and you\'ll be doing a lot of walking on marble in the sun.' },
  ],
  'dubai-travel-guide-2025': [
    { question: 'Is Dubai worth visiting in 2025?', answer: 'Dubai is worth it for first-timers who want a mix of spectacular architecture, world-class food, and desert experiences. It\'s expensive but surprisingly accessible. The Burj Khalifa, Dubai Frame, desert safari, and the old Al Fahidi quarter offer genuinely memorable experiences. It works best as a 4–5 day trip, not a 2-week stay.' },
    { question: 'What is the best time to visit Dubai?', answer: 'November to March is perfect — temperatures are 20–28°C and outdoor activities are pleasant. April and October are shoulder months (warm but manageable). May to September is brutal — 40–50°C heat makes being outside uncomfortable, though everything is heavily air-conditioned and prices drop 40–50%.' },
    { question: 'Do Indians need a visa for Dubai?', answer: 'Indian passport holders receive a 30-day visa on arrival in Dubai (UAE) as of April 2024, provided they hold a valid US, UK, EU, or Australian visa. Those without these visas must apply for a UAE tourist visa in advance through a UAE airline or travel agent (around AED 250–350 / ₹5,500–7,700).' },
    { question: 'Is Dubai safe for tourists?', answer: 'Dubai is one of the safest cities in the world for tourists. Crime rates are extremely low. The main things to be aware of: dress modestly in public spaces (not on beaches), do not drink in public (only in licensed venues), and be respectful during Ramadan. LGBTQ+ travellers should be discreet as same-sex relationships are illegal.' },
  ],
  'japan-first-time-travel-tips-2025': [
    { question: 'Is Japan safe for first-time travellers?', answer: 'Japan is one of the safest countries in the world. Violent crime is extremely rare, lost wallets are often returned intact, and train stations have assistance desks with English-speaking staff. The biggest risks are minor: getting lost on the subway, or accidentally violating an onsen etiquette rule.' },
    { question: 'Do I need a Japan Rail Pass?', answer: 'A JR Pass is worth it if you\'re visiting multiple cities. For a Tokyo–Kyoto–Osaka trip (2 weeks), a 14-day JR Pass (around ₹55,000) saves money over buying individual shinkansen tickets. For a Tokyo-only trip, skip the JR Pass and use IC cards (Suica/Pasmo) instead.' },
    { question: 'What is the tipping culture in Japan?', answer: 'Do not tip in Japan. Tipping is considered rude — it implies the server is not paid fairly or that you are treating them as inferior. Service is uniformly excellent and included in the price. Simply say "gochisousama deshita" (thank you for the meal) when leaving a restaurant.' },
    { question: 'What is the best way to get a SIM card in Japan?', answer: 'Buy a prepaid data SIM at Narita or Haneda airport arrivals (IIJmio, IHY Mobile, or Docomo Tourist SIM). A 15-day unlimited data SIM costs around ¥3,000–5,000 (₹1,500–2,500). Alternatively, rent a pocket WiFi router at the airport. Most convenience stores also sell SIM cards.' },
  ],
  'maldives-budget-travel-guide': [
    { question: 'Can you visit the Maldives on a budget?', answer: 'Yes. Staying on local inhabited islands (Maafushi, Thulusdhoo, Fulidhoo) instead of private resort islands cuts costs dramatically. Budget guesthouses cost $30–60/night vs $500+/night at resorts. You still get white-sand beaches and snorkelling — just not the overwater bungalow experience.' },
    { question: 'Do Indians need a visa for Maldives?', answer: 'No visa is required for Indian passport holders. Indians get a free 30-day visa on arrival at Malé\'s Velana International Airport. You need a return ticket, hotel booking confirmation, and sufficient funds.' },
    { question: 'What is the best time to visit Maldives?', answer: 'November to April is the dry season — sunny days, calm seas, and excellent visibility for snorkelling and diving. May to October is the wet season with rougher seas, but prices drop 30–50% and it is still beautiful on many atolls. December and January see peak prices.' },
    { question: 'How do you get from Malé to guesthouses on local islands?', answer: 'Public ferries are the cheapest option ($1–4 per trip) but run only once or twice a day. Speedboat transfers ($20–50 one-way) are faster and more frequent. Seaplane transfers are only used for the remote luxury resorts. Book ferry schedules in advance as they change seasonally.' },
  ],
  'singapore-3-day-itinerary': [
    { question: 'Is 3 days enough for Singapore?', answer: 'Three days covers the essential Singapore — Gardens by the Bay, Marina Bay Sands skyline, Sentosa Island, Chinatown, Little India, and the Botanic Gardens. Four to five days lets you add day trips to Pulau Ubin, Johor Bahru, or explore the hawker centres more thoroughly.' },
    { question: 'Do Indians need a visa for Singapore?', answer: 'Indian passport holders require a visa for Singapore. Apply online via the Singapore Tourism Board\'s e-Visa system. The fee is SGD 30 (~₹1,900) and takes 3–5 working days. Indians with valid US, Australian, UK, EU visas, or Singapore PR-holders can enter visa-free under certain conditions — check the ICA website.' },
    { question: 'What is Singapore famous for food-wise?', answer: 'Singapore is a food paradise. Must-tries: Hainanese chicken rice at Tian Tian (Maxwell Food Centre), chilli crab at Long Beach Seafood, laksa at 328 Katong, char kway teow (fried flat noodles), and kaya toast with soft-boiled eggs at Ya Kun. Hawker centres like Lau Pa Sat and Old Airport Road offer incredible variety at low prices.' },
    { question: 'Is Singapore expensive for Indian tourists?', answer: 'Singapore is one of Asia\'s most expensive cities. Budget travel (hostels, hawker food, public transport) runs SGD 80–120/day (~₹5,000–7,500). Mid-range with a 3-star hotel and restaurant meals costs SGD 200–300/day. The good news: food at hawker centres is genuinely cheap (SGD 4–8 per meal) and public transport is excellent and affordable.' },
  ],
  'varanasi-travel-guide': [
    { question: 'What is the best time to visit Varanasi?', answer: 'October to March is ideal — the Ganga Aarti is at its most atmospheric, the ghats are busy with pilgrims and the weather is pleasant. Dev Deepawali (November) is spectacular when thousands of lamps are floated on the Ganges. Avoid May–June (extreme heat, 45°C+) and July–August (heavy monsoon floods the lower ghats).' },
    { question: 'How many days do you need in Varanasi?', answer: 'Two to three days is enough to experience the essentials: sunrise boat ride on the Ganges, the ghats, the narrow lanes of the old city, Sarnath (20 km away), and the evening Ganga Aarti at Dashashwamedh Ghat. Allow an extra day if you want to visit Ramnagar Fort or attend a classical music recital.' },
    { question: 'Is Varanasi safe for tourists?', answer: 'Varanasi is safe but requires alertness. The main risks are aggressive touts near the ghats, overpriced boat rides, and pickpockets in crowded lanes. Politely but firmly decline unsolicited guides. Pre-book your boat ride through your hotel. The old city lanes (Vishwanath Gali) are safe to walk but easy to get lost in — embrace it.' },
    { question: 'Can non-Hindus visit the temples in Varanasi?', answer: 'Some temples, including the Kashi Vishwanath Temple, are restricted to Hindus only (including Indian Hindus — foreigners of Hindu faith may enter with ID). Many other temples and all the ghats are open to everyone. Photography is prohibited inside most temples. The Durga Temple and Tulsi Manas Temple are more accessible to all visitors.' },
  ],
  'goa-travel-guide-complete': [
    { question: 'When is the best time to visit Goa?', answer: 'November to February is peak season — the weather is perfect (25–32°C), all beach shacks are open, and the Christmas–New Year period is especially lively. October and March are shoulder months with good weather and fewer crowds. Avoid April–May (brutal heat) and June–September (heavy monsoon, most beach shacks close).' },
    { question: 'What is the difference between North and South Goa?', answer: 'North Goa (Baga, Calangute, Anjuna, Vagator) is louder, more commercialised, and known for nightlife and parties. South Goa (Palolem, Agonda, Colva, Benaulim) is quieter, cleaner, and better for those who want peaceful beaches. Most budget travellers start in North Goa; those seeking relaxation prefer South Goa.' },
    { question: 'How much does a Goa trip cost per day?', answer: 'Budget: ₹1,500–2,500/day (beach shack bed, local cafes, scooter rental). Mid-range: ₹3,500–6,000/day (private room in a guesthouse/Airbnb, restaurant meals). Luxury: ₹10,000–25,000+/day (5-star resort, private pool villa). Peak December–January prices are 50–100% higher than the rest of the year.' },
    { question: 'Do I need to rent a scooter in Goa?', answer: 'Renting a scooter (₹300–400/day) is by far the best way to get around Goa and is the local default. It lets you reach beaches and restaurants not served by autos. Ola/Uber and local taxis exist but are expensive for multiple trips. If you\'re uncomfortable on a scooter, rent a car with driver for ₹1,500–2,000/day.' },
  ],
  'shimla-trip-guide': [
    { question: 'When is the best time to visit Shimla?', answer: 'December to February for snow — Shimla\'s famous snowfall turns the town magical. March to June for pleasant weather (15–25°C) and cherry blossoms. September and October for clear post-monsoon skies and fewer crowds. Avoid July–August (heavy rain, landslides on road) unless you\'re specifically seeking the green misty hills.' },
    { question: 'How do I get to Shimla from Delhi?', answer: 'By train: The Kalka–Shimla Toy Train (UNESCO Heritage) is a beautiful 5-hour journey from Kalka — book well in advance. Reach Kalka from Delhi on the Shatabdi Express (4 hrs). By road: Delhi to Shimla is ~370 km (7–8 hrs) by bus or cab. Himachal Tourism buses from Delhi\'s ISBT are comfortable and frequent.' },
    { question: 'What are the top things to do in Shimla?', answer: 'Walk the Mall Road and Lakkar Bazaar, visit the neo-Gothic Christ Church, take the Jakhu Hill ropeway (or trek) to the Hanuman Temple, day trip to Kufri for snow activities, explore Narkanda for apple orchards and skiing, and ride the toy train at least one way between Kalka and Shimla.' },
    { question: 'Does it snow in Shimla? When?', answer: 'Shimla typically receives snowfall from late December through February. Heavy snowfall usually happens in January, often closing the NH5 highway for a day or two. The town is beautiful but can get bitterly cold (−5°C at night). Pack thermals, a heavy jacket, and waterproof boots if visiting in winter.' },
  ],
  'europe-backpacking-guide-india': [
    { question: 'Which Schengen visa should Indians apply for when backpacking Europe?', answer: 'Apply for the visa of your first entry country in the Schengen zone. If your itinerary visits multiple countries but you spend the most time in one, apply to that country\'s consulate. France, Germany, and Spain consulates tend to have faster processing times for Indians. Apply at least 6–8 weeks in advance.' },
    { question: 'How much money do Indians need for a Europe backpacking trip?', answer: 'Budget ₹4,000–6,000/day for Eastern Europe (Prague, Budapest, Krakow) and ₹7,000–10,000/day for Western Europe (Paris, Amsterdam, Barcelona). A 3-week Europe trip from India typically costs ₹1,50,000–2,50,000 total including flights, accommodation, food, transport, and entry fees.' },
    { question: 'What is the cheapest time to fly from India to Europe?', answer: 'March–April and October–November are the cheapest periods for India–Europe flights. Book 3–4 months ahead for the best fares. Emirates, Qatar Airways, and Turkish Airlines often have the most competitive prices from Indian cities. Budget airlines like Wizz Air and Ryanair are useful for travel within Europe.' },
    { question: 'Is a Eurail Pass worth it for Indian backpackers?', answer: 'For a whirlwind 3–4 country 2-week trip, a Eurail pass can save money. But for slower travel through 2 countries, point-to-point tickets booked in advance (via Trainline or Omio) are often cheaper. FlixBus is an excellent budget alternative for many Europe routes at 10–30% of train prices.' },
  ],
  'rishikesh-travel-guide': [
    { question: 'What is Rishikesh known for?', answer: 'Rishikesh is India\'s yoga capital and the "Adventure Sports Capital of India." It\'s famous for yoga ashrams and meditation retreats, white-water rafting on the Ganges, bungee jumping (the highest in India at 83m), the Beatles Ashram, Lakshman Jhula suspension bridge, and the evening Ganga Aarti at Parmarth Niketan.' },
    { question: 'What is the best time to visit Rishikesh?', answer: 'February to May and September to November are ideal. The weather is pleasant, the Ganges is calm enough for rafting, and the ashrams are busy with courses. The International Yoga Festival happens in March. June–August monsoon brings heavy rain and strong river currents that make water sports dangerous.' },
    { question: 'Is Rishikesh suitable for non-spiritual travellers?', answer: 'Absolutely. While Rishikesh has a strong spiritual identity, it also offers some of India\'s best adventure activities: river rafting, cliff jumping, kayaking, trekking to Chandrashila and Kedarkantha, and camping on the Ganges banks. The café culture in the Laxman Jhula area is vibrant and very traveller-friendly.' },
    { question: 'Is Rishikesh vegetarian-only?', answer: 'Yes — Rishikesh and Haridwar are both vegetarian cities. Meat, alcohol, and eggs are officially banned within the municipal limits (though some cafes near the tourist zones bend the rules for eggs). The vegetarian food is excellent — local thalis, fresh juices, and international cafes serving falafel, pancakes, and pasta are everywhere.' },
  ],
  'udaipur-travel-guide': [
    { question: 'What is Udaipur famous for?', answer: 'Udaipur is called the "City of Lakes" and is known for the Lake Pichola, City Palace, and the floating Lake Palace hotel (now a Taj property). It\'s one of Rajasthan\'s most romantic cities — whitewashed buildings reflected in lakes, rooftop restaurants overlooking the water, and a far more relaxed pace than Jaipur.' },
    { question: 'How many days do you need in Udaipur?', answer: 'Two to three days is ideal: City Palace, a boat ride on Lake Pichola to Jag Mandir, Saheliyon ki Bari, the old city markets, Bagore ki Haveli for the evening folk dance show, and a sunset rooftop dinner. A third day allows a day trip to Kumbhalgarh Fort or Ranakpur temples.' },
    { question: 'What is the best time to visit Udaipur?', answer: 'October to March is perfect — mild temperatures (15–28°C), full lakes after the monsoon, and the peak festival season. The Shilpgram festival in December is particularly vibrant. April–June is hot (35–42°C) but manageable. Udaipur\'s lakes look most beautiful from August–October after the monsoon fills them.' },
    { question: 'Is Udaipur expensive compared to other Rajasthan cities?', answer: 'Udaipur is the most expensive city in Rajasthan for accommodation, largely because of its romantic reputation and rooftop restaurant scene. However, budget guesthouses near Lal Ghat still offer rooms from ₹700–1,200/night with lake views. Mid-range hotels with lake-facing rooms run ₹3,000–6,000/night.' },
  ],
  'thailand-travel-guide-2025': [
    { question: 'Do Indians need a visa for Thailand in 2025?', answer: 'No. As of 2024, Indian passport holders receive a 30-day visa-free entry to Thailand. No application is needed — just arrive with a return ticket and proof of accommodation. The policy was made permanent in 2024 after successful trials in 2023.' },
    { question: 'What is the best time to visit Thailand?', answer: 'November to April is the dry season and ideal for most of Thailand. December to February is peak season with perfect weather. May to October is monsoon — the Gulf of Thailand (Koh Samui side) and Andaman (Phuket/Krabi side) have different monsoon timings, so one coast is usually sunny while the other is wet.' },
    { question: 'Is Thailand safe for Indian solo travellers?', answer: 'Thailand is very safe for Indian solo travellers, including women. The main risks are scams (gem scams, tuk-tuk detours to jewellery shops), drink spiking at nightlife venues, and road accidents from renting scooters. Use Grab instead of tuk-tuks for price certainty, and drink only in reputable venues.' },
    { question: 'How much does a Thailand trip cost from India?', answer: 'Return flights from major Indian cities to Bangkok cost ₹15,000–30,000. Daily travel budget: ₹2,500–4,000 for budget travel (hostels, street food, local transport), ₹6,000–10,000 for mid-range. A 10-day Thailand trip from India typically costs ₹60,000–1,00,000 total including flights.' },
  ],
  'paris-travel-guide-2025': [
    { question: 'How many days do you need in Paris?', answer: 'Four to five days covers the highlights comfortably: Eiffel Tower, Louvre, Musée d\'Orsay, Notre-Dame, Montmartre, Versailles day trip, and evening Seine cruise. Three days is the absolute minimum if you\'re focused. First-timers often underestimate how long museum visits take — pre-book timed entry for the Louvre.' },
    { question: 'Is Paris expensive?', answer: 'Paris is expensive but manageable with planning. Budget: €80–120/day (hostel, boulangerie meals, metro). Mid-range: €200–300/day (2-star hotel, brasserie lunches, one nice dinner). Many top attractions are free or reduced on the first Sunday of the month, including the Louvre and Musée d\'Orsay.' },
    { question: 'Is Paris safe for Indian tourists?', answer: 'Paris is generally safe but requires standard urban vigilance. Pickpocketing is common around the Eiffel Tower, Sacré-Cœur, and on the RER B airport train. Keep bags zipped, be wary of "petition" scammers, and use the metro safely by standing away from the doors at night. Tourist areas are well-patrolled.' },
    { question: 'Do Indians need a Schengen visa for Paris?', answer: 'Yes. Indian passport holders need a Schengen visa to visit France. Apply at VFS Global France visa application centre. Requirements include a confirmed itinerary, hotel bookings, travel insurance (minimum €30,000 coverage), bank statements, and employment/student proof. Apply 4–6 weeks before travel.' },
  ],
  'italy-travel-guide-2025': [
    { question: 'How many days do you need in Italy?', answer: 'Ten to fourteen days covers a classic Italy trip: 3 days Rome, 1 day Pompeii, 2 days Florence + Tuscany day trip, 1–2 days Cinque Terre, 2 days Venice, and travel days. For Rome only: 3 days minimum. For Rome + Florence + Venice: 8–10 days.' },
    { question: 'Is Italy safe for Indian tourists?', answer: 'Italy is very safe for tourists. The main concerns are pickpocketing in tourist-heavy areas (Colosseum, Vatican, Florence train station) and scams like people placing items in your hands and demanding payment. Stay vigilant in crowded areas, use a money belt, and ignore unsolicited "gifts".' },
    { question: 'What is the best time to visit Italy?', answer: 'April to June and September to October are ideal — pleasant weather (18–25°C), manageable crowds, and good prices. July and August are peak summer: brutally hot in Rome and Florence (35°C+), extremely crowded, and expensive. Venice in winter (November–February) is beautiful, uncrowded, and cheap.' },
    { question: 'Do you need to book Italian museums in advance?', answer: 'Yes, always pre-book the Colosseum, Vatican Museums, Sistine Chapel, Uffizi Gallery, and the Last Supper in Milan. Walk-up queues can be 2–3 hours. Book via official websites 2–4 weeks ahead in peak season. Most venues have a small booking fee (€2–5) that is well worth it.' },
  ],
  'vietnam-travel-guide-2025': [
    { question: 'Do Indians need a visa for Vietnam?', answer: 'Indian passport holders need a visa for Vietnam. The easiest option is the e-Visa (apply online at evisa.xuatnhapcanh.gov.vn) — it costs USD 25, takes 3 working days, and grants 90-day single or multiple entry. Alternatively, apply for a Visa on Arrival via a letter of approval, but the e-Visa is simpler.' },
    { question: 'What is the best time to visit Vietnam?', answer: 'Vietnam is long and thin, so weather varies by region. North (Hanoi, Ha Long Bay): best October–April. Central (Hoi An, Da Nang): best February–August. South (Ho Chi Minh City, Mekong): best November–April. December to April is a good compromise for a north-to-south trip.' },
    { question: 'How do I travel between cities in Vietnam?', answer: 'The Reunification Express train runs the full length of the country (Hanoi to Ho Chi Minh City, 33 hrs). Domestic flights on Vietnam Airlines, Bamboo Airways, or VietJet are cheap (often USD 20–50) and save huge amounts of time. Open Bus tickets (hop-on/hop-off) are popular for backpackers and very cheap.' },
    { question: 'Is Vietnamese food spicy for Indian palates?', answer: 'Vietnamese food is generally milder than Indian food — it uses fresh herbs, lemongrass, and lime rather than heavy spices. Pho, banh mi, bun cha, and fresh spring rolls (goi cuon) are all gentle on the palate. Northern Vietnamese food is subtler; Southern food is slightly sweeter. Very little will feel "spicy" to someone used to Indian food.' },
  ],
  'santorini-travel-guide': [
    { question: 'Is Santorini worth the money?', answer: 'Santorini is expensive and crowded in peak season but genuinely delivers on the iconic views — the caldera, white-blue churches, and sunset from Oia are as spectacular in person as in photos. Worth it for a 3–4 day romantic or honeymoon trip. Less worth it as a budget destination or for travellers who prefer activity-based travel over scenery.' },
    { question: 'When is the best time to visit Santorini?', answer: 'April–May and September–October are the sweet spots: warm enough for swimming, far fewer crowds than July–August, and prices 30–40% lower. July and August are peak — Oia\'s sunset viewpoint gets dangerously crowded. November to March the island quiets almost completely, many hotels close, but it\'s peaceful and very cheap.' },
    { question: 'How do I get to Santorini from Athens?', answer: 'By ferry from Piraeus Port, Athens: 5–9 hours depending on the boat (high-speed: 5 hrs, conventional: 9 hrs). Tickets cost €35–80 one way. By plane: Athens–Santorini is 45 minutes on Sky Express or Olympic Air (€60–120). Ferries are scenic and budget-friendly; flights save significant time.' },
    { question: 'Which village is best to stay in Santorini?', answer: 'Oia is the most famous (best sunset, most photogenic, most expensive). Fira (the capital) is livelier with more restaurants and nightlife. Imerovigli is quieter with stunning caldera views. Perissa and Perivolos on the black-sand beach side are best for beach access and budget accommodation.' },
  ],
  'london-travel-guide-2025': [
    { question: 'Is London expensive for Indian tourists?', answer: 'London is one of the most expensive cities to visit. Budget travel (hostels, supermarket food, walking and Tube) runs £80–120/day (~₹8,500–13,000). Mid-range with a budget hotel and restaurant meals runs £200–300/day. The good news: many top attractions are free — British Museum, National Gallery, Tate Modern, Hyde Park.' },
    { question: 'Do Indians need a UK visa?', answer: 'Yes. Indian passport holders need a UK Standard Visitor Visa to visit London. Apply via the UK Visas & Immigration website (UKVI) at least 3 months in advance. The fee is £115 (~₹12,500). You\'ll need bank statements, employment proof, hotel bookings, and a detailed itinerary. UK visa rejection rates for Indians have historically been higher than Schengen — be thorough.' },
    { question: 'What is the best time to visit London?', answer: 'June to August is summer — longest days, outdoor events, Wimbledon, and the warmest weather (though "warm" means 20–25°C at best). March to May is spring: beautiful parks and fewer crowds. September to November is pleasant and less crowded. December is festive with Christmas markets. The "bad" weather reputation is somewhat exaggerated — it rains year-round but rarely heavily.' },
    { question: 'What can you do for free in London?', answer: 'London has some of the world\'s best free attractions: British Museum, National History Museum, Science Museum, Victoria & Albert Museum, National Gallery, Tate Modern, Tate Britain, National Portrait Gallery, and all the Royal Parks. Changing of the Guard at Buckingham Palace and watching boats on the Thames are also free.' },
  ],
  'turkey-istanbul-travel-guide': [
    { question: 'Do Indians need a visa for Turkey?', answer: 'Yes. Indian passport holders need an e-Visa for Turkey, applied online at evisa.gov.tr. The fee is USD 50, it takes 24 hours to process, and grants 30-day single or 90-day multiple entry (multiple entry costs more). Apply at least 3 days before travel. Do not use third-party websites — only the official government portal.' },
    { question: 'What is the best time to visit Istanbul?', answer: 'April–May and September–October are ideal — mild temperatures (18–25°C), fewer tourists than summer, and comfortable sightseeing. June–August is hot (30–35°C), crowded, and expensive. December to February is cold (5–10°C) but the city is atmospheric and prices are low. Ramadan is a fascinating time to visit for the night bazaars.' },
    { question: 'Is Istanbul safe for tourists?', answer: 'Istanbul is generally safe for tourists. The historic Sultanahmet area, Beyoglu, and Bosphorus neighbourhoods are well-patrolled. Common issues are taxi overcharging (always use the meter or apps like BiTaksi) and carpet shop soft-pressure tactics. Avoid the few areas near the Syrian border, far from tourist Istanbul.' },
    { question: 'How many days do you need in Istanbul?', answer: 'Three to four days covers the essentials: Hagia Sophia, Blue Mosque, Topkapi Palace, Grand Bazaar, Spice Bazaar, a Bosphorus cruise, and the Beyoglu neighbourhood. Five to six days lets you visit Dolmabahçe Palace, the Asian side (Kadikoy), and Princes\' Islands.' },
  ],
  'sri-lanka-travel-guide-2025': [
    { question: 'Do Indians need a visa for Sri Lanka?', answer: 'As of 2024, Indian nationals receive free Electronic Travel Authorization (ETA) for Sri Lanka — apply online at eta.gov.lk before departure. It\'s free for Indians and grants 30 days, extendable to 6 months. Processing takes 24–48 hours.' },
    { question: 'What is the best time to visit Sri Lanka?', answer: 'Sri Lanka has two monsoon seasons affecting different coasts. West coast (Colombo, Galle, Ella): best December–March. East coast (Trincomalee, Arugam Bay): best May–September. For a complete island circuit, visit between December and March when the west and cultural triangle are at their best.' },
    { question: 'How do I get around Sri Lanka?', answer: 'Trains are scenic and cheap — the Colombo–Ella hill country route is one of the world\'s most beautiful train journeys (₹120–300 one-way). Tuk-tuks are everywhere for short hops. For flexibility, rent a scooter or hire a car with driver (₹4,000–6,000/day). Buses are the cheapest option for long distances.' },
    { question: 'Is Sri Lanka expensive for Indian tourists?', answer: 'Sri Lanka is very affordable for Indian tourists. Budget travel costs ₹1,500–3,000/day (guesthouse, local rice and curry meals, buses). Mid-range with a boutique hotel and restaurant meals runs ₹4,000–7,000/day. The Sri Lankan rupee gives Indian rupees strong purchasing power.' },
  ],
  'nepal-travel-guide-2025': [
    { question: 'Do Indians need a visa for Nepal?', answer: 'No. Indian passport holders do not need a visa for Nepal and can stay indefinitely. Entry is free. You don\'t even need a passport — a valid Indian voter ID, Aadhaar, or government-issued photo ID is sufficient for Indians entering Nepal.' },
    { question: 'What is the best time to visit Nepal?', answer: 'October–November is the best time for trekking — clear post-monsoon skies, excellent mountain views, and mild temperatures. March–May (spring) is the second-best window and the best time for Everest Base Camp due to climbing season. December–February is cold but clear at altitude. Monsoon (June–September) floods trails and clouds views.' },
    { question: 'How much does the Everest Base Camp trek cost?', answer: 'The EBC trek costs approximately ₹40,000–80,000 for a guided, teahouse-based 14-day trek from Lukla — including flights from Kathmandu to Lukla (~₹12,000 each way), permits, guide, and accommodation. Solo budgeted trekkers can do it for less, but guides and porters are strongly recommended.' },
    { question: 'Is Nepal safe for tourists?', answer: 'Nepal is very safe for tourists, including solo travellers. The main risks are altitude sickness on high treks, rare road accidents on mountain highways, and petty theft in Thamel (Kathmandu\'s tourist hub). Trek only with registered guides, respect altitude acclimatisation schedules, and register with TIMS before trekking.' },
  ],
  'morocco-marrakech-travel-guide': [
    { question: 'Is Morocco safe for Indian tourists?', answer: 'Morocco is generally safe for tourists. Marrakech\'s medina can feel overwhelming with aggressive shopkeepers and unofficial "guides" who attach themselves to tourists uninvited. Be firm but polite, ignore commission-based guides near Jemaa el-Fna, and navigate the souks confidently. Solo women should dress modestly outside tourist areas.' },
    { question: 'Do Indians need a visa for Morocco?', answer: 'Yes. Indian passport holders require a visa for Morocco. Apply at the Moroccan embassy or through a travel agent. The process requires a bank statement, return ticket, hotel bookings, employment proof, and takes about 2 weeks. There is no visa on arrival for Indians.' },
    { question: 'What is the best time to visit Morocco?', answer: 'March–May and September–November are ideal — pleasant temperatures (20–28°C), clear skies, and manageable crowds. June–August is very hot in Marrakech (40°C+) but cooler in the Atlas Mountains. December–February is cool and beautiful with potential snow on mountain passes and great prices.' },
    { question: 'How do you avoid getting ripped off in Marrakech?', answer: 'Always establish prices before any transaction — taxis, horse-drawn carriages, and market stalls all operate on negotiation. For taxis, insist on the meter or agree on a fare first. In the souks, initial asking prices are 3–5x the expected final price; start at 30% of the asking price. Phrase "la, shukran" (no, thank you) politely but firmly ends most approaches.' },
  ],
  'prague-travel-guide-2025': [
    { question: 'Is Prague cheap for Indian tourists?', answer: 'Prague is one of Europe\'s most affordable capitals. Budget travel costs €40–60/day (~₹3,500–5,500): hostel dorm, local pub meals, and trams. Mid-range with a private hotel runs €100–150/day. A good Czech meal with beer in a local restaurant costs €10–15. Avoid tourist-trap restaurants on Old Town Square.' },
    { question: 'Do I need a Schengen visa for Prague?', answer: 'Yes. The Czech Republic is in the Schengen zone, so Indian passport holders need a Schengen visa. Apply at the Czech or German/French consulate (whichever is most accessible). Requirements are the same as any Schengen visa: bank statements, itinerary, travel insurance, hotel bookings.' },
    { question: 'What is Prague famous for?', answer: 'Prague is famous for its perfectly preserved medieval Old Town and astronomical clock (Orloj), the Gothic spires of St. Vitus Cathedral, Charles Bridge lined with Baroque statues, Kafka\'s birthplace, traditional Czech beer (the best pilsner in the world), svíčková (beef sirloin in cream sauce), and trdelník pastry.' },
    { question: 'Is Prague worth visiting in winter?', answer: 'Absolutely. Prague\'s Christmas market on Old Town Square (late November to January) is one of Europe\'s most atmospheric. The city is magical under snow, crowds are 50% lower than summer, and prices for hotels drop significantly. Pack a heavy coat — temperatures regularly drop to −5 to −10°C in January.' },
  ],
  'amsterdam-travel-guide-2025': [
    { question: 'Do Indians need a visa for Amsterdam?', answer: 'Yes. Amsterdam is in the Netherlands, part of the Schengen zone. Indian passport holders need a Schengen visa — apply at the Netherlands consulate or VFS Global. Requirements are standard: bank statements (€50–100/day), travel insurance, itinerary, and hotel bookings. Apply 6–8 weeks before travel.' },
    { question: 'What is the best time to visit Amsterdam?', answer: 'April–May is ideal — the Keukenhof tulip fields are at peak bloom (one of the world\'s great natural spectacles), the weather is pleasant (15–20°C), and the city is beautiful. June–August is warm and lively but very crowded. September–October is good for fewer crowds and autumn canal reflections. Winter is grey but atmospheric and very cheap.' },
    { question: 'Is Amsterdam safe for tourists?', answer: 'Amsterdam is safe but requires vigilance on certain fronts: bicycle lanes are genuinely dangerous (cyclists have right of way, always look before stepping off a pavement), pickpocketing is common in the red-light district and around Central Station, and tourist-targeted scams are frequent. The rest of the city is extremely pleasant and low-crime.' },
    { question: 'What is there to do in Amsterdam beyond the obvious?', answer: 'Beyond the Anne Frank House and Van Gogh Museum: explore the Jordaan neighbourhood\'s independent boutiques and brown cafes, visit the FOAM Photography Museum, cycle to Zaanse Schans for windmills, take a cooking class in a houseboat kitchen, or rent a kayak and paddle the canals yourself.' },
  ],
  'seoul-korea-travel-guide': [
    { question: 'Do Indians need a visa for South Korea?', answer: 'Yes. Indian passport holders require a visa for South Korea. Apply online via the Korean e-Visa system (evisa.mofa.go.kr) or at the Korean embassy. The process takes 3–5 working days. You need bank statements, accommodation bookings, and a return ticket. Holders of valid US, UK, or Schengen visas may be eligible for visa-free entry — check current rules.' },
    { question: 'What is Seoul famous for?', answer: 'Seoul is famous for K-pop and Korean drama culture (SM Town, HYBE), street food (tteokbokki, Korean fried chicken, mandu), BBQ restaurants, the Gyeongbokgung Palace, shopping in Myeongdong and Dongdaemun, the Bukchon Hanok Village (traditional houses), and the DMZ (North Korean border) tours.' },
    { question: 'Is Korea vegetarian-friendly for Indian tourists?', answer: 'Korea is challenging for strict vegetarians. Most Korean dishes contain meat or seafood, including many soups and sauces. Veganism/vegetarianism is growing in Seoul with dedicated restaurants in Hongdae and Insadong. Buddhist temple food (traditional Korean vegetarian cuisine) is excellent and available at temple-stay programmes.' },
    { question: 'What is the best time to visit Seoul?', answer: 'Spring (March–May) for cherry blossoms along the Han River and Yeouido Park — some of Asia\'s best. Autumn (September–November) for vivid foliage in Bukhansan National Park. Summer (June–August) is hot, humid, and rainy. Winter (December–February) is very cold (−10°C) but Seoul looks beautiful in snow, and the ski resorts at Pyeongchang are a short bus ride away.' },
  ],
  'new-york-travel-guide': [
    { question: 'How much does a New York City trip cost?', answer: 'NYC is expensive. Budget travel (hostel dorm, street food, walking + subway) runs $100–150/day. Mid-range with a budget hotel, restaurant lunches, and one or two paid attractions runs $250–350/day. Many top attractions are free or pay-what-you-wish: Metropolitan Museum of Art, Central Park, Staten Island Ferry (views of Statue of Liberty), Brooklyn Bridge walk.' },
    { question: 'Which neighbourhood should I stay in New York?', answer: 'Midtown Manhattan is most central for sightseeing (Times Square, Central Park, Empire State Building) but expensive and noisy. Lower East Side and Williamsburg (Brooklyn) offer better value with a younger, more local vibe. For first-timers who want to walk to most sights, Midtown or the Upper West Side are most convenient.' },
    { question: 'Do Indians need a US visa to visit New York?', answer: 'Yes. Indian passport holders need a US B1/B2 Tourist Visa. Apply at the US Consulate or Embassy in India — the process includes an online DS-160 form, fee payment (~$185), and an in-person interview. Processing times vary but can take weeks to months. Apply 3–6 months ahead. The US visa is one of the harder ones for Indians to obtain.' },
    { question: 'What is the best time to visit New York City?', answer: 'April–June (spring) and September–November (fall) are ideal — mild weather and the city at its most beautiful. July–August is hot and humid (30–35°C) but great for outdoor events and rooftop bars. December is magical for Christmas decorations, the Rockefeller tree, and ice skating, though cold. January–February is cheapest and snowiest.' },
  ],
  'lisbon-travel-guide-2025': [
    { question: 'Is Lisbon cheap compared to other European capitals?', answer: 'Lisbon is one of Western Europe\'s most affordable capitals, though prices have risen significantly since 2019. Budget travel (hostel, pastelaria breakfast, petiscos lunch) runs €50–80/day. Mid-range with a private hotel and restaurant meals runs €120–180/day. A pastel de nata costs €1–1.50 — practically a free snack by European standards.' },
    { question: 'Do Indians need a Schengen visa for Lisbon?', answer: 'Yes. Portugal is in the Schengen zone. Indian passport holders need a Schengen visa — apply at the Portuguese consulate or VFS Global. Processing takes 10–15 working days. Standard requirements: insurance, bank statements, hotel bookings, return flights, and employment/student proof.' },
    { question: 'What should I not miss in Lisbon?', answer: 'Ride Tram 28 (but expect crowds), visit Jerónimos Monastery and Belém Tower in Belém, explore the Alfama neighbourhood\'s viewpoints (miradouros) at sunset, eat a pastel de nata at Pastéis de Belém, take the ferry to Cacilhas for a cheap local lunch, and make a day trip to Sintra\'s fairy-tale palaces.' },
    { question: 'What is the best time to visit Lisbon?', answer: 'March–May and September–October are ideal: warm (20–26°C), manageable crowds, and low prices. June–August is peak season — very hot (30–35°C), crowded, and expensive but buzzing with the Santos Populares festival in June. October is arguably the best single month: summer warmth lingers and tourists have left.' },
  ],
  'best-time-to-visit-india': [
    { question: 'When is the best overall time to visit India?', answer: 'October to March is the best overall window for visiting India — the north is cool and dry, Rajasthan is at its most comfortable, and the southern coasts are sunny. November–February is peak tourist season. Different regions have very different climates, so the best time depends heavily on which part of India you\'re visiting.' },
    { question: 'What months should I avoid visiting India?', answer: 'May–June is peak summer in most of India (40–48°C in Delhi, Rajasthan, and central India) — extremely uncomfortable for sightseeing. July–September is monsoon season in most regions. However, Kerala, the Himalayas, and Ladakh can be beautiful in the post-monsoon and dry periods that don\'t align with this rule.' },
    { question: 'When is the best time to visit India for the first time?', answer: 'November to February is ideal for first-timers. Weather is mild across most of the country, all major festivals (Diwali, Holi prep, Republic Day, winter fairs) are in this window, and visibility is best for the Taj Mahal and northern monuments. Book accommodation early as this is peak season.' },
    { question: 'Does India have only one monsoon season?', answer: 'No. India has two monsoon systems. The Southwest Monsoon (June–September) hits the west coast first, then moves across most of India. The Northeast Monsoon (October–December) brings rain to Tamil Nadu, Andhra Pradesh, and Sri Lanka. This is why Chennai gets heavy rain in November while the rest of India is dry and pleasant.' },
  ],
  'bali-7-day-itinerary': [
    { question: 'What is the perfect 7-day Bali itinerary?', answer: 'Days 1–2: Seminyak/Canggu for beaches and sunset. Days 3–4: Ubud for Tegalalang rice terraces, Monkey Forest, and traditional cooking class. Day 5: Kintamani volcano lake and Tirta Empul water temple. Day 6: Nusa Penida day trip (Kelingking Beach, Angel\'s Billabong, Broken Beach). Day 7: Uluwatu Temple sunset + Kecak fire dance. ' },
    { question: 'Is 7 days enough for Bali?', answer: 'Seven days is the sweet spot for Bali — enough to cover the main zones (Seminyak/Canggu, Ubud, Uluwatu) and do at least one island day trip (Nusa Penida or Nusa Lembongan). You won\'t get bored, but you also won\'t feel rushed. Ten days allows a more relaxed pace or adds the north (Munduk, Singaraja).' },
    { question: 'Should I stay in one place in Bali or move around?', answer: 'Moving around is the Bali way. Most visitors split time between coastal Seminyak/Canggu (2–3 nights), Ubud in the hills (2–3 nights), and either Uluwatu/Nusa Dua in the south or a day trip to the Nusa Islands. Moving between these areas takes 1–2 hours by Grab or scooter.' },
    { question: 'What is the best way to get around Bali?', answer: 'Grab (Southeast Asia\'s Uber) is the most convenient option — pre-set price, no haggling. Scooter rental (IDR 60,000–100,000/day) is cheapest and gives the most freedom but requires riding experience on busy roads. Private car hire with driver (IDR 400,000–600,000/day) is comfortable for longer journeys and groups.' },
  ],
  'goa-complete-itinerary': [
    { question: 'What is the best itinerary for 5 days in Goa?', answer: 'Day 1: Arrive, explore Panaji and Old Goa churches. Day 2: North Goa — Anjuna flea market, Vagator beach, Chapora Fort. Day 3: South Goa — Palolem beach, Cotigao Wildlife Sanctuary. Day 4: Water sports at Baga or Calangute, Aguada Fort. Day 5: Spice plantation tour, Old Goa\'s Basilica of Bom Jesus, departure.' },
    { question: 'What is the best beach in Goa?', answer: 'Palolem in South Goa is the most beautiful — a perfect crescent of white sand with gentle waves, palm trees, and a relaxed vibe. For nightlife: Baga and Anjuna (North Goa). For space and quiet: Agonda and Mandrem. Arambol is popular with long-term travellers and has a bohemian backpacker scene.' },
    { question: 'Is Goa worth visiting in the monsoon?', answer: 'Goa in monsoon (June–September) is divisive. The landscape turns impossibly green and crowds disappear, but most beach shacks close, the sea is too rough for swimming, and some roads flood. Some travellers love the atmospheric empty beaches and heavy rain. Accommodation prices drop 50–70%. If you like rain, go for it.' },
    { question: 'What is the cheapest way to travel in Goa?', answer: 'Rent a scooter (₹300–400/day) — it\'s the local way to explore and far cheaper than taxis. Eat at local shacks and toddy shops away from the main beach strips (meals ₹100–200 vs ₹400–800 at tourist places). Stay in guesthouses in Panaji, Mapusa, or Old Goa rather than beach-facing properties for 30–50% savings.' },
  ],
  'andaman-islands-travel-guide': [
    { question: 'Do you need a permit to visit the Andaman Islands?', answer: 'Indian nationals do not need a special permit for most Andaman Islands including Port Blair, Havelock (Swaraj), Neil, and Long Island. A Restricted Area Permit (RAP) is required for North Andaman and Baratang Islands — this is free and issued on arrival at Port Blair airport. Foreign nationals have more restrictions.' },
    { question: 'What is the best time to visit Andaman Islands?', answer: 'November to April is the best time — calm seas, clear water for snorkelling and diving, and sunny skies. December to March is peak season (book ferries and hotels well in advance). May and October are shoulder months. Monsoon (May–October) brings rough seas, cancelled ferries, and most dive schools close — avoid for beach holidays.' },
    { question: 'How do I get between Andaman islands?', answer: 'Government ferries are the cheapest option (₹200–400) but can be infrequent and slow (2–3 hours Port Blair to Havelock). Private speedboats (Makruzz, Nautika) are faster (1–1.5 hours, ₹800–1,200) and more reliable. Book in advance during peak season as seats sell out days ahead.' },
    { question: 'Is Radhanagar Beach really one of Asia\'s best?', answer: 'Yes. Time magazine named it "Asia\'s Best Beach" and it genuinely lives up to it — powder-white sand stretching 2 km, turquoise water with gentle waves, and a forest backdrop. It\'s well-maintained and less commercialised than Goa. Visit early morning or late afternoon to avoid the midday crowds and for the best light.' },
  ],
  'jaipur-travel-guide-2025': [
    { question: 'Why is Jaipur called the Pink City?', answer: 'Jaipur was painted pink in 1876 by Maharaja Ram Singh II to welcome the Prince of Wales (later King Edward VII). Pink was the traditional colour of hospitality in Rajputana. By law, all buildings in the old city must remain painted in this distinctive terracotta-pink hue, maintained to this day.' },
    { question: 'How many days do you need in Jaipur?', answer: 'Two to three days covers the essentials: Amber Fort (half day), City Palace and Hawa Mahal (half day), Jantar Mantar, Nahargarh Fort sunset, and the bazaars of the old city. A third day allows a day trip to Abhaneri stepwell (Chand Baori), Pushkar, or Ranthambore National Park.' },
    { question: 'What is the best time to visit Jaipur?', answer: 'October to March is ideal — comfortable temperatures (15–28°C), clear blue skies, and all the festival energy of the Rajasthan winter season. The Jaipur Literature Festival (January) and Jaipur Kite Festival (Makar Sankranti, January 14) are highlights. Summer (April–June) is extremely hot (40–48°C); avoid unless you enjoy empty monuments.' },
    { question: 'Is Jaipur safe for solo female travellers?', answer: 'Jaipur is broadly safe but women travellers should exercise caution. The old city bazaars and tourist spots have increased police presence. Stick to registered auto-rickshaws (use Ola/Uber), avoid poorly lit areas after dark, dress conservatively at temples and markets, and firmly decline approaches from touts and "student photographers".' },
  ],
  'coorg-travel-guide': [
    { question: 'What is Coorg known for?', answer: 'Coorg (Kodagu) is known as the "Scotland of India" for its misty hills, coffee and cardamom estates, and cool climate. It\'s famous for its coffee plantations (walk through them and buy estate-fresh coffee), Dubare Elephant Camp, Abbey Falls, Raja\'s Seat viewpoint, and the unique Kodava warrior culture and cuisine.' },
    { question: 'What is the best time to visit Coorg?', answer: 'October to March is best — the rains have ended, the hills are green, and the weather is cool (15–22°C). October–November is particularly beautiful with the post-monsoon freshness. June–September is heavy monsoon — lush but wet with some roads flooding. Avoid the peak April–May heat.' },
    { question: 'How do I get to Coorg from Bangalore?', answer: 'Coorg is 260 km from Bangalore (~5–6 hours by road on NH275). KSRTC luxury buses run daily from Mysuru Road bus stand (₹400–600). Private cabs cost ₹3,000–4,000 one way. The nearest airport is Mangalore (160 km, 3.5 hrs) or Mysuru (120 km, 2.5 hrs). No train station in Coorg itself.' },
    { question: 'Is Coorg good for a weekend trip from Bangalore?', answer: 'Yes — Coorg is one of the most popular 2-night weekend getaways from Bangalore. The typical trip is Friday night departure, Saturday exploring the estates and waterfalls, Sunday morning Dubare Elephant Camp, and return Sunday evening. Book accommodation well in advance for weekends and holidays.' },
  ],
  'munnar-travel-guide': [
    { question: 'What is Munnar famous for?', answer: 'Munnar is famous for its endless tea plantations cascading over misty mountain slopes at 1,500–2,700m elevation. The Eravikulam National Park (home to the endangered Nilgiri Tahr), Top Station viewpoint, Mattupetty Lake, Attukad Waterfalls, and the beautiful drive along the Valparai route are top attractions.' },
    { question: 'What is the best time to visit Munnar?', answer: 'September to May is the best period. October–February is peak season — cool (8–18°C), clear skies, and the tea estates are beautifully green after the rains. Neelakurinji flowers (blooming once every 12 years) turn the hills blue — next bloom is expected around 2030. Monsoon (June–August) brings heavy rain but dramatic misty scenery.' },
    { question: 'How do I get to Munnar?', answer: 'The nearest airport is Cochin International Airport (110 km, 3–4 hours by road). Regular buses run from Ernakulam (Kochi) to Munnar (~4 hours, ₹150–300). Private cabs from Kochi cost ₹2,000–2,500. From Thekkady (Periyar), it\'s 90 km (~3 hours) through winding mountain roads — a spectacular drive.' },
    { question: 'Is Munnar suitable for trekking?', answer: 'Yes. Munnar offers excellent trekking: Anamudi Peak (2,695m, South India\'s highest) requires a forest permit via Eravikulam NP, Rajamala trek, the tea estate trails, and the Meesapulimala trek (guided overnight). Most treks require prior booking through the Kerala Forest Department. Best trekking months are October–February.' },
  ],
  'switzerland-travel-guide': [
    { question: 'How expensive is Switzerland for Indian tourists?', answer: 'Switzerland is among the world\'s most expensive countries. Budget travel (hostel, self-catering, train) runs CHF 120–180/day (~₹11,000–17,000). Mid-range with a 3-star hotel and restaurant meals: CHF 250–400/day. A train journey, fondue dinner, and museum entry can easily cost CHF 150 in one day. The Swiss Travel Pass helps manage transport costs.' },
    { question: 'Do Indians need a Schengen visa for Switzerland?', answer: 'Yes. Switzerland is part of the Schengen zone. Indian passport holders need a Schengen visa — apply at the Swiss consulate or VFS Global. Apply at least 6–8 weeks in advance. Switzerland\'s visa requirements are thorough: bank statements showing CHF 100–150/day, travel insurance, hotel bookings, and employment proof.' },
    { question: 'What is the best time to visit Switzerland?', answer: 'June–August is ideal for hiking and mountain activities — all cable cars and mountain passes are open, wildflowers are in bloom, and the days are long. December–March is for skiing (St. Moritz, Zermatt, Verbier). September–October has beautiful autumn colours and fewer tourists. April–May sees snow melt and some closures.' },
    { question: 'What is the cheapest way to see Switzerland?', answer: 'Buy the Swiss Travel Pass (3, 6, 8, or 15-day unlimited rail, bus, and boat travel — plus free museum entry). Cook at least some meals in supermarkets (Migros and Coop are affordable). Stay in Swiss Youth Hostels (officially excellent quality). Visit Bern, Basel, and Lucerne instead of just Zurich and Geneva, which are the most expensive cities.' },
  ],
  'barcelona-travel-guide-2025': [
    { question: 'Do Indians need a Schengen visa for Barcelona?', answer: 'Yes. Spain is part of the Schengen zone. Indian passport holders need a Schengen visa — apply at the Spanish consulate or VFS Global Spain. Apply 6–8 weeks before travel. Bring bank statements, a detailed itinerary, travel insurance (€30,000 coverage), hotel bookings, return flight confirmation, and employment/student proof.' },
    { question: 'Is Barcelona safe for tourists?', answer: 'Barcelona is a beautiful city but has Europe\'s highest pickpocketing rates — especially on Las Ramblas, at the Barceloneta beach, on the Metro (L3 line), and near Sagrada Família. Use a front-facing bag, keep phones in your pocket, avoid back pockets, and be wary of anyone who seems overly friendly or distracting.' },
    { question: 'What is the best time to visit Barcelona?', answer: 'May–June and September–October are ideal — warm (22–28°C), the beaches are swimmable, and the city is lively without the July–August crush. July–August is very hot (32–35°C+), extremely crowded, and expensive. The La Mercè festival in September and Sant Jordi (April 23, Barcelona\'s Valentine\'s Day) are highlights.' },
    { question: 'Do I need to book Sagrada Família in advance?', answer: 'Yes — always book Sagrada Família tickets online at least 2–4 weeks in advance (1–2 months for summer). Walk-up tickets often sell out by mid-morning. The same applies to Park Güell\'s Monumental Zone. For Casa Batlló and Casa Milà (La Pedrera), same-week advance booking usually works outside peak season.' },
  ],
  'kyoto-travel-guide': [
    { question: 'How many days do you need in Kyoto?', answer: 'Three to four days covers Kyoto\'s highlights: Fushimi Inari torii gates, Arashiyama Bamboo Grove, Kinkaku-ji (Golden Pavilion), Philosopher\'s Path, Gion geisha district, and Nijo Castle. A fourth or fifth day allows day trips to Nara (deer park + Todai-ji) or Osaka, both under an hour by train.' },
    { question: 'What is the best time to visit Kyoto?', answer: 'Late March–early April for cherry blossoms (sakura) along the Maruyama Park and Philosopher\'s Path — one of Japan\'s most beautiful sights but also the most crowded. Mid-November for autumn foliage (koyo) in Eikan-do and Tofuku-ji. Both peak seasons require accommodation booked 3–6 months ahead.' },
    { question: 'Is Kyoto better than Tokyo for a first Japan trip?', answer: 'They are radically different. Tokyo is urban, futuristic, and overwhelming in scale. Kyoto is historical, traditional, and walkable. For a first Japan trip, both together (Tokyo 3–4 days + Kyoto 3–4 days) is the classic and best approach. If forced to choose just one: Tokyo for energy and modernity, Kyoto for culture and tranquility.' },
    { question: 'Is it worth staying in a ryokan in Kyoto?', answer: 'Yes — staying in a traditional Japanese inn (ryokan) at least one night is one of the most memorable Japan experiences. It includes sleeping on futon, wearing yukata robes, soaking in an onsen (hot spring bath), and a multi-course kaiseki dinner. Budget ryokans start around ¥8,000–12,000/person ($50–80); authentic ones run ¥20,000–50,000+.' },
  ],
  'phuket-travel-guide': [
    { question: 'What is the best time to visit Phuket?', answer: 'November to April is the dry season — clear skies, calm Andaman Sea, and ideal beach conditions. December to February is peak season (busiest and most expensive). May to October is monsoon — heavy rain and rough seas make swimming dangerous, though prices drop 40–50% and some excellent deals exist. October is transitional and often fine.' },
    { question: 'Is Phuket good for families?', answer: 'Phuket is very family-friendly. Patong Beach has a wide range of activities including elephant sanctuaries, ATV tours, and waterparks. Kata and Karon beaches are calmer and more suitable for children than the Patong nightlife zone. Fantasea theme park and Phuket Aquarium are popular family attractions.' },
    { question: 'Which beach is best in Phuket?', answer: 'Freedom Beach (secluded, turquoise, no jet skis), Kata Noi (beautiful bay, calm waves, less developed), and Surin Beach (sophisticated, clear water, quieter than Patong) are the most beautiful. Patong has the best facilities and nightlife but is the most crowded. Rawai suits local-style beach days and seafood restaurants.' },
    { question: 'Do Indians need a visa for Thailand (Phuket)?', answer: 'No. As of 2024, Indian passport holders receive a free 30-day visa-free entry to Thailand (including Phuket). No application needed — just bring a return ticket and proof of accommodation. This policy was made permanent following successful visa-free trials for Indian and Taiwanese nationals.' },
  ],
  'himachal-pradesh-travel-guide': [
    { question: 'What is the best time to visit Himachal Pradesh?', answer: 'It depends on the region and activity. For Manali/Shimla: March–June (pleasant trekking weather) and October–November (clear skies, autumn colours). For snow: December–February in Manali and Solang Valley. For Spiti Valley: June–October (only window when roads are open). Monsoon (July–August) brings landslide risks on many roads.' },
    { question: 'How do I get around Himachal Pradesh?', answer: 'HRTC (Himachal Pradesh Road Transport Corporation) buses connect most towns and are cheap but slow. Private cabs are comfortable and preferred for multiple stops. Renting a motorcycle or SUV is popular for the Spiti Valley circuit. Trains only run to Shimla (toy train from Kalka) and Pathankot (for Dharamshala connection).' },
    { question: 'Is Himachal Pradesh safe for solo travel?', answer: 'Yes — Himachal is one of India\'s safest states for solo travellers, including solo women. The hill towns are relaxed, locals are hospitable, and crime against tourists is extremely rare. The main risks are altitude sickness above 3,500m, mountain road accidents, and flash floods in monsoon. Always check road conditions before high-altitude travel.' },
    { question: 'What permits are required for Himachal Pradesh?', answer: 'No permits are required for Indian nationals for most of Himachal Pradesh including Shimla, Manali, and Dharamshala. Inner Line Permits (ILP) are required for Rohtang Pass (online permit, limited vehicles per day) and for some border areas near Spiti. Foreign nationals need additional permits for Spiti, Kinnaur, and areas near the China border.' },
  ],
  'solo-travel-india-tips': [
    { question: 'Is India safe for solo female travellers?', answer: 'India requires more vigilance for solo women than many destinations, but millions of women travel India solo every year safely. Rajasthan, Kerala, Goa, Himachal Pradesh, and Uttarakhand are considered safer regions. Take standard precautions: dress modestly, avoid isolated areas after dark, book verified accommodation, and share your itinerary with someone at home. Women\'s compartments exist on trains.' },
    { question: 'What are the best destinations for solo travel in India?', answer: 'Rishikesh (yoga, backpacker community), McLeod Ganj/Dharamshala (spiritual, traveller-friendly), Hampi (backpacker favourite, safe, fascinating), Pushkar (calm, easy, very traveller-oriented), Kasol (trekker hub), Goa (established solo scene), and Kerala (safe, friendly, well-organised tourism).' },
    { question: 'How much money do I need for solo travel in India?', answer: 'India is very affordable for solo travellers. Budget travel (hostels, dhabas, buses) costs ₹800–1,500/day. Mid-range (private guesthouses, restaurants, occasional taxis) runs ₹2,000–3,500/day. Backpacker hostels (₹300–600/dorm bed) are widespread in Goa, Rishikesh, Hampi, and most major cities.' },
    { question: 'What apps are essential for solo travel in India?', answer: 'IRCTC (train booking), Ola/Uber (cabs), Google Maps (offline download recommended), Zostel/Booking.com (accommodation), MakeMyTrip (flights/buses), and iTranslate for regional languages. Keep an offline copy of your itinerary and emergency contacts. WhatsApp is how most hostels and guesthouses communicate.' },
  ],
  'hong-kong-travel-guide': [
    { question: 'Do Indians need a visa for Hong Kong?', answer: 'No — Indian passport holders get a 14-day visa-free entry to Hong Kong (SAR). No advance application needed. Note: this is separate from mainland China, which requires a full Chinese visa. You can visit Hong Kong visa-free but crossing to Shenzhen or other mainland cities requires a Chinese visa.' },
    { question: 'How many days do you need in Hong Kong?', answer: 'Three to four days is ideal. Day 1: Victoria Peak, Central and Soho. Day 2: Temple Street Night Market, Mong Kok, Tian Tan Buddha on Lantau Island. Day 3: Hong Kong Disneyland or day trip to Macau (45-min ferry). Day 4: Stanley, Aberdeen Floating Village, final shopping in Tsim Sha Tsui.' },
    { question: 'Is Hong Kong expensive?', answer: 'Hong Kong is expensive for accommodation and restaurant dining. A mid-range hotel costs HKD 700–1,500/night (~₹7,500–16,000). However, public transport (MTR) is cheap and excellent, and local restaurants (cha chaan teng, wonton noodle shops, dim sum restaurants) offer incredible food for HKD 50–120/meal (~₹500–1,300).' },
    { question: 'What has changed in Hong Kong since 2019?', answer: 'The political landscape has changed significantly, and some international businesses and expats have relocated. For tourists, the practical experience remains largely the same — the MTR is world-class, food is extraordinary, and the skyline is as impressive as ever. The shopping and nightlife scene has evolved but continues. Always check current entry requirements before travel.' },
  ],
  'cheap-countries-from-india': [
    { question: 'What is the cheapest country to visit from India?', answer: 'Nepal and Bhutan are the cheapest overall — Indians pay no visa fees, accommodation and food are very affordable, and the cultural experience is extraordinary. Among international destinations, Thailand, Vietnam, Sri Lanka, and Indonesia (Bali) consistently top the budget travel lists from India, with total trip costs of ₹40,000–70,000 for 7–10 days including flights.' },
    { question: 'Which countries offer visa-free or visa-on-arrival access to Indians?', answer: 'Visa-free/on-arrival countries for Indians include Thailand (30 days, no visa), Nepal (unlimited), Bhutan (e-Permit required), Sri Lanka (free ETA), Maldives (30 days on arrival), Mauritius (90 days), Indonesia/Bali (30 days VOA), UAE/Dubai (with valid US/UK/EU visa), and around 60 other countries. Always verify current rules before booking.' },
    { question: 'When is the cheapest time to fly internationally from India?', answer: 'January–March (after peak New Year travel) and July–August (Indian monsoon, less demand) are typically the cheapest months for international flights from India. Book 2–3 months in advance for the best fares. Emirates, Qatar, Air Arabia, IndiGo (for short-haul), and AirAsia frequently have competitive sales.' },
    { question: 'Are budget international trips from India possible under ₹50,000?', answer: 'Yes. Thailand (7 days, ~₹40,000–55,000 all-in), Bali (7 days, ~₹45,000–65,000), Sri Lanka (5 days, ~₹30,000–45,000), Nepal (5 days, ~₹20,000–35,000), and Vietnam (7 days, ~₹50,000–70,000) are all achievable. The biggest variable is flight cost — flexible travel dates and advance booking unlock the best deals.' },
  ],
  'best-hill-stations-india': [
    { question: 'Which is the most beautiful hill station in India?', answer: 'Munnar (Kerala) and Coorg (Karnataka) are consistently ranked India\'s most beautiful for tea and coffee estate landscapes. For drama and Himalayan grandeur: Manali, Leh/Ladakh, and Spiti. For old-world colonial charm: Ooty, Shimla, and Darjeeling. Each region offers something different — the "most beautiful" depends entirely on what kind of landscape you love.' },
    { question: 'Which hill station is closest to Delhi?', answer: 'Shimla is the classic choice (~370 km, 7–8 hrs). Mussoorie (290 km, 6 hrs) and Nainital (310 km, 6 hrs) are also popular. For a quicker escape, Lansdowne (250 km, 5 hrs) and Kasauli (250 km, 5 hrs) are less-crowded alternatives. Manali is further (530 km, 10–12 hrs) but offers more dramatic mountain scenery.' },
    { question: 'What is the best time to visit hill stations in India?', answer: 'April–June is peak season for most hill stations — perfect escape from the plains\' heat, schools are on holiday, and weather is pleasant (12–22°C). October–November is excellent post-monsoon with clear skies. December–February brings snow to Shimla and Manali (beautiful but cold). Avoid July–September monsoon for road travel in hills — landslides are common.' },
    { question: 'Which Indian hill station is least crowded?', answer: 'Lansdowne, Munsiyari, Khajjiar, Chail, Kanatal, Ramgarh (Uttarakhand), and Yelagiri (Tamil Nadu) remain relatively undiscovered compared to Shimla, Manali, and Ooty. For Himalayan high-altitude solitude, Kalpa (Kinnaur), Sangla Valley, and Tirthan Valley in Himachal Pradesh are stunning and far less visited.' },
  ],
};

const filePath = new URL('../src/lib/blog.ts', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1');
let content = readFileSync(filePath, 'utf8');

let updated = 0;
let skipped = 0;

for (const [slug, faqs] of Object.entries(FAQ_DATA)) {
  // Find this post's slug declaration
  const slugPattern = `slug: '${slug}'`;
  const slugIdx = content.indexOf(slugPattern);
  if (slugIdx === -1) { console.warn(`SKIP: slug '${slug}' not found`); skipped++; continue; }

  // Find the content array closing ]
  // The pattern we look for after the slug: content: [...], followed by closing },
  // We search forward from the slug for the last ], before the next top-level },
  // Strategy: find "    ],\n  }," pattern that closes this post object
  // Walk forward from slugIdx to find content: [ then its matching ]
  const afterSlug = content.indexOf('content: [', slugIdx);
  if (afterSlug === -1) { console.warn(`SKIP: no content array for '${slug}'`); skipped++; continue; }

  // Find the matching close of content array by counting brackets
  let depth = 0;
  let i = afterSlug + 'content: '.length;
  for (; i < content.length; i++) {
    if (content[i] === '[') depth++;
    else if (content[i] === ']') { depth--; if (depth === 0) break; }
  }
  // i is now at the closing ] of content array
  // Check if faqs already exists right after
  const afterContent = content.slice(i, i + 200);
  if (afterContent.includes('faqs:')) {
    console.log(`ALREADY HAS FAQS: ${slug}`);
    skipped++;
    continue;
  }

  // Build the faqs string
  const faqsStr = `,\n    faqs: [\n` +
    faqs.map(f =>
      `      {\n        question: ${JSON.stringify(f.question)},\n        answer: ${JSON.stringify(f.answer)},\n      }`
    ).join(',\n') +
    ',\n    ]';

  // Insert after the closing ] of content array (before the comma+newline+  },)
  content = content.slice(0, i + 1) + faqsStr + content.slice(i + 1);
  console.log(`DONE: ${slug} (${faqs.length} FAQs)`);
  updated++;
}

writeFileSync(filePath, content, 'utf8');
console.log(`\nDone. Updated: ${updated}, Skipped: ${skipped}`);
